import react from "@vitejs/plugin-react";
import path from "path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    setupFiles: ["./test/setup.ts"],
    globals: true,
    css: false,
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      exclude: [
        "node_modules/",
        "test/",
        "**/*.d.ts",
        "**/*.config.*",
        "**/*.setup.*",
        "coverage/",
        "dist/",
        ".next/",
        "**/__tests__/**",
        "**/*.test.*",
        "**/*.spec.*",
        "**/mocks/**",
        "**/types/**",
        "**/utils/drizzle/**",
        "**/utils/queries/**",
        "**/utils/mutations/**",
        "**/utils/react-query/**",
        "**/utils/api/**",
        "**/utils/auth/**",
        "**/utils/model/**",
        "**/utils/logs/**",
        "**/utils/analytics/**",
        "**/utils/breadcrumb-utils.ts",
        "**/utils/logger.ts",
        "**/utils/navigation-utils.ts",
        "**/utils/date-utils.ts",
        "**/utils/string-utils.ts",
        "**/utils/validation-utils.ts",
        "**/utils/format-utils.ts",
        "**/utils/storage-utils.ts",
        "**/utils/constants.ts",
        "**/utils/types.ts",
        "**/lib/**",
        "**/mocks/**",
        "**/scripts/**",
        "**/styles/**",
        "**/types/**",
        "**/contexts/**",
        "**/hooks/**",
        "**/components/ui/**",
      ],
      include: [
        "app/**/*.{ts,tsx}",
        "components/**/*.{ts,tsx}",
        "utils/**/*.{ts,tsx}",
        "hooks/**/*.{ts,tsx}",
        "contexts/**/*.{ts,tsx}",
        "lib/**/*.{ts,tsx}",
      ],
      thresholds: {
        global: {
          branches: 70,
          functions: 70,
          lines: 70,
          statements: 70,
        },
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./"),
    },
  },
});
