-- Table definitions + constraints: agents_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: agents_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agents_resource (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT agents_created_at_not_null1 NOT NULL,
    active boolean DEFAULT true CONSTRAINT agents_active_not_null1 NOT NULL,
    generated boolean DEFAULT false CONSTRAINT agents_generated_not_null1 NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT agents_mcp_not_null1 NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT agents_id_new_not_null NOT NULL,
    name text,
    description text,
    department_ids uuid[] DEFAULT ARRAY[]::uuid[],
    temperature real,
    reasoning text,
    tool_ids uuid[] DEFAULT ARRAY[]::uuid[],
    quality public.quality_type,
    model_id uuid,
    prompt_id uuid,
    instruction_ids uuid[] DEFAULT ARRAY[]::uuid[],
    voices text[] DEFAULT ARRAY[]::text[] NOT NULL,
    rubric_id uuid
);


--

-- Name: agents_resource agents_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agents_resource
    ADD CONSTRAINT agents_resource_pkey PRIMARY KEY (id);


--
