-- Table definitions + constraints: descriptions_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: descriptions_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.descriptions_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT descriptions_id_not_null NOT NULL,
    description text CONSTRAINT descriptions_description_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT descriptions_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT descriptions_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT descriptions_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT descriptions_mcp_not_null NOT NULL
);


--

-- Name: descriptions_resource descriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.descriptions_resource
    ADD CONSTRAINT descriptions_pkey PRIMARY KEY (id);


--
