-- Tables: examples_*_resource (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: examples_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.examples_resource (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT examples_created_at_not_null NOT NULL,
    example text CONSTRAINT examples_example_not_null NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT examples_id_v7_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT examples_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT examples_mcp_not_null NOT NULL
);


--
