-- Tables: groups_*_resource (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: groups_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groups_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--
