-- Table definitions + constraints: personas_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: personas_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_resource (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT personas_created_at_not_null1 NOT NULL,
    active boolean DEFAULT true CONSTRAINT personas_active_not_null1 NOT NULL,
    generated boolean DEFAULT false CONSTRAINT personas_generated_not_null1 NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT personas_mcp_not_null1 NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT personas_id_new_not_null NOT NULL,
    name text,
    description text,
    icon text,
    color text,
    department_ids uuid[] DEFAULT ARRAY[]::uuid[],
    instructions text,
    examples text[] DEFAULT ARRAY[]::text[],
    parameter_ids uuid[] DEFAULT '{}'::uuid[],
    parameter_field_ids uuid[] DEFAULT '{}'::uuid[]
);


--

-- Name: personas_resource personas_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_resource
    ADD CONSTRAINT personas_resource_pkey PRIMARY KEY (id);


--
