-- Table definitions + constraints: points_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: points_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.points_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT points_id_not_null NOT NULL,
    value integer CONSTRAINT points_value_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT points_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT points_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT points_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT points_mcp_not_null NOT NULL,
    type public.point_type DEFAULT 'total'::public.point_type NOT NULL
);


--

-- Name: points_resource points_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_resource
    ADD CONSTRAINT points_pkey PRIMARY KEY (id);


--
