-- Table definitions + constraints: protocols_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: protocols_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.protocols_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT protocols_id_not_null NOT NULL,
    value text CONSTRAINT protocols_value_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT protocols_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT protocols_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT protocols_mcp_not_null NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: protocols_resource protocols_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.protocols_resource
    ADD CONSTRAINT protocols_pkey PRIMARY KEY (id);


--

-- Name: protocols_resource protocols_value_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.protocols_resource
    ADD CONSTRAINT protocols_value_key UNIQUE (value);


--
