-- Table definitions + constraints: provider_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: provider_keys_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_keys_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    provider_id uuid NOT NULL,
    key_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    key text DEFAULT ''::text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL
);


--

-- Name: provider_keys_resource provider_keys_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_keys_resource
    ADD CONSTRAINT provider_keys_resource_pkey PRIMARY KEY (id);


--
