-- Table definitions + constraints: providers_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: providers_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.providers_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT providers_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT providers_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT providers_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT providers_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT providers_mcp_not_null NOT NULL,
    name text,
    description text,
    department_ids uuid[] DEFAULT ARRAY[]::uuid[],
    value text,
    endpoint text,
    key text
);


--

-- Name: providers_resource providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers_resource
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
