-- Table definitions + constraints: questions_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: questions_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.questions_resource (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT questions_created_at_not_null NOT NULL,
    question_text text CONSTRAINT questions_question_text_not_null NOT NULL,
    allow_multiple boolean DEFAULT false CONSTRAINT questions_allow_multiple_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT questions_active_not_null NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT questions_id_v7_not_null NOT NULL,
    "time" integer CONSTRAINT questions_time_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT questions_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT questions_mcp_not_null NOT NULL
);


--

-- Name: questions_resource questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_resource
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
