-- Table definitions + constraints: resources_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: resources_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resources_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT domains_resource_id_not_null NOT NULL,
    resource public.resource_type CONSTRAINT domains_resource_resource_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT domains_resource_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT domains_resource_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT domains_resource_mcp_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT domains_resource_created_at_not_null NOT NULL
);


--

-- Name: resources_resource domains_resource_resource_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources_resource
    ADD CONSTRAINT domains_resource_resource_key UNIQUE (resource);


--

-- Name: resources_resource resources_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources_resource
    ADD CONSTRAINT resources_resource_pkey PRIMARY KEY (id);


--
