-- Tables: roles_*_resource (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: roles_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    role public.profile_type NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    icon_id uuid,
    color_id uuid,
    artifacts text[] DEFAULT '{}'::text[] NOT NULL
);


--
