-- Table definitions + constraints: runs_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: runs_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.runs_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: runs_resource runs_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs_resource
    ADD CONSTRAINT runs_resource_pkey PRIMARY KEY (id);


--
