-- Tables: scenario_*_resource (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: scenario_flags_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scenario_flags_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT scenario_flags_resource_new_id_not_null NOT NULL,
    flag_id uuid CONSTRAINT scenario_flags_resource_new_flag_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT scenario_flags_resource_new_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT scenario_flags_resource_new_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT scenario_flags_resource_new_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT scenario_flags_resource_new_active_not_null NOT NULL,
    scenario_id uuid CONSTRAINT scenario_flags_resource_scenario_id_new_not_null NOT NULL
);


--

-- Name: scenario_positions_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scenario_positions_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT scenario_positions_resource_new_id_not_null NOT NULL,
    value integer CONSTRAINT scenario_positions_resource_new_value_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT scenario_positions_resource_new_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT scenario_positions_resource_new_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT scenario_positions_resource_new_mcp_not_null NOT NULL,
    scenario_id uuid CONSTRAINT scenario_positions_resource_scenario_id_new_not_null NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: scenario_rubrics_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scenario_rubrics_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    rubric_id uuid CONSTRAINT scenario_rubrics_resource_rubric_id_new_not_null NOT NULL,
    scenario_id uuid CONSTRAINT scenario_rubrics_resource_scenario_id_new_not_null NOT NULL
);


--

-- Name: scenario_time_limits_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scenario_time_limits_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    time_limit_seconds integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    scenario_id uuid CONSTRAINT scenario_time_limits_resource_scenario_id_new_not_null NOT NULL,
    negative boolean DEFAULT false NOT NULL,
    CONSTRAINT scenario_time_limits_resource_time_limit_seconds_check CHECK ((time_limit_seconds > 0))
);


--
