-- Table definitions + constraints: slugs_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: slugs_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.slugs_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT slugs_id_not_null NOT NULL,
    value text CONSTRAINT slugs_value_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT slugs_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT slugs_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT slugs_mcp_not_null NOT NULL
);


--

-- Name: slugs_resource slugs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slugs_resource
    ADD CONSTRAINT slugs_pkey PRIMARY KEY (id);


--

-- Name: slugs_resource slugs_value_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slugs_resource
    ADD CONSTRAINT slugs_value_key UNIQUE (value);


--
