-- Table definitions + constraints: voices_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: voices_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voices_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT voices_id_not_null NOT NULL,
    voice text CONSTRAINT voices_voice_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT voices_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT voices_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT voices_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT voices_mcp_not_null NOT NULL
);


--

-- Name: voices_resource voices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voices_resource
    ADD CONSTRAINT voices_pkey PRIMARY KEY (id);


--
