"""resource_modalities_relation (resource_type → modality_type)."""

from __future__ import annotations

RESOURCE_MODALITIES: dict[str, frozenset[str]] = {
    "agents": frozenset({"call"}),
    "auths": frozenset({"call"}),
    "cohorts": frozenset({"call"}),
    "colors": frozenset({"call"}),
    "departments": frozenset({"call"}),
    "descriptions": frozenset({"call"}),
    "documents": frozenset({"call", "document"}),
    "endpoints": frozenset({"call"}),
    "evals": frozenset({"call"}),
    "examples": frozenset({"call"}),
    "fields": frozenset({"call"}),
    "flags": frozenset({"call"}),
    "icons": frozenset({"call"}),
    "images": frozenset({"call", "image"}),
    "instructions": frozenset({"call"}),
    "items": frozenset({"call"}),
    "keys": frozenset({"call"}),
    "models": frozenset({"call"}),
    "names": frozenset({"call"}),
    "objectives": frozenset({"call"}),
    "options": frozenset({"call"}),
    "parameters": frozenset({"call"}),
    "personas": frozenset({"call"}),
    "points": frozenset({"call"}),
    "problem_statements": frozenset({"call"}),
    "profiles": frozenset({"call"}),
    "prompts": frozenset({"call"}),
    "protocols": frozenset({"call"}),
    "questions": frozenset({"call"}),
    "rubrics": frozenset({"call"}),
    "scenarios": frozenset({"call"}),
    "settings": frozenset({"call"}),
    "simulations": frozenset({"call"}),
    "slugs": frozenset({"call"}),
    "standard_groups": frozenset({"call"}),
    "thresholds": frozenset({"call"}),
    "videos": frozenset({"call", "video"}),
}
