"""role → artifacts accessible to that role."""

from __future__ import annotations

ROLE_ARTIFACTS: dict[str, frozenset[str]] = {
    "admin": frozenset(
        {
            "agent",
            "attempt",
            "benchmark",
            "chat",
            "cohort",
            "dashboard",
            "document",
            "field",
            "group",
            "health",
            "home",
            "leaderboard",
            "model",
            "parameter",
            "persona",
            "practice",
            "pricing",
            "profile",
            "provider",
            "record",
            "reports",
            "scenario",
            "settings",
            "simulation",
            "test",
            "tool",
        }
    ),
    "guest": frozenset({"attempt", "chat", "practice"}),
    "instructional": frozenset(
        {
            "attempt",
            "benchmark",
            "chat",
            "cohort",
            "dashboard",
            "group",
            "home",
            "leaderboard",
            "persona",
            "practice",
            "pricing",
            "record",
            "reports",
            "scenario",
            "simulation",
            "test",
        }
    ),
    "member": frozenset(
        {
            "attempt",
            "chat",
            "home",
            "leaderboard",
            "practice",
        }
    ),
    "superadmin": frozenset(
        {
            "agent",
            "attempt",
            "auth",
            "benchmark",
            "chat",
            "cohort",
            "dashboard",
            "department",
            "document",
            "eval",
            "field",
            "group",
            "health",
            "home",
            "leaderboard",
            "model",
            "parameter",
            "persona",
            "practice",
            "pricing",
            "profile",
            "provider",
            "record",
            "reports",
            "rubric",
            "scenario",
            "settings",
            "simulation",
            "test",
            "tool",
        }
    ),
}
