"""SQL type definitions and registry - AUTO-GENERATED - DO NOT EDIT MANUALLY.

This file is automatically generated by sql-compile. All edits will be overwritten.
"""

from typing import Any
from typing import TYPE_CHECKING, Literal, Type, TypeVar, overload, cast

from uuid import UUID

from pydantic import BaseModel
from pydantic import Field


# Type variables for generic return types
TInput = TypeVar("TInput", bound=BaseModel)
TOutput = TypeVar("TOutput", bound=BaseModel)

# Type alias for SQL strings loaded from files (semantic clarity)
SqlString = str


# ============================================================================
# TYPE DEFINITIONS
# ============================================================================


# Generated from: agents/test_create_test_profile

class Agents/testCreateTestProfileSqlParams(BaseModel):

    first_name: str | None = None
    last_name: str | None = None
    role: str | None = None
    email: str | None = None

    def to_tuple(self) -> tuple[Any, ...]:
        return (
            self.first_name,
            self.last_name,
            self.role,
            self.email,
        )

class Agents/testCreateTestProfileSqlRow(BaseModel):

    profile_id: UUID | None = None
    email: str | None = None
    role: str | None = None

class Agents/testCreateTestProfileApiRequest(BaseModel):

    first_name: str | None = None
    last_name: str | None = None
    role: str | None = None
    email: str | None = None

class Agents/testCreateTestProfileApiResponse(BaseModel):

    profile_id: UUID | None = None
    email: str | None = None
    role: str | None = None



# Generated from: agents/test_create_test_prompt

class Agents/testCreateTestPromptSqlParams(BaseModel):

    system_prompt: str | None = None

    def to_tuple(self) -> tuple[Any, ...]:
        return (
            self.system_prompt,
        )

class Agents/testCreateTestPromptSqlRow(BaseModel):

    prompt_id: UUID | None = None
    system_prompt: str | None = None
    created_at: str | None = None

class Agents/testCreateTestPromptApiRequest(BaseModel):

    system_prompt: str | None = None

class Agents/testCreateTestPromptApiResponse(BaseModel):

    prompt_id: UUID | None = None
    system_prompt: str | None = None
    created_at: str | None = None



# Generated from: agents/test_get_agent_department_link

class Agents/testGetAgentDepartmentLinkSqlParams(BaseModel):

    agent_id: UUID
    department_id: UUID

    def to_tuple(self) -> tuple[Any, ...]:
        return (
            self.agent_id,
            self.department_id,
        )

class Agents/testGetAgentDepartmentLinkSqlRow(BaseModel):

    agent_id: UUID | None = None
    department_id: UUID | None = None
    active: bool | None = None

class Agents/testGetAgentDepartmentLinkApiRequest(BaseModel):

    agent_id: UUID
    department_id: UUID

class Agents/testGetAgentDepartmentLinkApiResponse(BaseModel):

    agent_id: UUID | None = None
    department_id: UUID | None = None
    active: bool | None = None



# Generated from: agents/test_get_agent_department_links

class Agents/testGetAgentDepartmentLinksSqlParams(BaseModel):

    agent_id: UUID

    def to_tuple(self) -> tuple[Any, ...]:
        return (
            self.agent_id,
        )

class Agents/testGetAgentDepartmentLinksSqlRow(BaseModel):

    agent_id: UUID | None = None
    department_id: UUID | None = None
    active: bool | None = None

class Agents/testGetAgentDepartmentLinksApiRequest(BaseModel):

    agent_id: UUID

class Agents/testGetAgentDepartmentLinksApiResponse(BaseModel):

    agent_id: UUID | None = None
    department_id: UUID | None = None
    active: bool | None = None



# Generated from: agents/test_get_agent_prompt_link

class Agents/testGetAgentPromptLinkSqlParams(BaseModel):

    agent_id: UUID

    def to_tuple(self) -> tuple[Any, ...]:
        return (
            self.agent_id,
        )

class Agents/testGetAgentPromptLinkSqlRow(BaseModel):

    agent_id: UUID | None = None
    prompt_id: UUID | None = None
    active: bool | None = None

class Agents/testGetAgentPromptLinkApiRequest(BaseModel):

    agent_id: UUID

class Agents/testGetAgentPromptLinkApiResponse(BaseModel):

    agent_id: UUID | None = None
    prompt_id: UUID | None = None
    active: bool | None = None



# Generated from: agents/test_get_first_department

class Agents/testGetFirstDepartmentSqlParams(BaseModel):

    pass

class Agents/testGetFirstDepartmentSqlRow(BaseModel):

    department_id: UUID | None = None
    title: str | None = None

class Agents/testGetFirstDepartmentApiRequest(BaseModel):

    pass

class Agents/testGetFirstDepartmentApiResponse(BaseModel):

    department_id: UUID | None = None
    title: str | None = None



# Generated from: agents/test_get_first_model

class Agents/testGetFirstModelSqlParams(BaseModel):

    pass

class Agents/testGetFirstModelSqlRow(BaseModel):

    model_id: UUID | None = None
    name: str | None = None
    provider_id: UUID | None = None

class Agents/testGetFirstModelApiRequest(BaseModel):

    pass

class Agents/testGetFirstModelApiResponse(BaseModel):

    model_id: UUID | None = None
    name: str | None = None
    provider_id: UUID | None = None



# Generated from: get_cs_dept_id

class GetCsDeptIdSqlParams(BaseModel):

    pass

class GetCsDeptIdSqlRow(BaseModel):

    department_id: UUID | None = None
    title: str | None = None

class GetCsDeptIdApiRequest(BaseModel):

    pass

class GetCsDeptIdApiResponse(BaseModel):

    department_id: UUID | None = None
    title: str | None = None



# Generated from: get_or_create_test_department

class GetOrCreateTestDepartmentSqlParams(BaseModel):

    title: str | None = None
    description: str | None = None

    def to_tuple(self) -> tuple[Any, ...]:
        return (
            self.title,
            self.description,
        )

class GetOrCreateTestDepartmentSqlRow(BaseModel):

    department_id: UUID | None = None
    title: str | None = None

class GetOrCreateTestDepartmentApiRequest(BaseModel):

    title: str | None = None
    description: str | None = None

class GetOrCreateTestDepartmentApiResponse(BaseModel):

    department_id: UUID | None = None
    title: str | None = None



# Generated from: get_or_create_test_model

class GetOrCreateTestModelSqlParams(BaseModel):

    name: str | None = None

    def to_tuple(self) -> tuple[Any, ...]:
        return (
            self.name,
        )

class GetOrCreateTestModelSqlRow(BaseModel):

    model_id: UUID | None = None
    name: str | None = None
    provider_id: UUID | None = None

class GetOrCreateTestModelApiRequest(BaseModel):

    name: str | None = None

class GetOrCreateTestModelApiResponse(BaseModel):

    model_id: UUID | None = None
    name: str | None = None
    provider_id: UUID | None = None



# Generated from: get_or_create_test_profile

class GetOrCreateTestProfileSqlParams(BaseModel):

    email: str | None = None
    role: str | None = None
    first_name: str | None = None
    last_name: str | None = None

    def to_tuple(self) -> tuple[Any, ...]:
        return (
            self.email,
            self.role,
            self.first_name,
            self.last_name,
        )

class GetOrCreateTestProfileSqlRow(BaseModel):

    profile_id: UUID | None = None
    email: str | None = None
    role: str | None = None

class GetOrCreateTestProfileApiRequest(BaseModel):

    email: str | None = None
    role: str | None = None
    first_name: str | None = None
    last_name: str | None = None

class GetOrCreateTestProfileApiResponse(BaseModel):

    profile_id: UUID | None = None
    email: str | None = None
    role: str | None = None



# Generated from: get_superadmin_alias

class GetSuperadminAliasSqlParams(BaseModel):

    email: str | None = None

    def to_tuple(self) -> tuple[Any, ...]:
        return (
            self.email,
        )

class GetSuperadminAliasSqlRow(BaseModel):

    profile_id: UUID | None = None
    email: str | None = None
    actor_name: str | None = None

class GetSuperadminAliasApiRequest(BaseModel):

    email: str | None = None

class GetSuperadminAliasApiResponse(BaseModel):

    profile_id: UUID | None = None
    email: str | None = None
    actor_name: str | None = None




# ============================================================================
# REGISTRY
# ============================================================================

_registry: dict[str, tuple[str, str, str, str]] = {
    "tests/sql/v4/integration/api/agents/test_create_test_profile_v4_complete.sql": (
        "Agents/testCreateTestProfileSqlParams",
        "Agents/testCreateTestProfileSqlRow",
        "Agents/testCreateTestProfileApiRequest",
        "Agents/testCreateTestProfileApiResponse",
    ),
    "tests/sql/v4/integration/api/agents/test_create_test_prompt_v4_complete.sql": (
        "Agents/testCreateTestPromptSqlParams",
        "Agents/testCreateTestPromptSqlRow",
        "Agents/testCreateTestPromptApiRequest",
        "Agents/testCreateTestPromptApiResponse",
    ),
    "tests/sql/v4/integration/api/agents/test_get_agent_department_link_v4_complete.sql": (
        "Agents/testGetAgentDepartmentLinkSqlParams",
        "Agents/testGetAgentDepartmentLinkSqlRow",
        "Agents/testGetAgentDepartmentLinkApiRequest",
        "Agents/testGetAgentDepartmentLinkApiResponse",
    ),
    "tests/sql/v4/integration/api/agents/test_get_agent_department_links_v4_complete.sql": (
        "Agents/testGetAgentDepartmentLinksSqlParams",
        "Agents/testGetAgentDepartmentLinksSqlRow",
        "Agents/testGetAgentDepartmentLinksApiRequest",
        "Agents/testGetAgentDepartmentLinksApiResponse",
    ),
    "tests/sql/v4/integration/api/agents/test_get_agent_prompt_link_v4_complete.sql": (
        "Agents/testGetAgentPromptLinkSqlParams",
        "Agents/testGetAgentPromptLinkSqlRow",
        "Agents/testGetAgentPromptLinkApiRequest",
        "Agents/testGetAgentPromptLinkApiResponse",
    ),
    "tests/sql/v4/integration/api/agents/test_get_first_department_v4_complete.sql": (
        "Agents/testGetFirstDepartmentSqlParams",
        "Agents/testGetFirstDepartmentSqlRow",
        "Agents/testGetFirstDepartmentApiRequest",
        "Agents/testGetFirstDepartmentApiResponse",
    ),
    "tests/sql/v4/integration/api/agents/test_get_first_model_v4_complete.sql": (
        "Agents/testGetFirstModelSqlParams",
        "Agents/testGetFirstModelSqlRow",
        "Agents/testGetFirstModelApiRequest",
        "Agents/testGetFirstModelApiResponse",
    ),
    "tests/sql/v4/integration/helpers/test_get_cs_dept_id_v4_complete.sql": (
        "GetCsDeptIdSqlParams",
        "GetCsDeptIdSqlRow",
        "GetCsDeptIdApiRequest",
        "GetCsDeptIdApiResponse",
    ),
    "tests/sql/v4/integration/helpers/test_get_or_create_test_department_v4_complete.sql": (
        "GetOrCreateTestDepartmentSqlParams",
        "GetOrCreateTestDepartmentSqlRow",
        "GetOrCreateTestDepartmentApiRequest",
        "GetOrCreateTestDepartmentApiResponse",
    ),
    "tests/sql/v4/integration/helpers/test_get_or_create_test_model_v4_complete.sql": (
        "GetOrCreateTestModelSqlParams",
        "GetOrCreateTestModelSqlRow",
        "GetOrCreateTestModelApiRequest",
        "GetOrCreateTestModelApiResponse",
    ),
    "tests/sql/v4/integration/helpers/test_get_or_create_test_profile_v4_complete.sql": (
        "GetOrCreateTestProfileSqlParams",
        "GetOrCreateTestProfileSqlRow",
        "GetOrCreateTestProfileApiRequest",
        "GetOrCreateTestProfileApiResponse",
    ),
    "tests/sql/v4/integration/helpers/test_get_superadmin_alias_v4_complete.sql": (
        "GetSuperadminAliasSqlParams",
        "GetSuperadminAliasSqlRow",
        "GetSuperadminAliasApiRequest",
        "GetSuperadminAliasApiResponse",
    ),
}


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_sql_types(sql_path: str) -> tuple[Type[BaseModel], Type[BaseModel]]:
    """Get SQL input and output types for a SQL file path.
    
    Args:
        sql_path: SQL file path (e.g., "app/sql/v4/agents/get_agent_new_complete.sql")
    
    Returns:
        Tuple of (SqlParamsType, SqlRowType)
    
    Raises:
        ValueError: If no types are found for the SQL file path
    """
    if sql_path not in _registry:
        raise ValueError(f"No types found for SQL path: {sql_path}")
    
    sql_params_class, sql_row_class, _, _ = _registry[sql_path]
    
    # Get class from current module
    import sys
    current_module = sys.modules[__name__]
    sql_params_type = getattr(current_module, sql_params_class)
    sql_row_type = getattr(current_module, sql_row_class)
    
    return sql_params_type, sql_row_type


def get_api_types(sql_path: str) -> tuple[Type[BaseModel], Type[BaseModel]]:
    """Get API request and response types for a SQL file path.
    
    Args:
        sql_path: SQL file path (e.g., "app/sql/v4/agents/get_agent_new_complete.sql")
    
    Returns:
        Tuple of (ApiRequestType, ApiResponseType)
    
    Raises:
        ValueError: If no types are found for the SQL file path
    """
    if sql_path not in _registry:
        raise ValueError(f"No types found for SQL path: {sql_path}")
    
    _, _, api_request_class, api_response_class = _registry[sql_path]
    
    # Get class from current module
    import sys
    current_module = sys.modules[__name__]
    api_request_type = getattr(current_module, api_request_class)
    api_response_type = getattr(current_module, api_response_class)
    
    return api_request_type, api_response_type


# Overload declarations for load_sql_query() - provides strong type hints
# Auto-generated by sql-compile. Do not edit manually.
if TYPE_CHECKING:
    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/api/agents/test_create_test_profile_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/api/agents/test_create_test_prompt_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/api/agents/test_get_agent_department_link_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/api/agents/test_get_agent_department_links_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/api/agents/test_get_agent_prompt_link_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/api/agents/test_get_first_department_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/api/agents/test_get_first_model_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/helpers/test_get_cs_dept_id_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/helpers/test_get_or_create_test_department_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/helpers/test_get_or_create_test_model_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/helpers/test_get_or_create_test_profile_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: Literal["tests/sql/v4/integration/helpers/test_get_superadmin_alias_v4_complete.sql"]
    ) -> SqlString: ...

    @overload
    def load_sql_query(
        file_path: str
    ) -> SqlString: ...


def load_sql_query(
    file_path: str,
) -> SqlString:
    """Load SQL file content and return as string.

    Returns the SQL query string from the specified file path.
    Uses Literal overloads to provide strong type hints for file paths.

    Args:
        file_path: Relative path from server root (e.g., "tests/sql/integration/infra/activity/insert_test_profile.sql")

    Returns:
        SQL string with parameter placeholders ($1, $2, etc.)

    Example:
        ```python
        sql_query = load_sql_query("tests/sql/integration/infra/activity/insert_test_profile.sql")
        # sql_query is typed as SqlString
        ```
    """
    # Import here to avoid circular imports
    from utils.sql_helper import load_sql

    return load_sql(file_path)