-- Foreign keys: agent_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: agent_drafts_entry agent_drafts_entry_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_entry
    ADD CONSTRAINT agent_drafts_entry_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups_entry(id);


--
