-- Foreign keys: file_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: file_uploads_entry file_uploads_entry_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_uploads_entry
    ADD CONSTRAINT file_uploads_entry_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.files_entry(id);


--

-- Name: file_uploads_entry file_uploads_entry_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_uploads_entry
    ADD CONSTRAINT file_uploads_entry_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads_entry(id);


--
