-- Foreign keys: reports_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: reports_entry reports_entry_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports_entry
    ADD CONSTRAINT reports_entry_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id);


--

-- Name: reports_entry reports_entry_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports_entry
    ADD CONSTRAINT reports_entry_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads_entry(id);


--
