-- Foreign keys: resolves_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: resolves_entry resolves_entry_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resolves_entry
    ADD CONSTRAINT resolves_entry_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id);


--

-- Name: resolves_entry resolves_entry_problem_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resolves_entry
    ADD CONSTRAINT resolves_entry_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.problems_entry(id) ON DELETE CASCADE;


--
