-- Foreign keys: text_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: text_completion_entry text_completion_entry_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.text_completion_entry
    ADD CONSTRAINT text_completion_entry_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions_entry(id);


--

-- Name: text_completion_entry text_completion_entry_text_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.text_completion_entry
    ADD CONSTRAINT text_completion_entry_text_id_fkey FOREIGN KEY (text_id) REFERENCES public.texts_entry(id) ON DELETE CASCADE;


--

-- Name: text_uploads_entry text_uploads_entry_text_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.text_uploads_entry
    ADD CONSTRAINT text_uploads_entry_text_id_fkey FOREIGN KEY (text_id) REFERENCES public.texts_entry(id);


--

-- Name: text_uploads_entry text_uploads_entry_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.text_uploads_entry
    ADD CONSTRAINT text_uploads_entry_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads_entry(id);


--
