-- Foreign keys: video_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: video_uploads_entry video_uploads_entry_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.video_uploads_entry
    ADD CONSTRAINT video_uploads_entry_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads_entry(id);


--

-- Name: video_uploads_entry video_uploads_entry_video_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.video_uploads_entry
    ADD CONSTRAINT video_uploads_entry_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos_entry(id);


--
