#!/usr/bin/env bash
set -euo pipefail

# Script to generate consolidated test schema SQL file
# Uses schema.sql exported from the live database (database-first approach)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DB_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$DB_ROOT/.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/server/tests/test-schema.sql"

# Check for schema.sql in database/ or root directory
SCHEMA_FILE=""
if [[ -f "$DB_ROOT/schema.sql" ]]; then
    SCHEMA_FILE="$DB_ROOT/schema.sql"
elif [[ -f "$ROOT_DIR/schema.sql" ]]; then
    SCHEMA_FILE="$ROOT_DIR/schema.sql"
else
    echo "❌ schema.sql not found in database/ or root directory"
    echo "💡 Run 'make export-db schema' first to generate it"
    exit 1
fi

echo "🔧 Generating test schema from $(basename $(dirname "$SCHEMA_FILE"))/schema.sql..."

# Create output file with header
cat > "$OUTPUT_FILE" << 'EOF'
-- ============================================================================
-- CONSOLIDATED TEST SCHEMA
-- Auto-generated from schema.sql (exported from live database)
-- DO NOT EDIT THIS FILE DIRECTLY - run 'make generate-test-schema' to regenerate
-- ============================================================================

EOF

# Copy schema.sql to test-schema.sql
cat "$SCHEMA_FILE" >> "$OUTPUT_FILE"

# Add footer
cat >> "$OUTPUT_FILE" << 'EOF'

-- ============================================================================
-- END OF CONSOLIDATED TEST SCHEMA
-- ============================================================================
EOF

echo "✅ Test schema generated: $(basename "$OUTPUT_FILE")"
echo "📍 Location: $OUTPUT_FILE"

# Show file size
FILE_SIZE=$(wc -l < "$OUTPUT_FILE" | xargs)
echo "📊 Lines: $FILE_SIZE"

