-- Indexes: auth_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: auth_item_keys_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_item_keys_calls_connection_call_id_idx ON public.auth_item_keys_calls_connection USING btree (call_id);


--

-- Name: auth_item_keys_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_item_keys_calls_connection_id_idx ON public.auth_item_keys_calls_connection USING btree (auth_item_keys_id);


--

-- Name: idx_auth_drafts_departments_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_drafts_departments_resource_id ON public.auth_drafts_departments_connection USING btree (departments_id);


--

-- Name: idx_auth_drafts_descriptions_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_drafts_descriptions_resource_id ON public.auth_drafts_descriptions_connection USING btree (descriptions_id);


--

-- Name: idx_auth_drafts_flags_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_drafts_flags_resource_id ON public.auth_drafts_flags_connection USING btree (flags_id);


--

-- Name: idx_auth_drafts_items_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_drafts_items_resource_id ON public.auth_drafts_items_connection USING btree (items_id);


--

-- Name: idx_auth_drafts_names_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_drafts_names_resource_id ON public.auth_drafts_names_connection USING btree (names_id);


--

-- Name: idx_auth_drafts_profiles_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_drafts_profiles_resource_id ON public.auth_drafts_profiles_connection USING btree (profiles_id);


--

-- Name: idx_auth_drafts_protocols_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_drafts_protocols_resource_id ON public.auth_drafts_protocols_connection USING btree (protocols_id);


--

-- Name: idx_auth_drafts_slugs_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_drafts_slugs_resource_id ON public.auth_drafts_slugs_connection USING btree (slugs_id);


--
