-- Indexes: colors_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: colors_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX colors_calls_connection_call_id_idx ON public.colors_calls_connection USING btree (call_id);


--

-- Name: colors_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX colors_calls_connection_id_idx ON public.colors_calls_connection USING btree (colors_id);


--
