-- Indexes: documents_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: documents_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX documents_calls_connection_call_id_idx ON public.documents_calls_connection USING btree (call_id);


--

-- Name: documents_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX documents_calls_connection_id_idx ON public.documents_calls_connection USING btree (documents_id);


--
