-- Indexes: file_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: file_files_connection_file_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX file_files_connection_file_id_idx ON public.file_files_connection USING btree (file_id);


--

-- Name: file_files_connection_files_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX file_files_connection_files_id_idx ON public.file_files_connection USING btree (files_id);


--
