-- Indexes: groups_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: groups_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX groups_calls_connection_call_id_idx ON public.groups_calls_connection USING btree (call_id);


--

-- Name: groups_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX groups_calls_connection_id_idx ON public.groups_calls_connection USING btree (groups_id);


--

-- Name: groups_groups_connection_group_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX groups_groups_connection_group_id_idx ON public.groups_groups_connection USING btree (group_id);


--

-- Name: groups_groups_connection_groups_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX groups_groups_connection_groups_id_idx ON public.groups_groups_connection USING btree (groups_id);


--
