-- Indexes: icons_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: icons_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX icons_calls_connection_call_id_idx ON public.icons_calls_connection USING btree (call_id);


--

-- Name: icons_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX icons_calls_connection_id_idx ON public.icons_calls_connection USING btree (icons_id);


--
