-- Indexes: invocation_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_benchmark_bundle_departments_conn_departments_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_bundle_departments_conn_departments_id ON public.invocation_departments_connection USING btree (departments_id);


--

-- Name: idx_benchmark_bundle_descriptions_descriptions_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_bundle_descriptions_descriptions_id ON public.invocation_descriptions_connection USING btree (descriptions_id);


--

-- Name: idx_benchmark_bundle_flags_flags_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_bundle_flags_flags_id ON public.invocation_flags_connection USING btree (flags_id);


--

-- Name: idx_benchmark_bundle_keys_keys_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_bundle_keys_keys_id ON public.invocation_keys_connection USING btree (keys_id);


--

-- Name: idx_benchmark_bundle_models_models_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_bundle_models_models_id ON public.invocation_models_connection USING btree (models_id);


--

-- Name: idx_benchmark_bundle_names_names_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_bundle_names_names_id ON public.invocation_names_connection USING btree (names_id);


--

-- Name: idx_benchmark_bundle_reasoning_levels_reasoning_levels_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_bundle_reasoning_levels_reasoning_levels_id ON public.invocation_reasoning_levels_connection USING btree (reasoning_levels_id);


--

-- Name: idx_benchmark_bundle_temperature_levels_temperature_levels_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_bundle_temperature_levels_temperature_levels_id ON public.invocation_temperature_levels_connection USING btree (temperature_levels_id);


--

-- Name: idx_benchmark_bundle_voices_voices_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_bundle_voices_voices_id ON public.invocation_voices_connection USING btree (voices_id);


--

-- Name: idx_invocation_drafts_profiles_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invocation_drafts_profiles_resource_id ON public.invocation_drafts_profiles_connection USING btree (profiles_id);


--

-- Name: idx_invocation_modalities_modalities_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invocation_modalities_modalities_id ON public.invocation_modalities_connection USING btree (modalities_id);


--

-- Name: idx_invocation_qualities_qualities_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invocation_qualities_qualities_id ON public.invocation_qualities_connection USING btree (qualities_id);


--

-- Name: idx_suite_drafts_departments_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_suite_drafts_departments_resource_id ON public.invocation_drafts_departments_connection USING btree (departments_id);


--

-- Name: idx_suite_drafts_descriptions_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_suite_drafts_descriptions_resource_id ON public.invocation_drafts_descriptions_connection USING btree (descriptions_id);


--

-- Name: idx_suite_drafts_flags_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_suite_drafts_flags_resource_id ON public.invocation_drafts_flags_connection USING btree (flags_id);


--

-- Name: idx_suite_drafts_keys_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_suite_drafts_keys_resource_id ON public.invocation_drafts_keys_connection USING btree (keys_id);


--

-- Name: idx_suite_drafts_names_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_suite_drafts_names_resource_id ON public.invocation_drafts_names_connection USING btree (names_id);


--

-- Name: idx_suite_drafts_reasoning_levels_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_suite_drafts_reasoning_levels_resource_id ON public.invocation_drafts_reasoning_levels_connection USING btree (reasoning_levels_id);


--

-- Name: idx_suite_drafts_temperature_levels_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_suite_drafts_temperature_levels_resource_id ON public.invocation_drafts_temperature_levels_connection USING btree (temperature_levels_id);


--

-- Name: idx_suite_drafts_voices_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_suite_drafts_voices_resource_id ON public.invocation_drafts_voices_connection USING btree (voices_id);


--
