-- Indexes: items_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: items_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX items_calls_connection_call_id_idx ON public.items_calls_connection USING btree (call_id);


--

-- Name: items_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX items_calls_connection_id_idx ON public.items_calls_connection USING btree (items_id);


--
