-- Indexes: names_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: names_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX names_calls_connection_call_id_idx ON public.names_calls_connection USING btree (call_id);


--

-- Name: names_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX names_calls_connection_id_idx ON public.names_calls_connection USING btree (names_id);


--
