-- Indexes: persona_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_persona_drafts_colors_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_colors_resource_id ON public.persona_drafts_colors_connection USING btree (colors_id);


--

-- Name: idx_persona_drafts_departments_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_departments_resource_id ON public.persona_drafts_departments_connection USING btree (departments_id);


--

-- Name: idx_persona_drafts_descriptions_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_descriptions_resource_id ON public.persona_drafts_descriptions_connection USING btree (descriptions_id);


--

-- Name: idx_persona_drafts_examples_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_examples_resource_id ON public.persona_drafts_examples_connection USING btree (examples_id);


--

-- Name: idx_persona_drafts_flags_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_flags_resource_id ON public.persona_drafts_flags_connection USING btree (flags_id);


--

-- Name: idx_persona_drafts_icons_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_icons_resource_id ON public.persona_drafts_icons_connection USING btree (icons_id);


--

-- Name: idx_persona_drafts_instructions_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_instructions_resource_id ON public.persona_drafts_instructions_connection USING btree (instructions_id);


--

-- Name: idx_persona_drafts_names_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_names_resource_id ON public.persona_drafts_names_connection USING btree (names_id);


--

-- Name: idx_persona_drafts_parameter_fields_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_parameter_fields_resource_id ON public.persona_drafts_parameter_fields_connection USING btree (parameter_fields_id);


--

-- Name: idx_persona_drafts_profiles_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_profiles_resource_id ON public.persona_drafts_profiles_connection USING btree (profiles_id);


--

-- Name: idx_persona_drafts_voices_voices_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_drafts_voices_voices_id ON public.persona_drafts_voices_connection USING btree (voices_id);


--
