-- Indexes: pricing_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: pricing_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_calls_connection_call_id_idx ON public.pricing_calls_connection USING btree (call_id);


--

-- Name: pricing_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_calls_connection_id_idx ON public.pricing_calls_connection USING btree (pricing_id);


--
