-- Indexes: responses_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: responses_options_connection_option_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX responses_options_connection_option_id_idx ON public.responses_options_connection USING btree (option_id);


--

-- Name: responses_options_connection_responses_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX responses_options_connection_responses_id_idx ON public.responses_options_connection USING btree (responses_id);


--

-- Name: responses_questions_connection_question_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX responses_questions_connection_question_id_idx ON public.responses_questions_connection USING btree (question_id);


--

-- Name: responses_questions_connection_responses_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX responses_questions_connection_responses_id_idx ON public.responses_questions_connection USING btree (responses_id);


--
