-- Indexes: simulations_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: simulations_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX simulations_calls_connection_call_id_idx ON public.simulations_calls_connection USING btree (call_id);


--

-- Name: simulations_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX simulations_calls_connection_id_idx ON public.simulations_calls_connection USING btree (simulations_id);


--
