-- Indexes: tool_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_tool_drafts_arg_positions_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_arg_positions_resource_id ON public.tool_drafts_arg_positions_connection USING btree (arg_positions_id);


--

-- Name: idx_tool_drafts_args_outputs_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_args_outputs_resource_id ON public.tool_drafts_args_outputs_connection USING btree (args_outputs_id);


--

-- Name: idx_tool_drafts_args_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_args_resource_id ON public.tool_drafts_args_connection USING btree (args_id);


--

-- Name: idx_tool_drafts_departments_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_departments_resource_id ON public.tool_drafts_departments_connection USING btree (departments_id);


--

-- Name: idx_tool_drafts_descriptions_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_descriptions_resource_id ON public.tool_drafts_descriptions_connection USING btree (descriptions_id);


--

-- Name: idx_tool_drafts_entries_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_entries_resource_id ON public.tool_drafts_entries_connection USING btree (entries_id);


--

-- Name: idx_tool_drafts_flags_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_flags_resource_id ON public.tool_drafts_flags_connection USING btree (flags_id);


--

-- Name: idx_tool_drafts_names_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_names_resource_id ON public.tool_drafts_names_connection USING btree (names_id);


--

-- Name: idx_tool_drafts_profiles_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_profiles_resource_id ON public.tool_drafts_profiles_connection USING btree (profiles_id);


--

-- Name: idx_tool_drafts_resources_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_resources_resource_id ON public.tool_drafts_resources_connection USING btree (resources_id);


--

-- Name: idx_tool_drafts_tools_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tool_drafts_tools_resource_id ON public.tool_drafts_tools_connection USING btree (tools_id);


--
