-- Indexes: values_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: values_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX values_calls_connection_call_id_idx ON public.values_calls_connection USING btree (call_id);


--

-- Name: values_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX values_calls_connection_id_idx ON public.values_calls_connection USING btree (values_id);


--
