-- Indexes: videos_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: videos_calls_connection_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX videos_calls_connection_call_id_idx ON public.videos_calls_connection USING btree (call_id);


--

-- Name: videos_calls_connection_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX videos_calls_connection_id_idx ON public.videos_calls_connection USING btree (videos_id);


--

-- Name: videos_videos_connection_video_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX videos_videos_connection_video_id_idx ON public.videos_videos_connection USING btree (video_id);


--

-- Name: videos_videos_connection_videos_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX videos_videos_connection_videos_id_idx ON public.videos_videos_connection USING btree (videos_id);


--
