-- Tables: attempt_*_entrie (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_analysis_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_analysis_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_analyses_entry_id_not_null NOT NULL,
    grade_id uuid CONSTRAINT simulation_analyses_entry_grade_id_not_null NOT NULL,
    content text CONSTRAINT simulation_analyses_entry_content_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_analyses_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_analyses_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_analyses_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_analyses_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_analyses_entry_active_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_archive_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_archive_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_archives_entry_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_archives_entry_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_archives_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_archives_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_archives_entry_active_not_null NOT NULL,
    attempt_id uuid CONSTRAINT simulation_archives_entry_attempt_id_not_null NOT NULL,
    archived boolean CONSTRAINT simulation_archives_entry_archived_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_chat_bridge_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_chat_bridge_entry (
    attempt_id uuid CONSTRAINT attempt_chat_entry_attempt_id_not_null NOT NULL,
    attempt_chat_id uuid CONSTRAINT attempt_chat_entry_chat_resolved_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT attempt_chat_entry_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT attempt_chat_entry_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT attempt_chat_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT attempt_chat_entry_mcp_not_null NOT NULL,
    session_id uuid
);


--

-- Name: attempt_chat_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_chat_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT chat_resolved_entry_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT chat_resolved_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT chat_resolved_entry_updated_at_not_null NOT NULL,
    title text DEFAULT ''::text CONSTRAINT chat_resolved_entry_title_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT chat_resolved_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT chat_resolved_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT chat_resolved_entry_active_not_null NOT NULL,
    group_id uuid,
    chat_id uuid CONSTRAINT chat_resolved_entry_chat_id_not_null NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    time_limit integer,
    negative_time boolean DEFAULT false NOT NULL,
    audio_enabled boolean DEFAULT false NOT NULL,
    text_enabled boolean DEFAULT false NOT NULL,
    hints_enabled boolean DEFAULT false NOT NULL,
    copy_paste_allowed boolean DEFAULT false NOT NULL,
    show_images boolean DEFAULT false NOT NULL,
    show_objectives boolean DEFAULT false NOT NULL,
    show_problem_statement boolean DEFAULT false NOT NULL,
    analyses_enabled boolean DEFAULT false NOT NULL,
    improvements_enabled boolean DEFAULT false NOT NULL,
    replacements_enabled boolean DEFAULT false NOT NULL,
    strengths_enabled boolean DEFAULT false NOT NULL,
    use_custom boolean DEFAULT false NOT NULL,
    use_previous boolean DEFAULT false NOT NULL,
    problem_statement_enabled boolean DEFAULT false NOT NULL,
    objectives_enabled boolean DEFAULT false NOT NULL,
    video_enabled boolean DEFAULT false NOT NULL,
    images_enabled boolean DEFAULT false NOT NULL,
    questions_enabled boolean DEFAULT false NOT NULL,
    assistant_persona_ids uuid[] DEFAULT ARRAY[]::uuid[],
    call_id uuid
);


--

-- Name: attempt_completion_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_completion_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_completions_entry_id_not_null NOT NULL,
    chat_id uuid CONSTRAINT simulation_completions_entry_chat_id_not_null NOT NULL,
    end_reason text DEFAULT ''::text CONSTRAINT simulation_completions_entry_end_reason_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_completions_entry_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_completions_entry_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_completions_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_completions_entry_mcp_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_content_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_content_entry (
    message_id uuid CONSTRAINT simulation_contents_entry_simulation_message_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_contents_entry_created_at_not_null1 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_contents_entry_updated_at_not_null1 NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_contents_entry_id_not_null NOT NULL,
    content text CONSTRAINT simulation_contents_entry_content_not_null NOT NULL,
    call_id uuid,
    generated boolean DEFAULT false CONSTRAINT simulation_contents_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_contents_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_contents_entry_active_not_null NOT NULL,
    persona_id uuid
);


--

-- Name: attempt_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    infinite_mode boolean DEFAULT false NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    num_chats integer DEFAULT 1 NOT NULL,
    user_persona_id uuid,
    call_id uuid,
    name text,
    description text,
    practice boolean DEFAULT false NOT NULL
);


--

-- Name: attempt_feedback_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_feedback_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_feedbacks_entry_id_not_null NOT NULL,
    grade_id uuid CONSTRAINT simulation_feedbacks_entry_grade_id_not_null NOT NULL,
    total integer CONSTRAINT simulation_feedbacks_entry_total_not_null NOT NULL,
    feedback text DEFAULT 'No feedback provided'::text CONSTRAINT simulation_feedbacks_entry_feedback_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_feedbacks_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_feedbacks_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_feedbacks_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_feedbacks_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_feedbacks_entry_active_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_grade_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_grade_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_grades_entry_id_not_null NOT NULL,
    chat_id uuid CONSTRAINT simulation_grades_entry_chat_id_not_null NOT NULL,
    run_id uuid,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_grades_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_grades_entry_updated_at_not_null NOT NULL,
    passed boolean CONSTRAINT simulation_grades_entry_passed_not_null NOT NULL,
    score integer CONSTRAINT simulation_grades_entry_score_not_null NOT NULL,
    time_taken integer,
    generated boolean DEFAULT false CONSTRAINT simulation_grades_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_grades_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_grades_entry_active_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_highlight_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_highlight_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_highlights_entry_id_not_null NOT NULL,
    strength_id uuid CONSTRAINT simulation_highlights_entry_strength_id_not_null NOT NULL,
    section text CONSTRAINT simulation_highlights_entry_section_not_null NOT NULL,
    idx integer DEFAULT 0 CONSTRAINT simulation_highlights_entry_idx_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_highlights_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_highlights_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_highlights_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_highlights_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_highlights_entry_active_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_message_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_message_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    chat_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    message_id uuid,
    call_id uuid
);


--

-- Name: attempt_strength_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_strength_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_strengths_entry_id_not_null NOT NULL,
    grade_id uuid CONSTRAINT simulation_strengths_entry_grade_id_not_null NOT NULL,
    message_id uuid CONSTRAINT simulation_strengths_entry_message_id_not_null NOT NULL,
    name text CONSTRAINT simulation_strengths_entry_name_not_null NOT NULL,
    description text DEFAULT 'No description provided'::text CONSTRAINT simulation_strengths_entry_description_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_strengths_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_strengths_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_strengths_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_strengths_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_strengths_entry_active_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_hint_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_hint_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_hints_entry_id_not_null NOT NULL,
    message_id uuid CONSTRAINT simulation_hints_entry_message_id_not_null NOT NULL,
    hint text CONSTRAINT simulation_hints_entry_hint_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_hints_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_hints_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_hints_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_hints_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_hints_entry_active_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_home_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_home_entry (
    attempt_id uuid NOT NULL,
    home_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    session_id uuid
);


--

-- Name: attempt_improvement_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_improvement_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_improvements_entry_id_not_null NOT NULL,
    grade_id uuid CONSTRAINT simulation_improvements_entry_grade_id_not_null NOT NULL,
    message_id uuid CONSTRAINT simulation_improvements_entry_message_id_not_null NOT NULL,
    name text CONSTRAINT simulation_improvements_entry_name_not_null NOT NULL,
    description text DEFAULT 'No description provided'::text CONSTRAINT simulation_improvements_entry_description_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_improvements_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_improvements_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_improvements_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_improvements_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_improvements_entry_active_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_message_tree_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_message_tree_entry (
    parent_id uuid CONSTRAINT simulation_message_tree_entry_parent_id_not_null NOT NULL,
    child_id uuid CONSTRAINT simulation_message_tree_entry_child_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_message_tree_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_message_tree_entry_updated_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_message_tree_entry_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_message_tree_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_message_tree_entry_mcp_not_null NOT NULL,
    session_id uuid
);


--

-- Name: attempt_practice_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_practice_entry (
    attempt_id uuid NOT NULL,
    practice_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    session_id uuid
);


--

-- Name: attempt_replacement_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_replacement_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_replacements_entry_id_not_null NOT NULL,
    improvement_id uuid CONSTRAINT simulation_replacements_entry_improvement_id_not_null NOT NULL,
    section text CONSTRAINT simulation_replacements_entry_section_not_null NOT NULL,
    replace text CONSTRAINT simulation_replacements_entry_replace_not_null NOT NULL,
    idx integer DEFAULT 0 CONSTRAINT simulation_replacements_entry_idx_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_replacements_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_replacements_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_replacements_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_replacements_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_replacements_entry_active_not_null NOT NULL,
    call_id uuid
);


--
