-- Table definitions + constraints: attempt_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_analysis_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_analysis_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_analyses_entry_id_not_null NOT NULL,
    grade_id uuid CONSTRAINT simulation_analyses_entry_grade_id_not_null NOT NULL,
    content text CONSTRAINT simulation_analyses_entry_content_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_analyses_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_analyses_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_analyses_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_analyses_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_analyses_entry_active_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_archive_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_archive_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_archives_entry_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_archives_entry_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_archives_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_archives_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_archives_entry_active_not_null NOT NULL,
    attempt_id uuid CONSTRAINT simulation_archives_entry_attempt_id_not_null NOT NULL,
    archived boolean CONSTRAINT simulation_archives_entry_archived_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_chat_bridge_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_chat_bridge_entry (
    attempt_id uuid CONSTRAINT attempt_chat_entry_attempt_id_not_null NOT NULL,
    attempt_chat_id uuid CONSTRAINT attempt_chat_entry_chat_resolved_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT attempt_chat_entry_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT attempt_chat_entry_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT attempt_chat_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT attempt_chat_entry_mcp_not_null NOT NULL,
    session_id uuid NOT NULL
);


--

-- Name: attempt_chat_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_chat_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT chat_resolved_entry_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT chat_resolved_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT chat_resolved_entry_updated_at_not_null NOT NULL,
    title text DEFAULT ''::text CONSTRAINT chat_resolved_entry_title_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT chat_resolved_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT chat_resolved_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT chat_resolved_entry_active_not_null NOT NULL,
    group_id uuid NOT NULL,
    chat_id uuid CONSTRAINT chat_resolved_entry_chat_id_not_null NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    time_limit integer,
    negative_time boolean DEFAULT false NOT NULL,
    audio_enabled boolean DEFAULT false NOT NULL,
    text_enabled boolean DEFAULT false NOT NULL,
    hints_enabled boolean DEFAULT false NOT NULL,
    copy_paste_allowed boolean DEFAULT false NOT NULL,
    show_images boolean DEFAULT false NOT NULL,
    show_objectives boolean DEFAULT false NOT NULL,
    show_problem_statement boolean DEFAULT false NOT NULL,
    analyses_enabled boolean DEFAULT false NOT NULL,
    improvements_enabled boolean DEFAULT false NOT NULL,
    replacements_enabled boolean DEFAULT false NOT NULL,
    strengths_enabled boolean DEFAULT false NOT NULL,
    use_custom boolean DEFAULT false NOT NULL,
    use_previous boolean DEFAULT false NOT NULL,
    problem_statement_enabled boolean DEFAULT false NOT NULL,
    objectives_enabled boolean DEFAULT false NOT NULL,
    video_enabled boolean DEFAULT false NOT NULL,
    images_enabled boolean DEFAULT false NOT NULL,
    questions_enabled boolean DEFAULT false NOT NULL,
    assistant_persona_ids uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_completion_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_completion_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_completions_entry_id_not_null NOT NULL,
    chat_id uuid CONSTRAINT simulation_completions_entry_chat_id_not_null NOT NULL,
    end_reason text DEFAULT ''::text CONSTRAINT simulation_completions_entry_end_reason_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_completions_entry_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_completions_entry_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_completions_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_completions_entry_mcp_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    infinite_mode boolean DEFAULT false NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    num_chats integer DEFAULT 1 NOT NULL,
    user_persona_id uuid NOT NULL,
    call_id uuid NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    practice boolean DEFAULT false NOT NULL
);


--

-- Name: attempt_grade_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_grade_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_grades_entry_id_not_null NOT NULL,
    chat_id uuid CONSTRAINT simulation_grades_entry_chat_id_not_null NOT NULL,
    run_id uuid,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_grades_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_grades_entry_updated_at_not_null NOT NULL,
    passed boolean CONSTRAINT simulation_grades_entry_passed_not_null NOT NULL,
    score integer CONSTRAINT simulation_grades_entry_score_not_null NOT NULL,
    time_taken integer,
    generated boolean DEFAULT false CONSTRAINT simulation_grades_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_grades_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_grades_entry_active_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_home_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_home_entry (
    attempt_id uuid NOT NULL,
    home_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    session_id uuid NOT NULL
);


--

-- Name: attempt_practice_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_practice_entry (
    attempt_id uuid NOT NULL,
    practice_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    session_id uuid NOT NULL
);


--

-- Name: attempt_content_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_content_entry (
    message_id uuid CONSTRAINT simulation_contents_entry_simulation_message_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_contents_entry_created_at_not_null1 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_contents_entry_updated_at_not_null1 NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_contents_entry_id_not_null NOT NULL,
    content text CONSTRAINT simulation_contents_entry_content_not_null NOT NULL,
    call_id uuid NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_contents_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_contents_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_contents_entry_active_not_null NOT NULL,
    persona_id uuid
);


--

-- Name: attempt_message_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_message_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    chat_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    message_id uuid NOT NULL,
    call_id uuid NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: attempt_conversation_completions_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_conversation_completions_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT conversations_completions_entry_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT conversations_completions_entry_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT conversations_completions_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT conversations_completions_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT conversations_completions_entry_active_not_null NOT NULL,
    conversation_id uuid CONSTRAINT conversations_completions_entry_conversation_id_not_null NOT NULL,
    end_reason text DEFAULT ''::text CONSTRAINT conversations_completions_entry_end_reason_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_conversations_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_conversations_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT conversations_entry_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT conversations_entry_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT conversations_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT conversations_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT conversations_entry_active_not_null NOT NULL,
    chat_id uuid CONSTRAINT conversations_entry_chat_id_not_null NOT NULL,
    run_id uuid,
    call_id uuid
);


--

-- Name: attempt_feedback_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_feedback_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_feedbacks_entry_id_not_null NOT NULL,
    grade_id uuid CONSTRAINT simulation_feedbacks_entry_grade_id_not_null NOT NULL,
    total integer CONSTRAINT simulation_feedbacks_entry_total_not_null NOT NULL,
    feedback text DEFAULT 'No feedback provided'::text CONSTRAINT simulation_feedbacks_entry_feedback_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_feedbacks_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_feedbacks_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_feedbacks_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_feedbacks_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_feedbacks_entry_active_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_highlight_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_highlight_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_highlights_entry_id_not_null NOT NULL,
    strength_id uuid CONSTRAINT simulation_highlights_entry_strength_id_not_null NOT NULL,
    section text CONSTRAINT simulation_highlights_entry_section_not_null NOT NULL,
    idx integer DEFAULT 0 CONSTRAINT simulation_highlights_entry_idx_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_highlights_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_highlights_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_highlights_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_highlights_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_highlights_entry_active_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_strength_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_strength_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_strengths_entry_id_not_null NOT NULL,
    grade_id uuid CONSTRAINT simulation_strengths_entry_grade_id_not_null NOT NULL,
    message_id uuid CONSTRAINT simulation_strengths_entry_message_id_not_null NOT NULL,
    name text CONSTRAINT simulation_strengths_entry_name_not_null NOT NULL,
    description text DEFAULT 'No description provided'::text CONSTRAINT simulation_strengths_entry_description_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_strengths_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_strengths_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_strengths_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_strengths_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_strengths_entry_active_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_hint_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_hint_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_hints_entry_id_not_null NOT NULL,
    message_id uuid CONSTRAINT simulation_hints_entry_message_id_not_null NOT NULL,
    hint text CONSTRAINT simulation_hints_entry_hint_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_hints_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_hints_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_hints_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_hints_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_hints_entry_active_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_improvement_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_improvement_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_improvements_entry_id_not_null NOT NULL,
    grade_id uuid CONSTRAINT simulation_improvements_entry_grade_id_not_null NOT NULL,
    message_id uuid CONSTRAINT simulation_improvements_entry_message_id_not_null NOT NULL,
    name text CONSTRAINT simulation_improvements_entry_name_not_null NOT NULL,
    description text DEFAULT 'No description provided'::text CONSTRAINT simulation_improvements_entry_description_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_improvements_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_improvements_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_improvements_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_improvements_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_improvements_entry_active_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_message_tree_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_message_tree_entry (
    parent_id uuid CONSTRAINT simulation_message_tree_entry_parent_id_not_null NOT NULL,
    child_id uuid CONSTRAINT simulation_message_tree_entry_child_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_message_tree_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_message_tree_entry_updated_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_message_tree_entry_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_message_tree_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_message_tree_entry_mcp_not_null NOT NULL,
    session_id uuid NOT NULL
);


--

-- Name: attempt_mutes_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_mutes_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT mutes_entry_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT mutes_entry_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT mutes_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT mutes_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT mutes_entry_active_not_null NOT NULL,
    conversation_id uuid CONSTRAINT mutes_entry_conversation_id_not_null NOT NULL,
    muted boolean CONSTRAINT mutes_entry_muted_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_replacement_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_replacement_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT simulation_replacements_entry_id_not_null NOT NULL,
    improvement_id uuid CONSTRAINT simulation_replacements_entry_improvement_id_not_null NOT NULL,
    section text CONSTRAINT simulation_replacements_entry_section_not_null NOT NULL,
    replace text CONSTRAINT simulation_replacements_entry_replace_not_null NOT NULL,
    idx integer DEFAULT 0 CONSTRAINT simulation_replacements_entry_idx_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_replacements_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT simulation_replacements_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT simulation_replacements_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT simulation_replacements_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT simulation_replacements_entry_active_not_null NOT NULL,
    call_id uuid NOT NULL
);


--

-- Name: attempt_responses_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attempt_responses_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT responses_entry_id_not_null NOT NULL,
    chat_id uuid CONSTRAINT responses_entry_chat_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT responses_entry_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT responses_entry_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT responses_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT responses_entry_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT responses_entry_active_not_null NOT NULL,
    call_id uuid
);


--

-- Name: attempt_chat_bridge_entry attempt_chat_bridge_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_chat_bridge_entry
    ADD CONSTRAINT attempt_chat_bridge_entry_pkey PRIMARY KEY (attempt_id, attempt_chat_id);


--

-- Name: attempt_chat_entry attempt_chat_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_chat_entry
    ADD CONSTRAINT attempt_chat_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_conversation_completions_entry attempt_conversation_completions_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_conversation_completions_entry
    ADD CONSTRAINT attempt_conversation_completions_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_conversations_entry attempt_conversations_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_conversations_entry
    ADD CONSTRAINT attempt_conversations_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_entry attempt_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_entry
    ADD CONSTRAINT attempt_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_home_entry attempt_home_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_home_entry
    ADD CONSTRAINT attempt_home_entry_pkey PRIMARY KEY (attempt_id, home_id);


--

-- Name: attempt_message_entry attempt_message_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_message_entry
    ADD CONSTRAINT attempt_message_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_mutes_entry attempt_mutes_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_mutes_entry
    ADD CONSTRAINT attempt_mutes_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_practice_entry attempt_practice_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_practice_entry
    ADD CONSTRAINT attempt_practice_entry_pkey PRIMARY KEY (attempt_id, practice_id);


--

-- Name: attempt_responses_entry attempt_responses_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_responses_entry
    ADD CONSTRAINT attempt_responses_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_analysis_entry simulation_analyses_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_analysis_entry
    ADD CONSTRAINT simulation_analyses_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_archive_entry simulation_archives_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_archive_entry
    ADD CONSTRAINT simulation_archives_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_completion_entry simulation_completions_entry_chat_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_completion_entry
    ADD CONSTRAINT simulation_completions_entry_chat_unique UNIQUE (chat_id);


--

-- Name: attempt_completion_entry simulation_completions_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_completion_entry
    ADD CONSTRAINT simulation_completions_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_content_entry simulation_contents_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_content_entry
    ADD CONSTRAINT simulation_contents_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_feedback_entry simulation_feedbacks_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_feedback_entry
    ADD CONSTRAINT simulation_feedbacks_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_grade_entry simulation_grades_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_grade_entry
    ADD CONSTRAINT simulation_grades_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_highlight_entry simulation_highlights_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_highlight_entry
    ADD CONSTRAINT simulation_highlights_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_hint_entry simulation_hints_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_hint_entry
    ADD CONSTRAINT simulation_hints_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_improvement_entry simulation_improvements_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_improvement_entry
    ADD CONSTRAINT simulation_improvements_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_message_tree_entry simulation_message_tree_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_message_tree_entry
    ADD CONSTRAINT simulation_message_tree_entry_pkey PRIMARY KEY (parent_id, child_id);


--

-- Name: attempt_replacement_entry simulation_replacements_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_replacement_entry
    ADD CONSTRAINT simulation_replacements_entry_pkey PRIMARY KEY (id);


--

-- Name: attempt_strength_entry simulation_strengths_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attempt_strength_entry
    ADD CONSTRAINT simulation_strengths_entry_pkey PRIMARY KEY (id);


--
