-- Tables: images_*_entrie (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: images_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    message_id uuid,
    session_id uuid
);


--
