-- Table definitions + constraints: message_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: message_uploads_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_uploads_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    message_id uuid NOT NULL,
    upload_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: message_uploads_entry message_uploads_entry_message_id_upload_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_uploads_entry
    ADD CONSTRAINT message_uploads_entry_message_id_upload_id_key UNIQUE (message_id, upload_id);


--

-- Name: message_uploads_entry message_uploads_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_uploads_entry
    ADD CONSTRAINT message_uploads_entry_pkey PRIMARY KEY (id);


--
