-- Table definitions + constraints: metrics_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: metrics_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metrics_entry (
    ts timestamp with time zone CONSTRAINT app_metrics_ts_not_null NOT NULL,
    requests_total bigint CONSTRAINT app_metrics_requests_total_not_null NOT NULL,
    errors_total bigint CONSTRAINT app_metrics_errors_total_not_null NOT NULL,
    avg_latency_ms double precision CONSTRAINT app_metrics_avg_latency_ms_not_null NOT NULL,
    cpu_percent double precision CONSTRAINT app_metrics_cpu_percent_not_null NOT NULL,
    memory_bytes bigint CONSTRAINT app_metrics_memory_bytes_not_null NOT NULL,
    session_id uuid
);


--

-- Name: metrics_entry metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metrics_entry
    ADD CONSTRAINT metrics_pkey PRIMARY KEY (ts);


--
