-- Table definitions + constraints: responses_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: responses_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.responses_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    chat_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    call_id uuid
);


--

-- Name: responses_entry responses_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.responses_entry
    ADD CONSTRAINT responses_entry_pkey PRIMARY KEY (id);


--
