-- Table definitions + constraints: scenario_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: scenario_drafts_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scenario_drafts_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    group_id uuid,
    session_id uuid
);


--

-- Name: scenario_drafts_entry scenario_drafts_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_entry
    ADD CONSTRAINT scenario_drafts_entry_pkey PRIMARY KEY (id);


--
