-- Tables: sessions_*_entrie (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: sessions_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    profile_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    session_id uuid
);


--
