-- Table definitions + constraints: sessions_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: sessions_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    generated boolean DEFAULT false NOT NULL
);


--

-- Name: sessions_entry sessions_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions_entry
    ADD CONSTRAINT sessions_entry_pkey PRIMARY KEY (id);


--
