-- Tables: video_*_entrie (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: video_uploads_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.video_uploads_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    video_id uuid NOT NULL,
    upload_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--
