"""Flag resource seeds.

46 rows of feature flags and toggles used across different artifact types.
Flags control behaviors like active state, audio/text/video modes, rubric types,
and various scenario configuration options.
"""

from uuid import UUID

flags = [
    dict(
        id=UUID("019b995a-86ef-71e9-ad2c-6c2040afdffe"),
        name="active",
        description="Active flag",
        type="active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-78fc-adec-fc4db3a87c0d"),
        name="guest_login_enabled",
        description="Guest login enabled",
        type="guest_login_enabled",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-78e3-8811-f5d0cfd31e3c"),
        name="Practice",
        description="Practice flag",
        type="practice",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-7800-b93b-7897b07eca47"),
        name="Video",
        description="Video enabled",
        type="video_enabled",
        icon="Video",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-7830-9317-80d8d52b1bb2"),
        name="Problem Statement",
        description="Problem statement enabled",
        type="problem_statement_enabled",
        icon="FileText",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-77a3-a2a6-e6b760a9fcfe"),
        name="Objectives",
        description="Objectives enabled",
        type="objectives_enabled",
        icon="Target",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-781a-8ecb-8c0a6cfab122"),
        name="Questions",
        description="Questions enabled",
        type="questions_enabled",
        icon="MessageCircle",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-77dc-8ddc-2013a6e3194f"),
        name="Images",
        description="Images enabled",
        type="images_enabled",
        icon="Image",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-789f-94fa-2bd3e0707baa"),
        name="groups",
        description="Groups flag",
        type="groups",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-7879-89ed-3eadac3e0b84"),
        name="dynamic",
        description="Dynamic flag",
        type="dynamic",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019b995a-86ef-78bb-87a8-0de554b128bb"),
        name="template",
        description="Template flag",
        type="template",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019bd1c8-54ed-738a-a5fe-a914fd802fd4"),
        name="Audio Enabled",
        description="Audio enabled flag for simulation scenario",
        type="audio_enabled",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019bd1c8-54ed-750f-9ac8-e07932a65132"),
        name="Text Enabled",
        description="Text enabled flag for simulation scenario",
        type="text_enabled",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019bd1c8-54ed-74e9-a759-57eb8cb33e44"),
        name="Show Problem Statement",
        description="Show problem statement flag for simulation scenario",
        type="show_problem_statement",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019bd1c8-54ed-74d1-a0fa-87039f089a82"),
        name="Show Objectives",
        description="Show objectives flag for simulation scenario",
        type="show_objectives",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019bd1c8-54ed-74b4-b6ac-6e8cefab3f3e"),
        name="Show Images",
        description="Show images flag for simulation scenario",
        type="show_images",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019bd1c8-54ed-7494-b25c-2cb4b87bf1f9"),
        name="Hints Enabled",
        description="Hints enabled flag for simulation scenario",
        type="hints_enabled",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019bd1c8-54ed-746e-8763-c56ec022d976"),
        name="Copy Paste Allowed",
        description="Copy paste allowed flag for simulation scenario",
        type="copy_paste_allowed",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019bc71d-3ec0-7a2f-a0d2-fe56d855f570"),
        name="use_templates",
        description="Use templates flag for scenarios",
        type="use_templates",
        icon="Layout",
        value=True,
    ),
    dict(
        id=UUID("019bcc4d-d9c6-7a09-b99a-919d8f85cab1"),
        name="mcp",
        description="Enable or disable the use of the MCP server",
        type="mcp",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc3-7423-93ff-cc162b6984e9"),
        name="Active",
        description="Controls whether this scenario is published and available for simulations",
        type="scenario_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc4-7dd2-bcbd-93f1af18c233"),
        name="field_active",
        description="Controls whether this field is visible and editable in forms",
        type="field_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc4-7ef6-b18f-7a556d94b225"),
        name="model_active",
        description="Controls whether this AI model is available for selection by agents",
        type="model_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc5-7197-8f3e-c203790334de"),
        name="profile_active",
        description="Controls whether this user profile is active and can access the system",
        type="profile_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc5-7a16-a7ce-ed6bdc9a6e5d"),
        name="provider_active",
        description="Controls whether this AI provider is available for use",
        type="provider_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc5-7dbf-aefd-d61c2e8eebc1"),
        name="rubric_active",
        description="Controls whether this rubric is available for grading simulations",
        type="rubric_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc6-717e-9377-b63fc43ae0c6"),
        name="setting_active",
        description="Controls whether this setting is enabled and applied",
        type="setting_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc6-74fb-be11-ea6b522945bb"),
        name="tool_active",
        description="Controls whether this tool is available for use by AI agents",
        type="tool_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc4-71d1-90f5-23e5037bca21"),
        name="Active",
        description="Controls whether this cohort is active and can run simulations",
        type="cohort_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc3-7998-9dcf-a00d3d137da5"),
        name="Active",
        description="Controls whether this persona is available for use in scenarios",
        type="persona_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc6-73b3-ac0d-822d6864d660"),
        name="Active",
        description="Controls whether this simulation is active and can be started",
        type="simulation_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc4-76ac-80d3-c8ba7618bc7a"),
        name="agent_active",
        description="Controls whether this AI agent is available for use in simulations",
        type="agent_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc4-79b2-949c-9f99ea25d2c0"),
        name="auth_active",
        description="Controls whether this authentication method is enabled for login",
        type="auth_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc3-7c81-b7b6-de11e555da9d"),
        name="department_active",
        description="Controls whether this department is visible in the organization structure",
        type="department_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc4-7b69-96a1-6cf5422bba50"),
        name="document_active",
        description="Controls whether this document is available for reference in scenarios",
        type="document_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019be334-bfc4-7c9d-b9f9-19eb0fc849ec"),
        name="eval_active",
        description="Controls whether this evaluation configuration is active and can be used",
        type="eval_active",
        icon="Power",
        value=True,
    ),
    dict(
        id=UUID("019c2085-4b7a-7522-b58b-d472e9fef570"),
        name="simulation_rubric",
        description="Rubric used for simulation grading",
        type="simulation_rubric",
        icon="Flag",
        value=True,
    ),
    dict(
        id=UUID("019c2085-4b7c-7a5b-9b83-731223104ac7"),
        name="video_rubric",
        description="Rubric used for video grading",
        type="video_rubric",
        icon="Video",
        value=True,
    ),
    dict(
        id=UUID("8d0c8f56-2d24-43cc-8dfb-bbe94804f48c"),
        name="Infinite Mode",
        description="Enable infinite mode for unlimited attempts",
        type="infinite_mode",
        icon="infinity",
        value=True,
    ),
    dict(
        id=UUID("019c7307-6fd9-73ba-ab1f-03fb6719f8dd"),
        name="Strengths Enabled",
        description="Enable strengths feedback for scenarios",
        type="strengths_enabled",
        icon="ThumbsUp",
        value=True,
    ),
    dict(
        id=UUID("019c7307-6fd9-74b2-bc6a-ad91933ee830"),
        name="Use Custom",
        description="Allow custom configuration for scenarios",
        type="use_custom",
        icon="Settings",
        value=True,
    ),
    dict(
        id=UUID("019c7307-6fd8-7fa2-955b-b06b6c5f9896"),
        name="Analyses Enabled",
        description="Enable analysis feedback for scenarios",
        type="analyses_enabled",
        icon="BarChart",
        value=True,
    ),
    dict(
        id=UUID("019c7307-6fd9-7487-aaea-6d896596223b"),
        name="Use Previous",
        description="Use previous attempt context for scenarios",
        type="use_previous",
        icon="History",
        value=True,
    ),
    dict(
        id=UUID("019c7307-6fd9-7454-8f14-6f55256edc46"),
        name="Replacements Enabled",
        description="Enable replacement suggestions for scenarios",
        type="replacements_enabled",
        icon="RefreshCw",
        value=True,
    ),
    dict(
        id=UUID("019c7307-6fd9-7433-ad75-ac78d08e7ede"),
        name="Improvements Enabled",
        description="Enable improvements feedback for scenarios",
        type="improvements_enabled",
        icon="TrendingUp",
        value=True,
    ),
]
