-- Foreign keys: arg_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: arg_positions_resource arg_positions_resource_args_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.arg_positions_resource
    ADD CONSTRAINT arg_positions_resource_args_id_fkey FOREIGN KEY (args_id) REFERENCES public.args_resource(id) ON DELETE CASCADE;


--
