-- Foreign keys: args_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: args_outputs_resource args_outputs_resource_args_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.args_outputs_resource
    ADD CONSTRAINT args_outputs_resource_args_id_fkey FOREIGN KEY (args_id) REFERENCES public.args_resource(id) ON DELETE CASCADE;


--
