-- Foreign keys: auth_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: auth_item_keys_resource auth_item_keys_resource_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_item_keys_resource
    ADD CONSTRAINT auth_item_keys_resource_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items_resource(id);


--

-- Name: auth_item_keys_resource auth_keys_resource_auth_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_item_keys_resource
    ADD CONSTRAINT auth_keys_resource_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES public.auths_resource(id) ON DELETE CASCADE;


--

-- Name: auth_item_keys_resource auth_keys_resource_key_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_item_keys_resource
    ADD CONSTRAINT auth_keys_resource_key_id_fkey FOREIGN KEY (key_id) REFERENCES public.keys_resource(id) ON DELETE CASCADE;


--
