-- Foreign keys: models_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: models_resource models_resource_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.models_resource
    ADD CONSTRAINT models_resource_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers_resource(id) ON DELETE SET NULL;


--
