-- Foreign keys: model_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: model_flags_resource model_flags_resource_flag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_flags_resource
    ADD CONSTRAINT model_flags_resource_flag_id_fkey FOREIGN KEY (flag_id) REFERENCES public.flags_resource(id);


--

-- Name: model_flags_resource model_flags_resource_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_flags_resource
    ADD CONSTRAINT model_flags_resource_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models_resource(id);


--

-- Name: model_positions_resource model_positions_resource_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_positions_resource
    ADD CONSTRAINT model_positions_resource_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models_resource(id);


--

-- Name: model_rubrics_resource model_rubrics_resource_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_rubrics_resource
    ADD CONSTRAINT model_rubrics_resource_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models_resource(id);


--

-- Name: model_rubrics_resource model_rubrics_resource_rubric_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_rubrics_resource
    ADD CONSTRAINT model_rubrics_resource_rubric_id_fkey FOREIGN KEY (rubric_id) REFERENCES public.rubrics_resource(id);


--
