-- Foreign keys: options_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: options_resource options_resource_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.options_resource
    ADD CONSTRAINT options_resource_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions_resource(id) ON DELETE CASCADE;


--
