-- Foreign keys: reasoning_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: reasoning_levels_resource reasoning_levels_reasoning_level_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reasoning_levels_resource
    ADD CONSTRAINT reasoning_levels_reasoning_level_id_fkey FOREIGN KEY (reasoning_level_id) REFERENCES public.model_artifact(id);


--
