-- Foreign keys: roles_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: roles_resource roles_resource_color_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_resource
    ADD CONSTRAINT roles_resource_color_id_fkey FOREIGN KEY (color_id) REFERENCES public.colors_resource(id);


--

-- Name: roles_resource roles_resource_icon_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_resource
    ADD CONSTRAINT roles_resource_icon_id_fkey FOREIGN KEY (icon_id) REFERENCES public.icons_resource(id);


--
