-- MV indexes: activity_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: activity_mv_activity_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX activity_mv_activity_id_idx ON public.activity_mv USING btree (activity_id);


--
