-- MV indexes: attempt_mutes_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_mutes_mv_conversation_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attempt_mutes_mv_conversation_id_idx ON public.attempt_mutes_mv USING btree (conversation_id);


--

-- Name: attempt_mutes_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attempt_mutes_mv_id_idx ON public.attempt_mutes_mv USING btree (id);


--
