-- MV indexes: attempt_improvement_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_attempt_improvement_mv_improvement_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_attempt_improvement_mv_improvement_id ON public.attempt_improvement_mv USING btree (improvement_id);


--
