-- MV indexes: attempt_conversation_completions_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_attempt_conversation_completions_mv_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_attempt_conversation_completions_mv_id ON public.attempt_conversation_completions_mv USING btree (id);


--
