-- MV indexes: attempt_content_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_attempt_content_mv_content_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_attempt_content_mv_content_id ON public.attempt_content_mv USING btree (content_id);


--
