-- MV indexes: attempt_message_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_attempt_message_mv_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_attempt_message_mv_message_id ON public.attempt_message_mv USING btree (message_id);


--
