-- MV indexes: calls_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: calls_mv_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX calls_mv_call_id_idx ON public.calls_mv USING btree (call_id);


--
