-- MV indexes: chat_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_chat_drafts_mv_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_chat_drafts_mv_id ON public.chat_drafts_mv USING btree (id);


--
