-- MV indexes: chat_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_chat_mv_chat_entry_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_chat_mv_chat_entry_id ON public.chat_mv USING btree (chat_entry_id);


--
