-- MV indexes: image_completion_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_image_completion_mv_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_image_completion_mv_id ON public.image_completion_mv USING btree (id);


--
