-- MV indexes: invocation_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_invocation_mv_entry_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_invocation_mv_entry_id ON public.invocation_mv USING btree (invocation_entry_id);


--
