-- MV indexes: problems_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: problems_mv_problem_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX problems_mv_problem_id_idx ON public.problems_mv USING btree (problem_id);


--
