-- MV indexes: test_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_test_mv_test_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_test_mv_test_id ON public.test_mv USING btree (test_id);


--
