-- MV indexes: test_invocation_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_test_invocation_mv_invocation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_test_invocation_mv_invocation_id ON public.test_invocation_mv USING btree (invocation_id);


--
