-- MV indexes: test_invocation_bridge_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_test_invocation_bridge_mv_pk; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_test_invocation_bridge_mv_pk ON public.test_invocation_bridge_mv USING btree (test_invocation_id, invocation_id);


--
