-- MV indexes: uploads_completions_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: uploads_completions_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uploads_completions_mv_id_idx ON public.uploads_completions_mv USING btree (id);


--
