-- Indexes: agents_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: agents_resource_prompt_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agents_resource_prompt_id_idx ON public.agents_resource USING btree (prompt_id);


--

-- Name: idx_agents_resource_department_ids; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agents_resource_department_ids ON public.agents_resource USING gin (department_ids);


--

-- Name: idx_agents_resource_instruction_ids; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agents_resource_instruction_ids ON public.agents_resource USING gin (instruction_ids);


--

-- Name: idx_agents_resource_model_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agents_resource_model_id ON public.agents_resource USING btree (model_id);


--

-- Name: idx_agents_resource_prompt_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agents_resource_prompt_id ON public.agents_resource USING btree (prompt_id);


--

-- Name: idx_agents_resource_tool_ids; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agents_resource_tool_ids ON public.agents_resource USING gin (tool_ids);


--
