-- Indexes: args_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: args_outputs_resource_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX args_outputs_resource_active_idx ON public.args_outputs_resource USING btree (active);


--

-- Name: args_outputs_resource_args_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX args_outputs_resource_args_id_idx ON public.args_outputs_resource USING btree (args_id);


--

-- Name: args_outputs_resource_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX args_outputs_resource_created_at_idx ON public.args_outputs_resource USING btree (created_at);


--

-- Name: args_resource_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX args_resource_active_idx ON public.args_resource USING btree (active);


--

-- Name: args_resource_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX args_resource_created_at_idx ON public.args_resource USING btree (created_at);


--

-- Name: args_resource_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX args_resource_name_idx ON public.args_resource USING btree (name);


--

-- Name: idx_args_outputs_resource_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_args_outputs_resource_mcp ON public.args_outputs_resource USING btree (mcp);


--

-- Name: idx_args_resource_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_args_resource_mcp ON public.args_resource USING btree (mcp);


--
