-- Indexes: conditional_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_conditional_parameters_resource_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conditional_parameters_resource_generated ON public.conditional_parameters_resource USING btree (generated);


--

-- Name: idx_conditional_parameters_resource_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conditional_parameters_resource_mcp ON public.conditional_parameters_resource USING btree (mcp);


--

-- Name: idx_conditional_parameters_resource_parameter_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conditional_parameters_resource_parameter_id ON public.conditional_parameters_resource USING btree (parameter_id);


--
