-- Indexes: objectives_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_objectives_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_objectives_mcp ON public.objectives_resource USING btree (mcp);


--

-- Name: objectives_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX objectives_created_at_idx ON public.objectives_resource USING btree (created_at);


--
