-- Indexes: problem_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_problem_statements_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_problem_statements_mcp ON public.problem_statements_resource USING btree (mcp);


--

-- Name: problem_statements_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problem_statements_created_at_idx ON public.problem_statements_resource USING btree (created_at);


--

-- Name: problem_statements_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problem_statements_name_idx ON public.problem_statements_resource USING btree (name);


--
