-- Indexes: providers_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_providers_resource_department_ids; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_providers_resource_department_ids ON public.providers_resource USING gin (department_ids);


--
