-- Indexes: resources_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_resources_resource_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resources_resource_active ON public.resources_resource USING btree (active);


--

-- Name: idx_resources_resource_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resources_resource_generated ON public.resources_resource USING btree (generated);


--

-- Name: idx_resources_resource_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resources_resource_mcp ON public.resources_resource USING btree (mcp);


--

-- Name: idx_resources_resource_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resources_resource_resource ON public.resources_resource USING btree (resource);


--
