-- Indexes: rubrics_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_rubrics_resource_department_ids; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rubrics_resource_department_ids ON public.rubrics_resource USING gin (department_ids);


--

-- Name: idx_rubrics_resource_standard_group_ids; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rubrics_resource_standard_group_ids ON public.rubrics_resource USING gin (standard_group_ids);


--

-- Name: rubrics_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rubrics_id_idx ON public.rubrics_resource USING btree (id);


--
