-- Indexes: run_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_run_positions_resource_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_run_positions_resource_active ON public.run_positions_resource USING btree (active);


--

-- Name: idx_run_positions_resource_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_run_positions_resource_generated ON public.run_positions_resource USING btree (generated);


--

-- Name: idx_run_positions_resource_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_run_positions_resource_mcp ON public.run_positions_resource USING btree (mcp);


--

-- Name: idx_run_positions_resource_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_run_positions_resource_run_id ON public.run_positions_resource USING btree (runs_id);


--

-- Name: run_positions_resource_eval_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX run_positions_resource_eval_id_idx ON public.run_positions_resource USING btree (eval_id);


--

-- Name: run_rubrics_resource_rubric_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX run_rubrics_resource_rubric_id_idx ON public.run_rubrics_resource USING btree (rubric_id);


--

-- Name: run_rubrics_resource_runs_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX run_rubrics_resource_runs_id_idx ON public.run_rubrics_resource USING btree (runs_id);


--
