-- Indexes: simulation_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: simulation_availability_resource_simulation_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX simulation_availability_resource_simulation_id_idx ON public.simulation_availability_resource USING btree (simulation_id);


--

-- Name: simulation_positions_resource_simulation_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX simulation_positions_resource_simulation_id_idx ON public.simulation_positions_resource USING btree (simulation_id);


--

-- Name: simulation_positions_resource_v2_value_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX simulation_positions_resource_v2_value_idx ON public.simulation_positions_resource USING btree (value);


--
