-- Indexes: standard_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_standard_groups_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_standard_groups_mcp ON public.standard_groups_resource USING btree (mcp);


--
