-- Tables: agent_*_artifact (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: agent_artifact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_artifact (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT agents_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT agents_updated_at_not_null NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT agents_id_v7_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT agents_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT agents_mcp_not_null NOT NULL
);


--
