-- Table definitions + constraints: department_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: department_artifact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department_artifact (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT departments_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT departments_updated_at_not_null NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT departments_id_v7_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT departments_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT departments_mcp_not_null NOT NULL
);


--

-- Name: department_artifact departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_artifact
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
