-- Tables: model_*_artifact (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: model_artifact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_artifact (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT models_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT models_updated_at_not_null NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT models_id_v7_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT models_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT models_mcp_not_null NOT NULL
);


--
