-- Table definitions + constraints: parameter_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: parameter_artifact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_artifact (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT parameters_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT parameters_updated_at_not_null NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT parameters_id_v7_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT parameters_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT parameters_mcp_not_null NOT NULL
);


--

-- Name: parameter_artifact parameters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_artifact
    ADD CONSTRAINT parameters_pkey PRIMARY KEY (id);


--
