-- Table definitions + constraints: provider_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: provider_artifact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_artifact (
    id uuid DEFAULT uuidv7() CONSTRAINT provider_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT provider_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT provider_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT provider_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT provider_mcp_not_null NOT NULL
);


--

-- Name: provider_artifact provider_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_artifact
    ADD CONSTRAINT provider_pkey PRIMARY KEY (id);


--
