-- Tables: rubric_*_artifact (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: rubric_artifact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rubric_artifact (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT rubrics_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT rubrics_updated_at_not_null NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT rubrics_id_v7_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT rubrics_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT rubrics_mcp_not_null NOT NULL
);


--
