-- Table definitions + constraints: scenario_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: scenario_artifact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scenario_artifact (
    created_at timestamp with time zone DEFAULT now() CONSTRAINT scenarios_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT scenarios_updated_at_not_null NOT NULL,
    id uuid DEFAULT uuidv7() CONSTRAINT scenarios_id_v7_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT scenarios_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT scenarios_mcp_not_null NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: scenario_artifact scenarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_artifact
    ADD CONSTRAINT scenarios_pkey PRIMARY KEY (id);


--
