-- Table definitions + constraints: tool_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: tool_artifact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_artifact (
    id uuid DEFAULT uuidv7() CONSTRAINT tools_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT tools_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT tools_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: tool_artifact tools_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_artifact
    ADD CONSTRAINT tools_pkey PRIMARY KEY (id);


--
