-- Indexes: document_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: document_departments_department_id_v7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_departments_department_id_v7_idx ON public.document_departments_junction USING btree (department_id);


--

-- Name: document_departments_document_id_v7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_departments_document_id_v7_idx ON public.document_departments_junction USING btree (document_id);


--

-- Name: document_descriptions_description_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_descriptions_description_id_idx ON public.document_descriptions_junction USING btree (description_id);


--

-- Name: document_descriptions_document_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_descriptions_document_id_idx ON public.document_descriptions_junction USING btree (document_id);


--

-- Name: document_documents_document_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_documents_document_id_idx ON public.document_documents_junction USING btree (document_id);


--

-- Name: document_documents_documents_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_documents_documents_id_idx ON public.document_documents_junction USING btree (documents_id);


--

-- Name: document_flags_document_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_flags_document_id_idx ON public.document_flags_junction USING btree (document_id);


--

-- Name: document_flags_flag_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_flags_flag_id_idx ON public.document_flags_junction USING btree (flag_id);


--

-- Name: document_names_document_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_names_document_id_idx ON public.document_names_junction USING btree (document_id);


--

-- Name: document_names_name_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_names_name_id_idx ON public.document_names_junction USING btree (name_id);


--

-- Name: document_parameters_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_parameters_active_idx ON public.document_parameters_junction USING btree (active);


--

-- Name: document_parameters_document_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_parameters_document_id_idx ON public.document_parameters_junction USING btree (document_id);


--

-- Name: document_parameters_generated_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_parameters_generated_idx ON public.document_parameters_junction USING btree (generated);


--

-- Name: document_parameters_mcp_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_parameters_mcp_idx ON public.document_parameters_junction USING btree (mcp);


--

-- Name: document_parameters_parameter_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_parameters_parameter_id_idx ON public.document_parameters_junction USING btree (parameter_id);


--

-- Name: document_parameters_type_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_parameters_type_idx ON public.document_parameters_junction USING btree (type);


--

-- Name: document_uploads_junction_document_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_uploads_junction_document_id_idx ON public.document_files_junction USING btree (document_id);


--

-- Name: document_uploads_junction_uploads_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_uploads_junction_uploads_id_idx ON public.document_files_junction USING btree (files_id);


--

-- Name: idx_document_departments_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_departments_generated ON public.document_departments_junction USING btree (generated);


--

-- Name: idx_document_departments_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_departments_mcp ON public.document_departments_junction USING btree (mcp);


--

-- Name: idx_document_descriptions_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_descriptions_generated ON public.document_descriptions_junction USING btree (generated);


--

-- Name: idx_document_descriptions_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_descriptions_mcp ON public.document_descriptions_junction USING btree (mcp);


--

-- Name: idx_document_flags_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_flags_generated ON public.document_flags_junction USING btree (generated);


--

-- Name: idx_document_flags_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_flags_mcp ON public.document_flags_junction USING btree (mcp);


--

-- Name: idx_document_images_junction_document_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_images_junction_document_id ON public.document_images_junction USING btree (document_id);


--

-- Name: idx_document_images_junction_images_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_images_junction_images_id ON public.document_images_junction USING btree (images_id);


--

-- Name: idx_document_names_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_names_generated ON public.document_names_junction USING btree (generated);


--

-- Name: idx_document_names_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_names_mcp ON public.document_names_junction USING btree (mcp);


--

-- Name: idx_document_parameter_fields_document_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_parameter_fields_document_id ON public.document_parameter_fields_junction USING btree (document_id);


--

-- Name: idx_document_parameter_fields_parameter_field_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_parameter_fields_parameter_field_id ON public.document_parameter_fields_junction USING btree (parameter_field_id);


--

-- Name: idx_document_texts_junction_document_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_texts_junction_document_id ON public.document_texts_junction USING btree (document_id);


--

-- Name: idx_document_texts_junction_texts_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_texts_junction_texts_id ON public.document_texts_junction USING btree (texts_id);


--
