-- Indexes: persona_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_persona_colors_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_colors_generated ON public.persona_colors_junction USING btree (generated);


--

-- Name: idx_persona_colors_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_colors_mcp ON public.persona_colors_junction USING btree (mcp);


--

-- Name: idx_persona_departments_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_departments_generated ON public.persona_departments_junction USING btree (generated);


--

-- Name: idx_persona_departments_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_departments_mcp ON public.persona_departments_junction USING btree (mcp);


--

-- Name: idx_persona_descriptions_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_descriptions_generated ON public.persona_descriptions_junction USING btree (generated);


--

-- Name: idx_persona_descriptions_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_descriptions_mcp ON public.persona_descriptions_junction USING btree (mcp);


--

-- Name: idx_persona_examples_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_examples_generated ON public.persona_examples_junction USING btree (generated);


--

-- Name: idx_persona_examples_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_examples_mcp ON public.persona_examples_junction USING btree (mcp);


--

-- Name: idx_persona_flags_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_flags_generated ON public.persona_flags_junction USING btree (generated);


--

-- Name: idx_persona_flags_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_flags_mcp ON public.persona_flags_junction USING btree (mcp);


--

-- Name: idx_persona_icons_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_icons_generated ON public.persona_icons_junction USING btree (generated);


--

-- Name: idx_persona_icons_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_icons_mcp ON public.persona_icons_junction USING btree (mcp);


--

-- Name: idx_persona_instructions_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_instructions_generated ON public.persona_instructions_junction USING btree (generated);


--

-- Name: idx_persona_instructions_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_instructions_mcp ON public.persona_instructions_junction USING btree (mcp);


--

-- Name: idx_persona_names_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_names_generated ON public.persona_names_junction USING btree (generated);


--

-- Name: idx_persona_names_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_names_mcp ON public.persona_names_junction USING btree (mcp);


--

-- Name: idx_persona_parameter_fields_parameter_field_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_parameter_fields_parameter_field_id ON public.persona_parameter_fields_junction USING btree (parameter_fields_id);


--

-- Name: idx_persona_parameter_fields_persona_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_persona_parameter_fields_persona_id ON public.persona_parameter_fields_junction USING btree (persona_id);


--

-- Name: persona_colors_color_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_colors_color_id_idx ON public.persona_colors_junction USING btree (colors_id);


--

-- Name: persona_colors_persona_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_colors_persona_id_idx ON public.persona_colors_junction USING btree (persona_id);


--

-- Name: persona_departments_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_departments_active_idx ON public.persona_departments_junction USING btree (active);


--

-- Name: persona_departments_department_id_v7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_departments_department_id_v7_idx ON public.persona_departments_junction USING btree (departments_id);


--

-- Name: persona_departments_persona_id_v7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_departments_persona_id_v7_idx ON public.persona_departments_junction USING btree (persona_id);


--

-- Name: persona_descriptions_description_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_descriptions_description_id_idx ON public.persona_descriptions_junction USING btree (descriptions_id);


--

-- Name: persona_descriptions_persona_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_descriptions_persona_id_idx ON public.persona_descriptions_junction USING btree (persona_id);


--

-- Name: persona_examples_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_examples_active_idx ON public.persona_examples_junction USING btree (active);


--

-- Name: persona_examples_example_id_v7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_examples_example_id_v7_idx ON public.persona_examples_junction USING btree (examples_id);


--

-- Name: persona_examples_persona_id_v7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_examples_persona_id_v7_idx ON public.persona_examples_junction USING btree (persona_id);


--

-- Name: persona_flags_flag_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_flags_flag_id_idx ON public.persona_flags_junction USING btree (flags_id);


--

-- Name: persona_flags_persona_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_flags_persona_id_idx ON public.persona_flags_junction USING btree (persona_id);


--

-- Name: persona_icons_icon_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_icons_icon_id_idx ON public.persona_icons_junction USING btree (icons_id);


--

-- Name: persona_icons_persona_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_icons_persona_id_idx ON public.persona_icons_junction USING btree (persona_id);


--

-- Name: persona_instructions_instruction_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_instructions_instruction_id_idx ON public.persona_instructions_junction USING btree (instructions_id);


--

-- Name: persona_instructions_persona_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_instructions_persona_id_idx ON public.persona_instructions_junction USING btree (persona_id);


--

-- Name: persona_names_name_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_names_name_id_idx ON public.persona_names_junction USING btree (names_id);


--

-- Name: persona_names_persona_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_names_persona_id_idx ON public.persona_names_junction USING btree (persona_id);


--

-- Name: persona_personas_persona_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_personas_persona_id_idx ON public.persona_personas_junction USING btree (persona_id);


--

-- Name: persona_personas_personas_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_personas_personas_id_idx ON public.persona_personas_junction USING btree (personas_id);


--

-- Name: persona_voices_junction_voice_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX persona_voices_junction_voice_id_idx ON public.persona_voices_junction USING btree (voices_id);


--
