/**
 * Resource types matching the database resources enum
 * Used for AI generation state management and type safety
 */
export type ResourceType =
  | "names"
  | "descriptions"
  | "colors"
  | "icons"
  | "instructions"
  | "flags"
  | "examples"
  | "fields"
  | "parameters"
  | "parameter_fields"
  | "departments"
  | "points"
  | "standard_groups"
  | "standards"
  | "scenarios"
  | "scenario_flags"
  | "scenario_positions"
  | "scenario_rubrics"
  | "simulation_positions"
  | "simulations"
  | "templates"
  | "uploads"
  | "images"
  | "texts"
  | "models"
  | "providers"
  | "prompts"
  | "values"
  | "endpoints"
  | "keys"
  | "modalities"
  | "pricing"
  | "qualities"
  | "reasoning_levels"
  | "temperature_levels"
  | "voices"
  | "tools"
  | "settings"
  | "args"
  | "args_outputs"
