-- Table definitions + constraints: auth_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: auth_drafts_departments_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_drafts_departments_connection (
    draft_id uuid NOT NULL,
    departments_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: auth_drafts_descriptions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_drafts_descriptions_connection (
    draft_id uuid NOT NULL,
    descriptions_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: auth_drafts_flags_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_drafts_flags_connection (
    draft_id uuid NOT NULL,
    flags_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: auth_drafts_items_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_drafts_items_connection (
    draft_id uuid NOT NULL,
    items_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: auth_drafts_names_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_drafts_names_connection (
    draft_id uuid NOT NULL,
    names_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: auth_drafts_profiles_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_drafts_profiles_connection (
    draft_id uuid NOT NULL,
    profiles_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: auth_drafts_protocols_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_drafts_protocols_connection (
    draft_id uuid NOT NULL,
    protocols_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: auth_drafts_slugs_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_drafts_slugs_connection (
    draft_id uuid NOT NULL,
    slugs_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: auth_item_keys_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_item_keys_calls_connection (
    auth_item_keys_id uuid NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: auth_drafts_departments_connection auth_drafts_departments_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_drafts_departments_connection
    ADD CONSTRAINT auth_drafts_departments_connection_pkey PRIMARY KEY (draft_id, departments_id);


--

-- Name: auth_drafts_descriptions_connection auth_drafts_descriptions_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_drafts_descriptions_connection
    ADD CONSTRAINT auth_drafts_descriptions_connection_pkey PRIMARY KEY (draft_id, descriptions_id);


--

-- Name: auth_drafts_flags_connection auth_drafts_flags_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_drafts_flags_connection
    ADD CONSTRAINT auth_drafts_flags_connection_pkey PRIMARY KEY (draft_id, flags_id);


--

-- Name: auth_drafts_items_connection auth_drafts_items_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_drafts_items_connection
    ADD CONSTRAINT auth_drafts_items_connection_pkey PRIMARY KEY (draft_id, items_id);


--

-- Name: auth_drafts_names_connection auth_drafts_names_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_drafts_names_connection
    ADD CONSTRAINT auth_drafts_names_connection_pkey PRIMARY KEY (draft_id, names_id);


--

-- Name: auth_drafts_profiles_connection auth_drafts_profiles_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_drafts_profiles_connection
    ADD CONSTRAINT auth_drafts_profiles_connection_pkey PRIMARY KEY (draft_id, profiles_id);


--

-- Name: auth_drafts_protocols_connection auth_drafts_protocols_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_drafts_protocols_connection
    ADD CONSTRAINT auth_drafts_protocols_connection_pkey PRIMARY KEY (draft_id, protocols_id);


--

-- Name: auth_drafts_slugs_connection auth_drafts_slugs_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_drafts_slugs_connection
    ADD CONSTRAINT auth_drafts_slugs_connection_pkey PRIMARY KEY (draft_id, slugs_id);


--

-- Name: auth_item_keys_calls_connection auth_item_keys_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_item_keys_calls_connection
    ADD CONSTRAINT auth_item_keys_calls_connection_pkey PRIMARY KEY (auth_item_keys_id, call_id);


--
