-- Table definitions + constraints: cohort_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: cohort_drafts_cohorts_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_cohorts_connection (
    draft_id uuid NOT NULL,
    cohorts_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: cohort_drafts_departments_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_departments_connection (
    draft_id uuid NOT NULL,
    departments_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: cohort_drafts_descriptions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_descriptions_connection (
    draft_id uuid NOT NULL,
    descriptions_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: cohort_drafts_flags_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_flags_connection (
    draft_id uuid NOT NULL,
    flags_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: cohort_drafts_names_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_names_connection (
    draft_id uuid NOT NULL,
    names_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: cohort_drafts_profile_personas_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_profile_personas_connection (
    draft_id uuid NOT NULL,
    profile_personas_id uuid CONSTRAINT cohort_drafts_profile_personas_con_profile_personas_id_not_null NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: cohort_drafts_profiles_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_profiles_connection (
    draft_id uuid NOT NULL,
    profiles_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: cohort_drafts_simulation_availability_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_simulation_availability_connection (
    id uuid DEFAULT uuidv7() NOT NULL,
    draft_id uuid CONSTRAINT cohort_drafts_simulation_availability_connect_draft_id_not_null NOT NULL,
    simulation_availability_id uuid CONSTRAINT cohort_drafts_simulation_av_simulation_availability_id_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT cohort_drafts_simulation_availability_connectio_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT cohort_drafts_simulation_availability_connec_generated_not_null NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT cohort_drafts_simulation_availability_conne_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT cohort_drafts_simulation_availability_conne_updated_at_not_null NOT NULL
);


--

-- Name: cohort_drafts_simulation_positions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_simulation_positions_connection (
    draft_id uuid NOT NULL,
    simulation_positions_id uuid CONSTRAINT cohort_drafts_simulation_posit_simulation_positions_id_not_null NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT cohort_drafts_simulation_positions_connecti_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() CONSTRAINT cohort_drafts_simulation_positions_connecti_updated_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT cohort_drafts_simulation_positions_connectio_generated_not_null NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: cohort_drafts_simulations_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cohort_drafts_simulations_connection (
    draft_id uuid NOT NULL,
    simulations_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: cohort_drafts_cohorts_connection cohort_drafts_cohorts_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_cohorts_connection
    ADD CONSTRAINT cohort_drafts_cohorts_connection_pkey PRIMARY KEY (draft_id, cohorts_id);


--

-- Name: cohort_drafts_departments_connection cohort_drafts_departments_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_departments_connection
    ADD CONSTRAINT cohort_drafts_departments_connection_pkey PRIMARY KEY (draft_id, departments_id);


--

-- Name: cohort_drafts_descriptions_connection cohort_drafts_descriptions_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_descriptions_connection
    ADD CONSTRAINT cohort_drafts_descriptions_connection_pkey PRIMARY KEY (draft_id, descriptions_id);


--

-- Name: cohort_drafts_flags_connection cohort_drafts_flags_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_flags_connection
    ADD CONSTRAINT cohort_drafts_flags_connection_pkey PRIMARY KEY (draft_id, flags_id);


--

-- Name: cohort_drafts_names_connection cohort_drafts_names_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_names_connection
    ADD CONSTRAINT cohort_drafts_names_connection_pkey PRIMARY KEY (draft_id, names_id);


--

-- Name: cohort_drafts_profile_personas_connection cohort_drafts_profile_personas_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_profile_personas_connection
    ADD CONSTRAINT cohort_drafts_profile_personas_connection_pkey PRIMARY KEY (draft_id, profile_personas_id);


--

-- Name: cohort_drafts_profiles_connection cohort_drafts_profiles_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_profiles_connection
    ADD CONSTRAINT cohort_drafts_profiles_connection_pkey PRIMARY KEY (draft_id, profiles_id);


--

-- Name: cohort_drafts_simulation_availability_connection cohort_drafts_simulation_availability_connection_draft_availabi; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_simulation_availability_connection
    ADD CONSTRAINT cohort_drafts_simulation_availability_connection_draft_availabi UNIQUE (draft_id, simulation_availability_id);


--

-- Name: cohort_drafts_simulation_availability_connection cohort_drafts_simulation_availability_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_simulation_availability_connection
    ADD CONSTRAINT cohort_drafts_simulation_availability_connection_pkey PRIMARY KEY (id);


--

-- Name: cohort_drafts_simulation_positions_connection cohort_drafts_simulation_positions_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_simulation_positions_connection
    ADD CONSTRAINT cohort_drafts_simulation_positions_connection_pkey PRIMARY KEY (draft_id, simulation_positions_id);


--

-- Name: cohort_drafts_simulations_connection cohort_drafts_simulations_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cohort_drafts_simulations_connection
    ADD CONSTRAINT cohort_drafts_simulations_connection_pkey PRIMARY KEY (draft_id, simulations_id);


--
