-- Table definitions + constraints: department_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: department_drafts_descriptions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department_drafts_descriptions_connection (
    draft_id uuid NOT NULL,
    descriptions_id uuid CONSTRAINT department_drafts_descriptions_connect_descriptions_id_not_null NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: department_drafts_flags_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department_drafts_flags_connection (
    draft_id uuid NOT NULL,
    flags_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: department_drafts_names_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department_drafts_names_connection (
    draft_id uuid NOT NULL,
    names_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: department_drafts_profiles_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department_drafts_profiles_connection (
    draft_id uuid NOT NULL,
    profiles_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: department_drafts_settings_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department_drafts_settings_connection (
    draft_id uuid NOT NULL,
    settings_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: department_drafts_descriptions_connection department_drafts_descriptions_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_drafts_descriptions_connection
    ADD CONSTRAINT department_drafts_descriptions_connection_pkey PRIMARY KEY (draft_id, descriptions_id);


--

-- Name: department_drafts_flags_connection department_drafts_flags_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_drafts_flags_connection
    ADD CONSTRAINT department_drafts_flags_connection_pkey PRIMARY KEY (draft_id, flags_id);


--

-- Name: department_drafts_names_connection department_drafts_names_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_drafts_names_connection
    ADD CONSTRAINT department_drafts_names_connection_pkey PRIMARY KEY (draft_id, names_id);


--

-- Name: department_drafts_profiles_connection department_drafts_profiles_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_drafts_profiles_connection
    ADD CONSTRAINT department_drafts_profiles_connection_pkey PRIMARY KEY (draft_id, profiles_id);


--

-- Name: department_drafts_settings_connection department_drafts_settings_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_drafts_settings_connection
    ADD CONSTRAINT department_drafts_settings_connection_pkey PRIMARY KEY (draft_id, settings_id);


--
