-- Table definitions + constraints: document_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: document_drafts_departments_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_departments_connection (
    draft_id uuid NOT NULL,
    departments_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_descriptions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_descriptions_connection (
    draft_id uuid NOT NULL,
    descriptions_id uuid CONSTRAINT document_drafts_descriptions_connectio_descriptions_id_not_null NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_documents_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_documents_connection (
    draft_id uuid NOT NULL,
    documents_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_flags_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_flags_connection (
    draft_id uuid NOT NULL,
    flags_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_images_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_images_connection (
    draft_id uuid NOT NULL,
    images_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_names_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_names_connection (
    draft_id uuid NOT NULL,
    names_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_parameter_fields_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_parameter_fields_connection (
    draft_id uuid NOT NULL,
    parameter_fields_id uuid CONSTRAINT document_drafts_parameter_fields_c_parameter_fields_id_not_null NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_parameters_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_parameters_connection (
    draft_id uuid NOT NULL,
    parameters_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_texts_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_texts_connection (
    draft_id uuid NOT NULL,
    texts_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_uploads_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_uploads_connection (
    draft_id uuid NOT NULL,
    uploads_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_profiles_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_drafts_profiles_connection (
    draft_id uuid NOT NULL,
    profiles_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: document_drafts_departments_connection document_drafts_departments_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_departments_connection
    ADD CONSTRAINT document_drafts_departments_connection_pkey PRIMARY KEY (draft_id, departments_id);


--

-- Name: document_drafts_descriptions_connection document_drafts_descriptions_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_descriptions_connection
    ADD CONSTRAINT document_drafts_descriptions_connection_pkey PRIMARY KEY (draft_id, descriptions_id);


--

-- Name: document_drafts_documents_connection document_drafts_documents_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_documents_connection
    ADD CONSTRAINT document_drafts_documents_connection_pkey PRIMARY KEY (draft_id, documents_id);


--

-- Name: document_drafts_flags_connection document_drafts_flags_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_flags_connection
    ADD CONSTRAINT document_drafts_flags_connection_pkey PRIMARY KEY (draft_id, flags_id);


--

-- Name: document_drafts_images_connection document_drafts_images_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_images_connection
    ADD CONSTRAINT document_drafts_images_connection_pkey PRIMARY KEY (draft_id, images_id);


--

-- Name: document_drafts_names_connection document_drafts_names_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_names_connection
    ADD CONSTRAINT document_drafts_names_connection_pkey PRIMARY KEY (draft_id, names_id);


--

-- Name: document_drafts_parameter_fields_connection document_drafts_parameter_fields_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_parameter_fields_connection
    ADD CONSTRAINT document_drafts_parameter_fields_connection_pkey PRIMARY KEY (draft_id, parameter_fields_id);


--

-- Name: document_drafts_parameters_connection document_drafts_parameters_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_parameters_connection
    ADD CONSTRAINT document_drafts_parameters_connection_pkey PRIMARY KEY (draft_id, parameters_id);


--

-- Name: document_drafts_profiles_connection document_drafts_profiles_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_profiles_connection
    ADD CONSTRAINT document_drafts_profiles_connection_pkey PRIMARY KEY (draft_id, profiles_id);


--

-- Name: document_drafts_texts_connection document_drafts_texts_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_texts_connection
    ADD CONSTRAINT document_drafts_texts_connection_pkey PRIMARY KEY (draft_id, texts_id);


--

-- Name: document_drafts_uploads_connection document_drafts_uploads_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_drafts_uploads_connection
    ADD CONSTRAINT document_drafts_uploads_connection_pkey PRIMARY KEY (draft_id, uploads_id);


--
