-- Table definitions + constraints: feedbacks_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: feedbacks_standards_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedbacks_standards_connection (
    feedbacks_id uuid NOT NULL,
    standard_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: feedbacks_standards_connection feedbacks_standards_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedbacks_standards_connection
    ADD CONSTRAINT feedbacks_standards_connection_pkey PRIMARY KEY (feedbacks_id, standard_id);


--
