-- Table definitions + constraints: groups_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: groups_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groups_calls_connection (
    groups_id uuid CONSTRAINT groups_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: groups_groups_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groups_groups_connection (
    groups_id uuid NOT NULL,
    group_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: groups_calls_connection groups_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups_calls_connection
    ADD CONSTRAINT groups_calls_connection_pkey PRIMARY KEY (groups_id, call_id);


--

-- Name: groups_groups_connection groups_groups_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups_groups_connection
    ADD CONSTRAINT groups_groups_connection_pkey PRIMARY KEY (groups_id, group_id);


--
