-- Table definitions + constraints: home_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: home_cohorts_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_cohorts_connection (
    home_id uuid NOT NULL,
    cohorts_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: home_departments_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_departments_connection (
    home_id uuid NOT NULL,
    departments_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: home_profiles_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_profiles_connection (
    home_id uuid NOT NULL,
    profiles_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: home_simulations_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_simulations_connection (
    home_id uuid NOT NULL,
    simulations_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: home_profile_personas_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_profile_personas_connection (
    home_id uuid NOT NULL,
    profile_personas_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: home_simulation_availability_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_simulation_availability_connection (
    home_id uuid NOT NULL,
    simulation_availability_id uuid CONSTRAINT home_simulation_availabilit_simulation_availability_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: home_simulation_positions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_simulation_positions_connection (
    home_id uuid NOT NULL,
    simulation_positions_id uuid CONSTRAINT home_simulation_positions_conn_simulation_positions_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: home_cohorts_connection home_cohorts_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_cohorts_connection
    ADD CONSTRAINT home_cohorts_connection_pkey PRIMARY KEY (home_id, cohorts_id);


--

-- Name: home_departments_connection home_departments_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_departments_connection
    ADD CONSTRAINT home_departments_connection_pkey PRIMARY KEY (home_id, departments_id);


--

-- Name: home_profile_personas_connection home_profile_personas_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_profile_personas_connection
    ADD CONSTRAINT home_profile_personas_connection_pkey PRIMARY KEY (home_id, profile_personas_id);


--

-- Name: home_profiles_connection home_profiles_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_profiles_connection
    ADD CONSTRAINT home_profiles_connection_pkey PRIMARY KEY (home_id, profiles_id);


--

-- Name: home_simulation_availability_connection home_simulation_availability_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_simulation_availability_connection
    ADD CONSTRAINT home_simulation_availability_connection_pkey PRIMARY KEY (home_id, simulation_availability_id);


--

-- Name: home_simulation_positions_connection home_simulation_positions_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_simulation_positions_connection
    ADD CONSTRAINT home_simulation_positions_connection_pkey PRIMARY KEY (home_id, simulation_positions_id);


--

-- Name: home_simulations_connection home_simulations_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_simulations_connection
    ADD CONSTRAINT home_simulations_connection_pkey PRIMARY KEY (home_id, simulations_id);


--
