-- Table definitions + constraints: icons_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: icons_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.icons_calls_connection (
    icons_id uuid CONSTRAINT icons_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: icons_calls_connection icons_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.icons_calls_connection
    ADD CONSTRAINT icons_calls_connection_pkey PRIMARY KEY (icons_id, call_id);


--
