-- Tables: images_*_connection (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: images_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images_calls_connection (
    images_id uuid CONSTRAINT images_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: images_images_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images_images_connection (
    image_id uuid NOT NULL,
    images_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: images_qualities_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images_qualities_connection (
    image_id uuid NOT NULL,
    quality_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
