-- Table definitions + constraints: names_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: names_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.names_calls_connection (
    names_id uuid CONSTRAINT names_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: names_calls_connection names_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.names_calls_connection
    ADD CONSTRAINT names_calls_connection_pkey PRIMARY KEY (names_id, call_id);


--
