-- Table definitions + constraints: objectives_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: objectives_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.objectives_calls_connection (
    objectives_id uuid CONSTRAINT objectives_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: objectives_calls_connection objectives_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objectives_calls_connection
    ADD CONSTRAINT objectives_calls_connection_pkey PRIMARY KEY (objectives_id, call_id);


--
