-- Tables: parameter_*_connection (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: parameter_drafts_departments_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_drafts_departments_connection (
    draft_id uuid NOT NULL,
    departments_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: parameter_drafts_descriptions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_drafts_descriptions_connection (
    draft_id uuid NOT NULL,
    descriptions_id uuid CONSTRAINT parameter_drafts_descriptions_connecti_descriptions_id_not_null NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: parameter_drafts_fields_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_drafts_fields_connection (
    draft_id uuid NOT NULL,
    fields_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: parameter_drafts_flags_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_drafts_flags_connection (
    draft_id uuid NOT NULL,
    flags_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: parameter_drafts_names_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_drafts_names_connection (
    draft_id uuid NOT NULL,
    names_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: parameter_drafts_parameters_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_drafts_parameters_connection (
    draft_id uuid NOT NULL,
    parameters_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: parameter_drafts_profiles_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_drafts_profiles_connection (
    draft_id uuid NOT NULL,
    profiles_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: parameter_fields_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_fields_calls_connection (
    parameter_fields_id uuid CONSTRAINT parameter_fields_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
