-- Tables: personas_*_connection (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: personas_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_calls_connection (
    personas_id uuid CONSTRAINT personas_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: personas_personas_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_personas_connection (
    personas_entry_id uuid NOT NULL,
    personas_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--
