-- Table definitions + constraints: points_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: points_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.points_calls_connection (
    points_id uuid CONSTRAINT points_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: points_calls_connection points_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_calls_connection
    ADD CONSTRAINT points_calls_connection_pkey PRIMARY KEY (points_id, call_id);


--
