-- Tables: practice_*_connection (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: practice_cohorts_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.practice_cohorts_connection (
    practice_id uuid NOT NULL,
    cohorts_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: practice_departments_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.practice_departments_connection (
    practice_id uuid NOT NULL,
    departments_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: practice_profiles_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.practice_profiles_connection (
    practice_id uuid NOT NULL,
    profiles_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: practice_simulations_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.practice_simulations_connection (
    practice_id uuid NOT NULL,
    simulations_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: practice_profile_personas_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.practice_profile_personas_connection (
    practice_id uuid NOT NULL,
    profile_personas_id uuid CONSTRAINT practice_profile_personas_connecti_profile_personas_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: practice_simulation_availability_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.practice_simulation_availability_connection (
    practice_id uuid CONSTRAINT practice_simulation_availability_connectio_practice_id_not_null NOT NULL,
    simulation_availability_id uuid CONSTRAINT practice_simulation_availab_simulation_availability_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: practice_simulation_positions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.practice_simulation_positions_connection (
    practice_id uuid NOT NULL,
    simulation_positions_id uuid CONSTRAINT practice_simulation_positions__simulation_positions_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--
