-- Tables: pricing_*_connection (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: pricing_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pricing_calls_connection (
    pricing_id uuid CONSTRAINT pricing_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
