-- Tables: responses_*_connection (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: responses_options_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.responses_options_connection (
    responses_id uuid NOT NULL,
    option_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: responses_questions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.responses_questions_connection (
    responses_id uuid NOT NULL,
    question_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
