-- Table definitions + constraints: run_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: run_positions_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_positions_calls_connection (
    run_positions_id uuid CONSTRAINT run_positions_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: run_pricing_pricing_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_pricing_pricing_connection (
    run_pricing_id uuid NOT NULL,
    pricing_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: run_rubrics_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_rubrics_calls_connection (
    run_rubrics_id uuid CONSTRAINT run_rubrics_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: run_positions_calls_connection run_positions_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_positions_calls_connection
    ADD CONSTRAINT run_positions_calls_connection_pkey PRIMARY KEY (run_positions_id, call_id);


--

-- Name: run_pricing_pricing_connection run_pricing_pricing_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_pricing_pricing_connection
    ADD CONSTRAINT run_pricing_pricing_connection_pkey PRIMARY KEY (run_pricing_id, pricing_id);


--

-- Name: run_rubrics_calls_connection run_rubrics_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_rubrics_calls_connection
    ADD CONSTRAINT run_rubrics_calls_connection_pkey PRIMARY KEY (run_rubrics_id, call_id);


--
