-- Table definitions + constraints: scenarios_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: scenarios_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scenarios_calls_connection (
    scenarios_id uuid CONSTRAINT scenarios_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: scenarios_calls_connection scenarios_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenarios_calls_connection
    ADD CONSTRAINT scenarios_calls_connection_pkey PRIMARY KEY (scenarios_id, call_id);


--
