-- Tables: setting_*_connection (and variants)
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: setting_drafts_agents_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_agents_connection (
    draft_id uuid NOT NULL,
    agents_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_auth_item_keys_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_auth_item_keys_connection (
    draft_id uuid NOT NULL,
    auth_item_keys_id uuid CONSTRAINT setting_drafts_auth_item_keys_connec_auth_item_keys_id_not_null NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_auths_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_auths_connection (
    draft_id uuid NOT NULL,
    auths_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_colors_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_colors_connection (
    draft_id uuid NOT NULL,
    colors_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_departments_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_departments_connection (
    draft_id uuid NOT NULL,
    departments_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_descriptions_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_descriptions_connection (
    draft_id uuid NOT NULL,
    descriptions_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_flags_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_flags_connection (
    draft_id uuid NOT NULL,
    flags_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_items_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_items_connection (
    draft_id uuid NOT NULL,
    items_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_names_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_names_connection (
    draft_id uuid NOT NULL,
    names_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_profiles_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_profiles_connection (
    draft_id uuid NOT NULL,
    profiles_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_provider_keys_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_provider_keys_connection (
    draft_id uuid NOT NULL,
    provider_keys_id uuid CONSTRAINT setting_drafts_provider_keys_connecti_provider_keys_id_not_null NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_settings_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_settings_connection (
    draft_id uuid NOT NULL,
    settings_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: setting_drafts_thresholds_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_thresholds_connection (
    draft_id uuid NOT NULL,
    thresholds_id uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
