-- Table definitions + constraints: uploads_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: uploads_uploads_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uploads_uploads_connection (
    uploads_id uuid NOT NULL,
    upload_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: uploads_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uploads_calls_connection (
    uploads_id uuid CONSTRAINT uploads_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: uploads_calls_connection uploads_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uploads_calls_connection
    ADD CONSTRAINT uploads_calls_connection_pkey PRIMARY KEY (uploads_id, call_id);


--

-- Name: uploads_uploads_connection uploads_uploads_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uploads_uploads_connection
    ADD CONSTRAINT uploads_uploads_connection_pkey PRIMARY KEY (uploads_id, upload_id);


--
