-- Table definitions + constraints: values_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: values_calls_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.values_calls_connection (
    values_id uuid CONSTRAINT values_calls_connection_id_not_null NOT NULL,
    call_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: values_calls_connection values_calls_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.values_calls_connection
    ADD CONSTRAINT values_calls_connection_pkey PRIMARY KEY (values_id, call_id);


--
