"""Handler for hint_end WebSocket event - emits final client event for hint generation completion."""

import uuid
from typing import Any, cast

from app.infra.v4.websocket.get_db_connection import get_db_connection
from app.infra.v4.websocket.handler_wrapper import handle_internal_event
from app.infra.v4.websocket.openapi_helpers import register_server_endpoint
from app.infra.v4.websocket.typed_emit import emit_to_client
from app.main import get_internal_sio, sio
from fastapi import APIRouter
from pydantic import BaseModel
from utils.sql_helper import execute_sql_typed

internal_sio = get_internal_sio()

client_router = APIRouter()
server_router = APIRouter()

# Import autogenerated types
from app.sql.types import (GetTextToolCallResultsSqlParams,
                           GetTextToolCallResultsSqlRow,
                           TextGenerationCompleteSqlParams,
                           TextGenerationCompleteSqlRow)

SQL_GET_TOOL_RESULTS_PATH = "app/sql/v4/generate/text/get_text_tool_call_results_complete.sql"
SQL_COMPLETE_PATH = "app/sql/v4/generate/text/text_generation_complete_complete.sql"


class HintEndApiRequest(BaseModel):
    """Payload for hint_end event."""

    sid: str
    type: str  # "tool_call_complete" | "run_complete"
    resource_id: str | None = None
    run_id: str
    group_id: str | None = None
    department_id: str | None = None
    tool_call_id: str | None = None
    call_id: str | None = None
    tool_name: str | None = None
    tool_type: str | None = None
    final_content: str | None = None
    arguments_raw: str | None = None


async def _hint_end_impl(
    sid: str,
    data: HintEndApiRequest,
    profile_id: uuid.UUID,
) -> None:
    """Handle hint completion - transforms to client event format."""
    if data.type == "tool_call_complete":
        # Route to tool-specific handler if needed
        # For hint agent, tools are handled by their own handlers
        # Just emit generic tool completion event
        await sio.emit(
            "simulation_hints_tool_complete",
            {
                "success": True,
                "resource_id": data.resource_id,
                "run_id": data.run_id,
                "tool_call_id": data.tool_call_id or "",
                "tool_type": data.tool_type,
            },
            room=sid,
        )
    elif data.type == "run_complete":
        # All tools done - extract results and finalize
        if not data.run_id:
            await emit_to_client(
                "simulation_hints_error",
                {
                    "success": False,
                    "message": "Missing run_id in run_complete event",
                },
                room=sid,
            )
            return

        try:
            from app.infra.v4.websocket.get_db_connection import \
                get_db_connection
            from utils.cache.invalidate_tags import invalidate_tags

            async with get_db_connection() as conn:
                model_run_id = uuid.UUID(data.run_id)
                resource_id = uuid.UUID(data.resource_id) if data.resource_id else None

                # 1. Extract tool results using SQL function
                tool_results_params = GetTextToolCallResultsSqlParams(
                    run_id=model_run_id
                )
                tool_results = cast(
                    GetTextToolCallResultsSqlRow,
                    await execute_sql_typed(
                        conn, SQL_GET_TOOL_RESULTS_PATH, params=tool_results_params
                    ),
                )

                # 2. Call comprehensive SQL function - does ALL database work
                complete_params = TextGenerationCompleteSqlParams(
                    profile_id=profile_id,
                    run_id=model_run_id,
                    resource_id=resource_id,
                    group_id=uuid.UUID(data.group_id) if data.group_id else None,
                    department_id=uuid.UUID(data.department_id) if data.department_id else None,
                )
                complete_result = cast(
                    TextGenerationCompleteSqlRow,
                    await execute_sql_typed(conn, SQL_COMPLETE_PATH, params=complete_params),
                )

                # 3. Invalidate cache if resource was created
                if resource_id:
                    await invalidate_tags(["hint_generation"])

            # 4. Extract hint-specific data from tool_results
            # tool_results is jsonb from SQL function
            hint_ids: list[str] = []
            hints_count = 0
            if complete_result.tool_results:
                # Parse tool_results to extract hint information
                # Format depends on how hints are stored in tool_results
                import json
                try:
                    if isinstance(complete_result.tool_results, dict):
                        # Extract hints from tool_results structure
                        # This depends on the actual structure returned by hint tool
                        pass
                    elif isinstance(complete_result.tool_results, str):
                        tool_results_dict = json.loads(complete_result.tool_results)
                        # Extract hint data if available
                        pass
                except Exception:
                    pass
            
            # 5. Emit final completion to client
            await sio.emit(
                "simulation_hints_complete",
                {
                    "success": complete_result.success,
                    "message": complete_result.message,
                    "chat_id": str(resource_id) if resource_id else None,
                    "tool_results": complete_result.tool_results,
                    "trace_id": complete_result.trace_id,
                    "hint_ids": hint_ids,
                    "hints_count": hints_count,
                },
                room=sid,
            )
        except Exception as e:
            await emit_to_client(
                "simulation_hints_error",
                {
                    "success": False,
                    "message": f"Failed to finalize hint generation: {str(e)}",
                },
                room=sid,
            )


@internal_sio.on("hint_end")  # type: ignore
async def hint_end_internal(data: dict[str, Any]) -> None:
    """Handle hint_end event from internal bus."""
    await handle_internal_event(
        data=data,
        request_type=HintEndApiRequest,
        handler=_hint_end_impl,  # type: ignore[arg-type]
        error_event_name="hint_error",
        error_response_type=None,
    )


register_server_endpoint(
    server_router,
    "/hint_end",
    HintEndApiRequest,
    "Handle hint generation completion",
)

