"""Per-resource socket event handlers.

Aggregates server_routers from all per-resource modules and imports the
dispatcher to register internal_sio listeners.
"""

from fastapi import APIRouter

from . import dispatcher  # noqa: F401 — registers internal_sio listeners
from .agents import server_router as agents_server_router
from .arg_positions import server_router as arg_positions_server_router
from .args import server_router as args_server_router
from .args_outputs import server_router as args_outputs_server_router
from .auth_item_keys import server_router as auth_item_keys_server_router
from .auths import server_router as auths_server_router
from .bindings import server_router as bindings_server_router
from .cohorts import server_router as cohorts_server_router
from .colors import server_router as colors_server_router
from .conditional_parameters import server_router as conditional_parameters_server_router
from .departments import server_router as departments_server_router
from .descriptions import server_router as descriptions_server_router
from .documents import server_router as documents_server_router
from .domains import server_router as domains_server_router
from .emails import server_router as emails_server_router
from .endpoints import server_router as endpoints_server_router
from .evals import server_router as evals_server_router
from .examples import server_router as examples_server_router
from .flags import server_router as flags_server_router
from .group_positions import server_router as group_positions_server_router
from .group_rubrics import server_router as group_rubrics_server_router
from .groups import server_router as groups_server_router
from .icons import server_router as icons_server_router
from .images import server_router as images_server_router
from .instructions import server_router as instructions_server_router
from .items import server_router as items_server_router
from .keys import server_router as keys_server_router
from .modalities import server_router as modalities_server_router
from .models import server_router as models_server_router
from .names import server_router as names_server_router
from .objectives import server_router as objectives_server_router
from .options import server_router as options_server_router
from .parameter_fields import server_router as parameter_fields_server_router
from .parameters import server_router as parameters_server_router
from .personas import server_router as personas_server_router
from .points import server_router as points_server_router
from .pricing import server_router as pricing_server_router
from .problem_statements import server_router as problem_statements_server_router
from .profiles import server_router as profiles_server_router
from .prompts import server_router as prompts_server_router
from .protocols import server_router as protocols_server_router
from .provider_keys import server_router as provider_keys_server_router
from .providers import server_router as providers_server_router
from .qualities import server_router as qualities_server_router
from .questions import server_router as questions_server_router
from .reasoning_levels import server_router as reasoning_levels_server_router
from .request_limits import server_router as request_limits_server_router
from .role_routes import server_router as role_routes_server_router
from .roles import server_router as roles_server_router
from .routes import server_router as routes_server_router
from .rubrics import server_router as rubrics_server_router
from .run_positions import server_router as run_positions_server_router
from .run_rubrics import server_router as run_rubrics_server_router
from .scenario_flags import server_router as scenario_flags_server_router
from .scenario_personas import server_router as scenario_personas_server_router
from .scenario_positions import server_router as scenario_positions_server_router
from .scenario_rubrics import server_router as scenario_rubrics_server_router
from .scenario_time_limits import server_router as scenario_time_limits_server_router
from .scenarios import server_router as scenarios_server_router
from .settings import server_router as settings_server_router
from .simulation_positions import server_router as simulation_positions_server_router
from .simulations import server_router as simulations_server_router
from .slugs import server_router as slugs_server_router
from .standard_groups import server_router as standard_groups_server_router
from .standards import server_router as standards_server_router
from .temperature_levels import server_router as temperature_levels_server_router
from .texts import server_router as texts_server_router
from .thresholds import server_router as thresholds_server_router
from .tools import server_router as tools_server_router
from .uploads import server_router as uploads_server_router
from .values import server_router as values_server_router
from .videos import server_router as videos_server_router
from .voices import server_router as voices_server_router

server_router = APIRouter()

server_router.include_router(agents_server_router)
server_router.include_router(arg_positions_server_router)
server_router.include_router(args_server_router)
server_router.include_router(args_outputs_server_router)
server_router.include_router(auth_item_keys_server_router)
server_router.include_router(auths_server_router)
server_router.include_router(bindings_server_router)
server_router.include_router(cohorts_server_router)
server_router.include_router(colors_server_router)
server_router.include_router(conditional_parameters_server_router)
server_router.include_router(departments_server_router)
server_router.include_router(descriptions_server_router)
server_router.include_router(documents_server_router)
server_router.include_router(domains_server_router)
server_router.include_router(emails_server_router)
server_router.include_router(endpoints_server_router)
server_router.include_router(evals_server_router)
server_router.include_router(examples_server_router)
server_router.include_router(flags_server_router)
server_router.include_router(group_positions_server_router)
server_router.include_router(group_rubrics_server_router)
server_router.include_router(groups_server_router)
server_router.include_router(icons_server_router)
server_router.include_router(images_server_router)
server_router.include_router(instructions_server_router)
server_router.include_router(items_server_router)
server_router.include_router(keys_server_router)
server_router.include_router(modalities_server_router)
server_router.include_router(models_server_router)
server_router.include_router(names_server_router)
server_router.include_router(objectives_server_router)
server_router.include_router(options_server_router)
server_router.include_router(parameter_fields_server_router)
server_router.include_router(parameters_server_router)
server_router.include_router(personas_server_router)
server_router.include_router(points_server_router)
server_router.include_router(pricing_server_router)
server_router.include_router(problem_statements_server_router)
server_router.include_router(profiles_server_router)
server_router.include_router(prompts_server_router)
server_router.include_router(protocols_server_router)
server_router.include_router(provider_keys_server_router)
server_router.include_router(providers_server_router)
server_router.include_router(qualities_server_router)
server_router.include_router(questions_server_router)
server_router.include_router(reasoning_levels_server_router)
server_router.include_router(request_limits_server_router)
server_router.include_router(role_routes_server_router)
server_router.include_router(roles_server_router)
server_router.include_router(routes_server_router)
server_router.include_router(rubrics_server_router)
server_router.include_router(run_positions_server_router)
server_router.include_router(run_rubrics_server_router)
server_router.include_router(scenario_flags_server_router)
server_router.include_router(scenario_personas_server_router)
server_router.include_router(scenario_positions_server_router)
server_router.include_router(scenario_rubrics_server_router)
server_router.include_router(scenario_time_limits_server_router)
server_router.include_router(scenarios_server_router)
server_router.include_router(settings_server_router)
server_router.include_router(simulation_positions_server_router)
server_router.include_router(simulations_server_router)
server_router.include_router(slugs_server_router)
server_router.include_router(standard_groups_server_router)
server_router.include_router(standards_server_router)
server_router.include_router(temperature_levels_server_router)
server_router.include_router(texts_server_router)
server_router.include_router(thresholds_server_router)
server_router.include_router(tools_server_router)
server_router.include_router(uploads_server_router)
server_router.include_router(values_server_router)
server_router.include_router(videos_server_router)
server_router.include_router(voices_server_router)
