-- Materialized view: attempt_replacement_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_replacement_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.attempt_replacement_mv AS
 SELECT r.id AS replacement_id,
    r.improvement_id,
    r.section,
    r.replace AS replace_text,
    r.idx,
    r.created_at
   FROM (((((((public.attempt_replacement_entry r
     JOIN public.attempt_improvement_entry i ON ((i.id = r.improvement_id)))
     JOIN public.attempt_message_entry sm ON ((sm.id = i.message_id)))
     JOIN public.messages_entry m ON ((m.id = sm.id)))
     JOIN public.attempt_chat_entry c ON ((c.id = sm.chat_id)))
     JOIN public.attempt_chat_bridge_entry ac ON ((ac.attempt_chat_id = c.id)))
     JOIN public.attempt_entry a ON ((a.id = ac.attempt_id)))
     LEFT JOIN LATERAL ( SELECT attempt_archive_entry.archived
           FROM public.attempt_archive_entry
          WHERE ((attempt_archive_entry.attempt_id = a.id) AND (attempt_archive_entry.active = true))
          ORDER BY attempt_archive_entry.created_at DESC
         LIMIT 1) sa_archive ON (true))
  WHERE ((r.active = true) AND (i.active = true) AND (m.active = true) AND (c.active = true) AND (a.active = true) AND (COALESCE(sa_archive.archived, false) = false))
  WITH NO DATA;


--
