-- Materialized view: attempt_grade_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_grade_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.attempt_grade_mv AS
 WITH latest_grade AS (
         SELECT DISTINCT ON (g.chat_id) g.id AS grade_id,
            g.chat_id,
            g.score,
            g.passed,
            g.time_taken,
            g.created_at
           FROM public.attempt_grade_entry g
          WHERE (g.active = true)
          ORDER BY g.chat_id, g.created_at DESC
        )
 SELECT lg.grade_id,
    lg.chat_id,
    (lg.score)::double precision AS score,
    lg.passed,
    lg.time_taken,
    r.total_points,
    r.pass_points,
    acrc.rubrics_id AS rubric_id,
    lg.created_at
   FROM (((latest_grade lg
     LEFT JOIN public.attempt_chat_entry ace ON (((ace.id = lg.chat_id) AND (ace.active = true))))
     LEFT JOIN public.attempt_chat_rubrics_connection acrc ON (((acrc.attempt_chat_id = ace.id) AND (acrc.active = true))))
     LEFT JOIN public.rubrics_resource r ON ((r.id = acrc.rubrics_id)))
  WITH NO DATA;


--
