-- Materialized view: attempt_home_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_home_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.attempt_home_mv AS
 SELECT attempt_id,
    home_id,
    created_at,
    active,
    generated,
    mcp,
    session_id
   FROM public.attempt_home_entry
  WHERE (active = true)
  WITH NO DATA;


--
