-- Materialized view: audios_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: audios_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.audios_mv AS
 SELECT ae.id AS audio_id,
    ur.id AS uploads_id,
    ue.file_path,
    ue.mime_type,
    ue.size,
    ae.length_seconds,
    avc.voice_id,
    ae.created_at
   FROM (((((public.audios_entry ae
     JOIN public.audio_uploads_entry aue ON (((aue.audio_id = ae.id) AND (aue.active = true))))
     JOIN public.uploads_entry ue ON (((ue.id = aue.upload_id) AND (ue.active = true))))
     JOIN public.uploads_uploads_connection uuc ON (((uuc.upload_id = ue.id) AND (uuc.active = true))))
     JOIN public.uploads_resource ur ON (((ur.id = uuc.uploads_id) AND (ur.active = true))))
     LEFT JOIN public.audios_voices_connection avc ON (((avc.audio_id = ae.id) AND (avc.active = true))))
  WHERE (ae.active = true)
  WITH NO DATA;


--
