-- Materialized view: certificates_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: certificates_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.certificates_mv AS
 SELECT id,
    created_at,
    generated,
    mcp,
    active,
    upload_id,
    call_id
   FROM public.certificates_entry
  WHERE (active = true)
  WITH NO DATA;


--
