-- Materialized view: chat_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: chat_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.chat_mv AS
 WITH scenario_single AS (
         SELECT DISTINCT ON (tbsc.chat_id) tbsc.chat_id,
            tbsc.scenarios_id AS scenario_id
           FROM public.chat_scenarios_connection tbsc
          WHERE (tbsc.active = true)
          ORDER BY tbsc.chat_id, tbsc.scenarios_id
        ), department_agg AS (
         SELECT tbdc.chat_id,
            array_agg(DISTINCT tbdc.departments_id ORDER BY tbdc.departments_id) AS department_ids
           FROM public.chat_departments_connection tbdc
          WHERE (tbdc.active = true)
          GROUP BY tbdc.chat_id
        ), document_agg AS (
         SELECT tbdc.chat_id,
            array_agg(DISTINCT tbdc.documents_id ORDER BY tbdc.documents_id) AS document_ids
           FROM public.chat_documents_connection tbdc
          WHERE (tbdc.active = true)
          GROUP BY tbdc.chat_id
        ), parameter_field_agg AS (
         SELECT tbpfc.chat_id,
            array_agg(DISTINCT tbpfc.parameter_fields_id ORDER BY tbpfc.parameter_fields_id) AS parameter_field_ids
           FROM public.chat_parameter_fields_connection tbpfc
          WHERE (tbpfc.active = true)
          GROUP BY tbpfc.chat_id
        ), question_agg AS (
         SELECT tbqc.chat_id,
            array_agg(DISTINCT tbqc.questions_id ORDER BY tbqc.questions_id) AS question_ids
           FROM public.chat_questions_connection tbqc
          WHERE (tbqc.active = true)
          GROUP BY tbqc.chat_id
        ), option_agg AS (
         SELECT tboc.chat_id,
            array_agg(DISTINCT tboc.options_id ORDER BY tboc.options_id) AS option_ids
           FROM public.chat_options_connection tboc
          WHERE (tboc.active = true)
          GROUP BY tboc.chat_id
        ), video_agg AS (
         SELECT tbvc.chat_id,
            array_agg(DISTINCT tbvc.videos_id ORDER BY tbvc.videos_id) AS video_ids
           FROM public.chat_videos_connection tbvc
          WHERE (tbvc.active = true)
          GROUP BY tbvc.chat_id
        ), image_agg AS (
         SELECT tbic.chat_id,
            array_agg(DISTINCT tbic.images_id ORDER BY tbic.images_id) AS image_ids
           FROM public.chat_images_connection tbic
          WHERE (tbic.active = true)
          GROUP BY tbic.chat_id
        ), problem_statement_agg AS (
         SELECT tbpsc.chat_id,
            array_agg(DISTINCT tbpsc.problem_statements_id ORDER BY tbpsc.problem_statements_id) AS problem_statement_ids
           FROM public.chat_problem_statements_connection tbpsc
          WHERE (tbpsc.active = true)
          GROUP BY tbpsc.chat_id
        ), objective_agg AS (
         SELECT tboc.chat_id,
            array_agg(DISTINCT tboc.objectives_id ORDER BY tboc.objectives_id) AS objective_ids
           FROM public.chat_objectives_connection tboc
          WHERE (tboc.active = true)
          GROUP BY tboc.chat_id
        ), flag_agg AS (
         SELECT tbfc.chat_id,
            array_agg(DISTINCT tbfc.flags_id ORDER BY tbfc.flags_id) AS flag_ids
           FROM public.chat_flags_connection tbfc
          WHERE (tbfc.active = true)
          GROUP BY tbfc.chat_id
        ), name_agg AS (
         SELECT tbnc.chat_id,
            array_agg(DISTINCT tbnc.names_id ORDER BY tbnc.names_id) AS name_ids
           FROM public.chat_names_connection tbnc
          WHERE (tbnc.active = true)
          GROUP BY tbnc.chat_id
        ), description_agg AS (
         SELECT tbdc.chat_id,
            array_agg(DISTINCT tbdc.descriptions_id ORDER BY tbdc.descriptions_id) AS description_ids
           FROM public.chat_descriptions_connection tbdc
          WHERE (tbdc.active = true)
          GROUP BY tbdc.chat_id
        ), persona_agg AS (
         SELECT tbpc.chat_id,
            array_agg(DISTINCT tbpc.personas_id ORDER BY tbpc.personas_id) AS persona_ids
           FROM public.chat_personas_connection tbpc
          WHERE (tbpc.active = true)
          GROUP BY tbpc.chat_id
        ), rubric_agg AS (
         SELECT tbrc.chat_id,
            array_agg(DISTINCT tbrc.rubrics_id ORDER BY tbrc.rubrics_id) AS rubric_ids
           FROM public.chat_rubrics_connection tbrc
          WHERE (tbrc.active = true)
          GROUP BY tbrc.chat_id
        ), standard_agg AS (
         SELECT tbsc.chat_id,
            array_agg(DISTINCT tbsc.standards_id ORDER BY tbsc.standards_id) AS standard_ids
           FROM public.chat_standards_connection tbsc
          WHERE (tbsc.active = true)
          GROUP BY tbsc.chat_id
        ), standard_group_agg AS (
         SELECT tbsgc.chat_id,
            array_agg(DISTINCT tbsgc.standard_groups_id ORDER BY tbsgc.standard_groups_id) AS standard_group_ids
           FROM public.chat_standard_groups_connection tbsgc
          WHERE (tbsgc.active = true)
          GROUP BY tbsgc.chat_id
        ), flag_pivot AS (
         SELECT ss_1.chat_id,
            COALESCE(bool_or(
                CASE
                    WHEN (fr.type = 'video_enabled'::public.flag_type) THEN sfj.value
                    ELSE NULL::boolean
                END), false) AS video_enabled,
            COALESCE(bool_or(
                CASE
                    WHEN (fr.type = 'problem_statement_enabled'::public.flag_type) THEN sfj.value
                    ELSE NULL::boolean
                END), false) AS problem_statement_enabled,
            COALESCE(bool_or(
                CASE
                    WHEN (fr.type = 'objectives_enabled'::public.flag_type) THEN sfj.value
                    ELSE NULL::boolean
                END), false) AS objectives_enabled,
            COALESCE(bool_or(
                CASE
                    WHEN (fr.type = 'images_enabled'::public.flag_type) THEN sfj.value
                    ELSE NULL::boolean
                END), false) AS images_enabled,
            COALESCE(bool_or(
                CASE
                    WHEN (fr.type = 'questions_enabled'::public.flag_type) THEN sfj.value
                    ELSE NULL::boolean
                END), false) AS questions_enabled
           FROM (((scenario_single ss_1
             JOIN public.scenario_scenarios_junction ssj ON (((ssj.scenarios_id = ss_1.scenario_id) AND (ssj.active = true))))
             JOIN public.scenario_flags_junction sfj ON (((sfj.scenario_id = ssj.scenario_id) AND (sfj.active = true))))
             JOIN public.flags_resource fr ON ((fr.id = sfj.flag_id)))
          WHERE (fr.type = ANY (ARRAY['video_enabled'::public.flag_type, 'problem_statement_enabled'::public.flag_type, 'objectives_enabled'::public.flag_type, 'images_enabled'::public.flag_type, 'questions_enabled'::public.flag_type]))
          GROUP BY ss_1.chat_id
        )
 SELECT tbe.id AS chat_entry_id,
    COALESCE(hte.home_id, pte.practice_id) AS parent_id,
    ss.scenario_id,
    COALESCE(dep.department_ids, ARRAY[]::uuid[]) AS department_ids,
    COALESCE(doc.document_ids, ARRAY[]::uuid[]) AS document_ids,
    COALESCE(pf.parameter_field_ids, ARRAY[]::uuid[]) AS parameter_field_ids,
    COALESCE(que.question_ids, ARRAY[]::uuid[]) AS question_ids,
    COALESCE(opt.option_ids, ARRAY[]::uuid[]) AS option_ids,
    COALESCE(vid.video_ids, ARRAY[]::uuid[]) AS video_ids,
    COALESCE(img.image_ids, ARRAY[]::uuid[]) AS image_ids,
    COALESCE(ps.problem_statement_ids, ARRAY[]::uuid[]) AS problem_statement_ids,
    COALESCE(obj.objective_ids, ARRAY[]::uuid[]) AS objective_ids,
    COALESCE(flg.flag_ids, ARRAY[]::uuid[]) AS flag_ids,
    COALESCE(nm.name_ids, ARRAY[]::uuid[]) AS name_ids,
    COALESCE(dsc.description_ids, ARRAY[]::uuid[]) AS description_ids,
    COALESCE(per.persona_ids, ARRAY[]::uuid[]) AS persona_ids,
    COALESCE(rub.rubric_ids, ARRAY[]::uuid[]) AS rubric_ids,
    COALESCE(std.standard_ids, ARRAY[]::uuid[]) AS standard_ids,
    COALESCE(stg.standard_group_ids, ARRAY[]::uuid[]) AS standard_group_ids,
    COALESCE(fp.video_enabled, false) AS video_enabled,
    COALESCE(fp.problem_statement_enabled, false) AS problem_statement_enabled,
    COALESCE(fp.objectives_enabled, false) AS objectives_enabled,
    COALESCE(fp.images_enabled, false) AS images_enabled,
    COALESCE(fp.questions_enabled, false) AS questions_enabled,
    tbe."position",
    tbe.time_limit,
    tbe.negative_time,
    tbe.name,
    tbe.description,
    tbe.use_custom,
    tbe.use_previous,
    tbe.audio_enabled,
    tbe.text_enabled,
    tbe.hints_enabled,
    tbe.copy_paste_allowed,
    tbe.show_images,
    tbe.show_objectives,
    tbe.show_problem_statement,
    tbe.analyses_enabled,
    tbe.improvements_enabled,
    tbe.replacements_enabled,
    tbe.strengths_enabled,
    tbe.generate_problem_statements,
    tbe.generate_objectives,
    tbe.generate_videos,
    tbe.generate_images,
    tbe.generate_questions,
    tbe.generate_names,
    tbe.generate_descriptions,
    tbe.generate_personas,
    tbe.generate_documents,
    tbe.generate_options,
    tbe.generate_parameter_fields,
    tbe.created_at,
    tbe.updated_at,
    tbe.active
   FROM ((((((((((((((((((((public.chat_entry tbe
     LEFT JOIN public.home_chat_entry hte ON ((hte.chat_id = tbe.id)))
     LEFT JOIN public.practice_chat_entry pte ON ((pte.chat_id = tbe.id)))
     LEFT JOIN scenario_single ss ON ((ss.chat_id = tbe.id)))
     LEFT JOIN department_agg dep ON ((dep.chat_id = tbe.id)))
     LEFT JOIN document_agg doc ON ((doc.chat_id = tbe.id)))
     LEFT JOIN parameter_field_agg pf ON ((pf.chat_id = tbe.id)))
     LEFT JOIN question_agg que ON ((que.chat_id = tbe.id)))
     LEFT JOIN option_agg opt ON ((opt.chat_id = tbe.id)))
     LEFT JOIN video_agg vid ON ((vid.chat_id = tbe.id)))
     LEFT JOIN image_agg img ON ((img.chat_id = tbe.id)))
     LEFT JOIN problem_statement_agg ps ON ((ps.chat_id = tbe.id)))
     LEFT JOIN objective_agg obj ON ((obj.chat_id = tbe.id)))
     LEFT JOIN flag_agg flg ON ((flg.chat_id = tbe.id)))
     LEFT JOIN name_agg nm ON ((nm.chat_id = tbe.id)))
     LEFT JOIN description_agg dsc ON ((dsc.chat_id = tbe.id)))
     LEFT JOIN persona_agg per ON ((per.chat_id = tbe.id)))
     LEFT JOIN rubric_agg rub ON ((rub.chat_id = tbe.id)))
     LEFT JOIN standard_agg std ON ((std.chat_id = tbe.id)))
     LEFT JOIN standard_group_agg stg ON ((stg.chat_id = tbe.id)))
     LEFT JOIN flag_pivot fp ON ((fp.chat_id = tbe.id)))
  WHERE (tbe.active = true)
  WITH NO DATA;


--
