-- Materialized view: conversations_completions_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: conversations_completions_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.conversations_completions_mv AS
 SELECT id,
    created_at,
    generated,
    mcp,
    active,
    conversation_id,
    end_reason,
    call_id
   FROM public.conversations_completions_entry
  WHERE (active = true)
  WITH NO DATA;


--
