-- Materialized view: conversations_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: conversations_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.conversations_mv AS
 SELECT id,
    created_at,
    generated,
    mcp,
    active,
    chat_id,
    run_id,
    call_id
   FROM public.conversations_entry
  WHERE (active = true)
  WITH NO DATA;


--
