-- Materialized view: document_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: document_drafts_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.document_drafts_mv AS
 WITH draft_links AS (
         SELECT document_drafts_departments_connection.draft_id,
            'departments'::text AS resource_type,
            document_drafts_departments_connection.departments_id AS resource_id
           FROM public.document_drafts_departments_connection
          WHERE (document_drafts_departments_connection.active = true)
        UNION ALL
         SELECT document_drafts_descriptions_connection.draft_id,
            'descriptions'::text AS resource_type,
            document_drafts_descriptions_connection.descriptions_id AS resource_id
           FROM public.document_drafts_descriptions_connection
          WHERE (document_drafts_descriptions_connection.active = true)
        UNION ALL
         SELECT document_drafts_documents_connection.draft_id,
            'documents'::text AS resource_type,
            document_drafts_documents_connection.documents_id AS resource_id
           FROM public.document_drafts_documents_connection
          WHERE (document_drafts_documents_connection.active = true)
        UNION ALL
         SELECT document_drafts_flags_connection.draft_id,
            'flags'::text AS resource_type,
            document_drafts_flags_connection.flags_id AS resource_id
           FROM public.document_drafts_flags_connection
          WHERE (document_drafts_flags_connection.active = true)
        UNION ALL
         SELECT document_drafts_images_connection.draft_id,
            'images'::text AS resource_type,
            document_drafts_images_connection.images_id AS resource_id
           FROM public.document_drafts_images_connection
          WHERE (document_drafts_images_connection.active = true)
        UNION ALL
         SELECT document_drafts_names_connection.draft_id,
            'names'::text AS resource_type,
            document_drafts_names_connection.names_id AS resource_id
           FROM public.document_drafts_names_connection
          WHERE (document_drafts_names_connection.active = true)
        UNION ALL
         SELECT document_drafts_parameter_fields_connection.draft_id,
            'parameter_fields'::text AS resource_type,
            document_drafts_parameter_fields_connection.parameter_fields_id AS resource_id
           FROM public.document_drafts_parameter_fields_connection
          WHERE (document_drafts_parameter_fields_connection.active = true)
        UNION ALL
         SELECT document_drafts_parameters_connection.draft_id,
            'parameters'::text AS resource_type,
            document_drafts_parameters_connection.parameters_id AS resource_id
           FROM public.document_drafts_parameters_connection
          WHERE (document_drafts_parameters_connection.active = true)
        UNION ALL
         SELECT document_drafts_texts_connection.draft_id,
            'texts'::text AS resource_type,
            document_drafts_texts_connection.texts_id AS resource_id
           FROM public.document_drafts_texts_connection
          WHERE (document_drafts_texts_connection.active = true)
        UNION ALL
         SELECT document_drafts_uploads_connection.draft_id,
            'uploads'::text AS resource_type,
            document_drafts_uploads_connection.uploads_id AS resource_id
           FROM public.document_drafts_uploads_connection
          WHERE (document_drafts_uploads_connection.active = true)
        )
 SELECT d.id AS draft_id,
    d.created_at,
    d.updated_at,
    d.version,
    d.generated,
    d.mcp,
    d.active,
    d.group_id,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'departments'::text)), ARRAY[]::uuid[]) AS department_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'descriptions'::text)), ARRAY[]::uuid[]) AS description_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'documents'::text)), ARRAY[]::uuid[]) AS document_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'flags'::text)), ARRAY[]::uuid[]) AS flag_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'images'::text)), ARRAY[]::uuid[]) AS image_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'names'::text)), ARRAY[]::uuid[]) AS name_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'parameter_fields'::text)), ARRAY[]::uuid[]) AS parameter_field_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'parameters'::text)), ARRAY[]::uuid[]) AS parameter_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'texts'::text)), ARRAY[]::uuid[]) AS text_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'uploads'::text)), ARRAY[]::uuid[]) AS upload_ids
   FROM (public.document_drafts_entry d
     LEFT JOIN draft_links l ON ((l.draft_id = d.id)))
  GROUP BY d.id, d.created_at, d.updated_at, d.version, d.generated, d.mcp, d.active, d.group_id
  WITH NO DATA;


--
