-- Materialized view: emulations_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: emulations_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.emulations_mv AS
 SELECT id,
    grant_id,
    created_at,
    updated_at,
    session_id
   FROM public.emulations_entry
  WITH NO DATA;


--
