-- Materialized view: field_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: field_drafts_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.field_drafts_mv AS
 SELECT id,
    version,
    created_at,
    generated,
    mcp,
    active,
    group_id,
    session_id
   FROM public.field_drafts_entry
  WHERE (active = true)
  WITH NO DATA;


--
