-- Materialized view: groups_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: groups_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.groups_mv AS
 SELECT id AS group_id,
    session_id,
    created_at AS group_created_at,
    name AS group_name,
    active
   FROM public.groups_entry g
  WHERE (active = true)
  WITH NO DATA;


--
