-- Materialized view: image_completion_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: image_completion_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.image_completion_mv AS
 SELECT id,
    image_id,
    stop,
    error,
    message,
    session_id,
    created_at,
    active,
    generated,
    mcp
   FROM public.image_completion_entry
  WHERE (active = true)
  WITH NO DATA;


--
