-- Materialized view: test_archive_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: test_archive_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.test_archive_mv AS
 SELECT id,
    created_at,
    generated,
    mcp,
    active,
    test_id,
    archived,
    call_id
   FROM public.test_archive_entry
  WHERE (active = true)
  WITH NO DATA;


--
