-- Materialized view: tool_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: tool_drafts_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.tool_drafts_mv AS
 WITH draft_links AS (
         SELECT tool_drafts_arg_positions_connection.draft_id,
            'arg_positions'::text AS resource_type,
            tool_drafts_arg_positions_connection.arg_positions_id AS resource_id
           FROM public.tool_drafts_arg_positions_connection
          WHERE (tool_drafts_arg_positions_connection.active = true)
        UNION ALL
         SELECT tool_drafts_args_connection.draft_id,
            'args'::text AS resource_type,
            tool_drafts_args_connection.args_id AS resource_id
           FROM public.tool_drafts_args_connection
          WHERE (tool_drafts_args_connection.active = true)
        UNION ALL
         SELECT tool_drafts_args_outputs_connection.draft_id,
            'args_outputs'::text AS resource_type,
            tool_drafts_args_outputs_connection.args_outputs_id AS resource_id
           FROM public.tool_drafts_args_outputs_connection
          WHERE (tool_drafts_args_outputs_connection.active = true)
        UNION ALL
         SELECT tool_drafts_entries_connection.draft_id,
            'entries'::text AS resource_type,
            tool_drafts_entries_connection.entries_id AS resource_id
           FROM public.tool_drafts_entries_connection
          WHERE (tool_drafts_entries_connection.active = true)
        UNION ALL
         SELECT tool_drafts_departments_connection.draft_id,
            'departments'::text AS resource_type,
            tool_drafts_departments_connection.departments_id AS resource_id
           FROM public.tool_drafts_departments_connection
          WHERE (tool_drafts_departments_connection.active = true)
        UNION ALL
         SELECT tool_drafts_descriptions_connection.draft_id,
            'descriptions'::text AS resource_type,
            tool_drafts_descriptions_connection.descriptions_id AS resource_id
           FROM public.tool_drafts_descriptions_connection
          WHERE (tool_drafts_descriptions_connection.active = true)
        UNION ALL
         SELECT tool_drafts_resources_connection.draft_id,
            'resources'::text AS resource_type,
            tool_drafts_resources_connection.resources_id AS resource_id
           FROM public.tool_drafts_resources_connection
          WHERE (tool_drafts_resources_connection.active = true)
        UNION ALL
         SELECT tool_drafts_flags_connection.draft_id,
            'flags'::text AS resource_type,
            tool_drafts_flags_connection.flags_id AS resource_id
           FROM public.tool_drafts_flags_connection
          WHERE (tool_drafts_flags_connection.active = true)
        UNION ALL
         SELECT tool_drafts_names_connection.draft_id,
            'names'::text AS resource_type,
            tool_drafts_names_connection.names_id AS resource_id
           FROM public.tool_drafts_names_connection
          WHERE (tool_drafts_names_connection.active = true)
        UNION ALL
         SELECT tool_drafts_tools_connection.draft_id,
            'tools'::text AS resource_type,
            tool_drafts_tools_connection.tools_id AS resource_id
           FROM public.tool_drafts_tools_connection
          WHERE (tool_drafts_tools_connection.active = true)
        )
 SELECT d.id AS draft_id,
    d.created_at,
    d.updated_at,
    d.version,
    d.generated,
    d.mcp,
    d.active,
    d.group_id,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'arg_positions'::text)), ARRAY[]::uuid[]) AS arg_position_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'args'::text)), ARRAY[]::uuid[]) AS args_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'args_outputs'::text)), ARRAY[]::uuid[]) AS args_output_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'entries'::text)), ARRAY[]::uuid[]) AS entry_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'departments'::text)), ARRAY[]::uuid[]) AS department_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'descriptions'::text)), ARRAY[]::uuid[]) AS description_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'resources'::text)), ARRAY[]::uuid[]) AS resource_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'flags'::text)), ARRAY[]::uuid[]) AS flag_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'names'::text)), ARRAY[]::uuid[]) AS name_ids,
    COALESCE(array_agg(DISTINCT l.resource_id) FILTER (WHERE (l.resource_type = 'tools'::text)), ARRAY[]::uuid[]) AS tool_ids
   FROM (public.tool_drafts_entry d
     LEFT JOIN draft_links l ON ((l.draft_id = d.id)))
  GROUP BY d.id, d.created_at, d.updated_at, d.version, d.generated, d.mcp, d.active, d.group_id
  WITH NO DATA;


--
