-- Materialized view: video_uploads_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: video_uploads_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.video_uploads_mv AS
 SELECT id,
    video_id,
    upload_id,
    created_at,
    active,
    generated,
    mcp,
    session_id
   FROM public.video_uploads_entry
  WHERE (active = true)
  WITH NO DATA;


--
