-- Indexes: document_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_documents_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_documents_mcp ON public.document_artifact USING btree (mcp);


--
