-- Indexes: provider_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_provider_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_mcp ON public.provider_artifact USING btree (mcp);


--

-- Name: provider_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX provider_id_idx ON public.provider_artifact USING btree (id);


--
