/**
 * role-icons.ts
 * Lucide icon registry for the Roles component's icon picker.
 *
 * This is the only place that maps icon name strings to Lucide components.
 * All other icon rendering uses inline SVG from the icons_resource API.
 */

import {
  Activity,
  AlarmClock,
  AlertCircle,
  Angry,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  BarChart,
  Battery,
  Bell,
  Bike,
  Bird,
  Bluetooth,
  Book,
  BookOpen,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  Circle,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  Club,
  Cog,
  Columns,
  Compass,
  Computer,
  Copy,
  CreditCard,
  Cross,
  Crown,
  Database,
  Diamond,
  Dice1,
  Dog,
  DollarSign,
  Download,
  Droplet,
  Dumbbell,
  Edit,
  Edit2,
  Edit3,
  Equal,
  Eye,
  EyeOff,
  FastForward,
  File,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flower,
  Folder,
  Frown,
  Gamepad,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Grid,
  Guitar,
  Hash,
  Headphones,
  Heart,
  HeartCrack,
  HeartPulse,
  HelpCircle,
  Hexagon,
  Home,
  Hourglass,
  Image,
  Infinity,
  Info,
  Key,
  Laptop,
  Layers,
  Layout,
  Leaf,
  Lightbulb,
  Link,
  Link2,
  Lock,
  Mail,
  MapPin,
  Medal,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Microscope,
  Minus,
  Monitor,
  Moon,
  Mountain,
  Music,
  Navigation,
  Network,
  Package,
  Paintbrush,
  Palette,
  Pause,
  PawPrint,
  PenTool,
  Percent,
  Phone,
  Piano,
  PieChart,
  PiggyBank,
  Pill,
  Plane,
  Play,
  Plus,
  Power,
  Printer,
  Puzzle,
  Rainbow,
  Rewind,
  Rocket,
  Rows,
  Satellite,
  Save,
  School,
  Scissors,
  Search,
  Server,
  Settings,
  Shield,
  ShieldOff,
  Ship,
  SkipBack,
  SkipForward,
  Smartphone,
  SmilePlus,
  Spade,
  Sparkles,
  Speaker,
  Speech,
  Square,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tablet,
  Target,
  Telescope,
  Timer,
  Train,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UserX,
  Video,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Watch,
  Waves,
  Wifi,
  WifiOff,
  Wrench,
  X,
  XCircle,
  Zap,
} from "lucide-react";

export const ROLE_ICON_MAP = {
  SmilePlus, Frown, Angry, Heart, HeartCrack, Zap, Brain, Target, Award, Crown,
  Star, Sparkles, Flame, Cloud, Sun, Moon, Droplet, MessageSquare, MessageCircle,
  Phone, Mail, Users, User, UserPlus, UserMinus, UserCheck, UserX, Speech, Mic,
  MicOff, Volume, Volume1, Volume2, VolumeX, Headphones, Speaker, Book, BookOpen,
  GraduationCap, School, Lightbulb, Search, Eye, EyeOff, CheckCircle, XCircle,
  AlertCircle, HelpCircle, Info, Briefcase, ClipboardList, Building, Computer,
  Monitor, Laptop, Smartphone, Tablet, Printer, FileText, File, Folder, Archive,
  Clipboard, PenTool, Edit, Edit2, Edit3, Save, Download, Upload, Activity, Play,
  Pause, SkipBack, SkipForward, Rewind, FastForward, Timer, Clock, Calendar,
  MapPin, Navigation, Compass, Globe, Flag, Trophy, Medal, Gift, Settings, Wrench,
  Cog, Database, Server, Network, Wifi, WifiOff, Bluetooth, Battery, Power, Lock,
  Unlock, Shield, ShieldOff, Key, Link, Link2, Palette, Brush, Camera, Video,
  Music, Guitar, Piano, Film, Image, Paintbrush, Scissors, Copy, Layers, Grid,
  Layout, Columns, Rows, Leaf, Flower, Mountain, Waves, Fish, Bird, Cat, Dog,
  PawPrint, Bug, Rainbow, DollarSign, Gauge, CreditCard, Wallet, PiggyBank,
  TrendingUp, TrendingDown, BarChart, PieChart, Calculator, Percent, Hash, AtSign,
  Plus, Minus, Equal, Infinity, HeartPulse, Dumbbell, Bike, Car, Bus, Train,
  Plane, Ship, Rocket, Satellite, Telescope, Microscope, Stethoscope, Pill, Cross,
  Hourglass, Watch, AlarmClock, Bell, Check, X, ArrowUp, ArrowDown, ArrowLeft,
  ArrowRight, ChevronUp, ChevronDown, Home, Store, Package, Box, Circle, Square,
  Triangle, Hexagon, Diamond, Spade, Club, Dice1, Gamepad, Puzzle,
};

export const ROLE_ICON_NAMES = Object.keys(ROLE_ICON_MAP);
