-- Indexes: emulations_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: emulations_entry_grant_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emulations_entry_grant_id_idx ON public.emulations_entry USING btree (grant_id);


--

-- Name: emulations_entry_session_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emulations_entry_session_id_idx ON public.emulations_entry USING btree (session_id);


--
