-- Indexes: health_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: health_service_ts_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX health_service_ts_idx ON public.health_entry USING btree (service, ts);


--

-- Name: idx_health_entry_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_health_entry_session_id ON public.health_entry USING btree (session_id);


--

-- Name: idx_health_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_health_generated ON public.health_entry USING btree (generated);


--

-- Name: idx_health_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_health_mcp ON public.health_entry USING btree (mcp);


--
