-- Indexes: metrics_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_metrics_entry_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metrics_entry_active ON public.metrics_entry USING btree (active);


--

-- Name: idx_metrics_entry_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metrics_entry_created_at ON public.metrics_entry USING btree (created_at);


--

-- Name: idx_metrics_entry_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metrics_entry_generated ON public.metrics_entry USING btree (generated);


--

-- Name: idx_metrics_entry_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metrics_entry_mcp ON public.metrics_entry USING btree (mcp);


--

-- Name: idx_metrics_entry_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metrics_entry_session_id ON public.metrics_entry USING btree (session_id);


--

-- Name: metrics_ts_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX metrics_ts_idx ON public.metrics_entry USING btree (ts);


--
