-- Indexes: mutes_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_mutes_entry_call_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mutes_entry_call_id ON public.mutes_entry USING btree (call_id);


--

-- Name: mutes_entry_conversation_id_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX mutes_entry_conversation_id_created_at_idx ON public.mutes_entry USING btree (conversation_id, created_at DESC);


--

-- Name: mutes_entry_conversation_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX mutes_entry_conversation_id_idx ON public.mutes_entry USING btree (conversation_id);


--

-- Name: mutes_entry_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX mutes_entry_created_at_idx ON public.mutes_entry USING btree (created_at);


--
