-- Indexes: personas_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_personas_entry_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_personas_entry_created_at ON public.personas_entry USING btree (created_at);


--

-- Name: idx_personas_entry_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_personas_entry_session_id ON public.personas_entry USING btree (session_id);


--
