-- Indexes: problems_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: feedback_problems_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feedback_problems_created_at_idx ON public.problems_entry USING btree (created_at);


--

-- Name: feedback_problems_type_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feedback_problems_type_idx ON public.problems_entry USING btree (type);


--

-- Name: idx_feedback_problems_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_feedback_problems_generated ON public.problems_entry USING btree (generated);


--

-- Name: idx_feedback_problems_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_feedback_problems_mcp ON public.problems_entry USING btree (mcp);


--

-- Name: idx_problems_entry_call_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_problems_entry_call_id ON public.problems_entry USING btree (call_id);


--

-- Name: problems_entry_session_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problems_entry_session_id_idx ON public.problems_entry USING btree (session_id);


--
