-- Indexes: reports_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_reports_entry_call_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reports_entry_call_id ON public.reports_entry USING btree (call_id);


--

-- Name: reports_entry_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reports_entry_created_at_idx ON public.reports_entry USING btree (created_at);


--

-- Name: reports_entry_upload_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reports_entry_upload_id_idx ON public.reports_entry USING btree (upload_id);


--
