-- Indexes: scenario_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_scenario_drafts_entry_group_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_entry_group_id ON public.scenario_drafts_entry USING btree (group_id);


--

-- Name: idx_scenario_drafts_entry_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_entry_session_id ON public.scenario_drafts_entry USING btree (session_id);


--
