-- Indexes: sessions_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_sessions_entry_profile_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sessions_entry_profile_active ON public.sessions_entry USING btree (profile_id, active);


--

-- Name: idx_sessions_entry_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sessions_entry_session_id ON public.sessions_entry USING btree (session_id);


--

-- Name: sessions_entry_profile_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sessions_entry_profile_id_idx ON public.sessions_entry USING btree (profile_id);


--
