-- Indexes: upload_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_upload_completion_entry_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_upload_completion_entry_created_at ON public.upload_completion_entry USING btree (created_at);


--

-- Name: idx_upload_completion_entry_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_upload_completion_entry_session_id ON public.upload_completion_entry USING btree (session_id);


--

-- Name: idx_upload_completion_entry_upload_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_upload_completion_entry_upload_id ON public.upload_completion_entry USING btree (upload_id);


--
