-- Table definitions + constraints: parameter_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: parameter_departments_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_departments_junction (
    active boolean DEFAULT true CONSTRAINT parameter_departments_active_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT parameter_departments_created_at_not_null NOT NULL,
    departments_id uuid CONSTRAINT parameter_departments_department_id_not_null NOT NULL,
    parameter_id uuid CONSTRAINT parameter_departments_parameter_id_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT parameter_departments_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT parameter_departments_mcp_not_null NOT NULL
);


--

-- Name: parameter_descriptions_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_descriptions_junction (
    parameter_id uuid CONSTRAINT parameter_descriptions_parameter_id_not_null NOT NULL,
    descriptions_id uuid CONSTRAINT parameter_descriptions_description_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT parameter_descriptions_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT parameter_descriptions_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT parameter_descriptions_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT parameter_descriptions_active_not_null NOT NULL
);


--

-- Name: parameter_fields_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_fields_junction (
    parameter_id uuid CONSTRAINT parameter_fields_parameter_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT parameter_fields_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT parameter_fields_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT parameter_fields_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT parameter_fields_active_not_null NOT NULL,
    fields_id uuid CONSTRAINT parameter_fields_field_resource_id_not_null NOT NULL
);


--

-- Name: parameter_flags_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_flags_junction (
    parameter_id uuid CONSTRAINT parameter_flags_parameter_id_not_null NOT NULL,
    flags_id uuid CONSTRAINT parameter_flags_flag_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT parameter_flags_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT parameter_flags_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT parameter_flags_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT parameter_flags_active_not_null NOT NULL
);


--

-- Name: parameter_names_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_names_junction (
    parameter_id uuid CONSTRAINT parameter_names_parameter_id_not_null NOT NULL,
    names_id uuid CONSTRAINT parameter_names_name_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT parameter_names_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT parameter_names_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT parameter_names_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT parameter_names_active_not_null NOT NULL
);


--

-- Name: parameter_parameters_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parameter_parameters_junction (
    parameter_id uuid NOT NULL,
    parameters_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: parameter_departments_junction parameter_departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_departments_junction
    ADD CONSTRAINT parameter_departments_pkey PRIMARY KEY (parameter_id, departments_id);


--

-- Name: parameter_descriptions_junction parameter_descriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_descriptions_junction
    ADD CONSTRAINT parameter_descriptions_pkey PRIMARY KEY (parameter_id, descriptions_id);


--

-- Name: parameter_fields_junction parameter_fields_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_fields_junction
    ADD CONSTRAINT parameter_fields_pkey PRIMARY KEY (parameter_id, fields_id);


--

-- Name: parameter_flags_junction parameter_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_flags_junction
    ADD CONSTRAINT parameter_flags_pkey PRIMARY KEY (parameter_id, flags_id);


--

-- Name: parameter_names_junction parameter_names_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_names_junction
    ADD CONSTRAINT parameter_names_pkey PRIMARY KEY (parameter_id, names_id);


--

-- Name: parameter_parameters_junction parameter_parameters_junction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_parameters_junction
    ADD CONSTRAINT parameter_parameters_junction_pkey PRIMARY KEY (parameter_id, parameters_id);


--
