-- Table definitions + constraints: provider_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: provider_departments_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_departments_junction (
    provider_id uuid CONSTRAINT provider_departments_provider_id_not_null NOT NULL,
    department_id uuid CONSTRAINT provider_departments_department_id_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT provider_departments_active_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT provider_departments_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT provider_departments_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT provider_departments_mcp_not_null NOT NULL
);


--

-- Name: provider_descriptions_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_descriptions_junction (
    provider_id uuid CONSTRAINT provider_descriptions_provider_id_not_null NOT NULL,
    description_id uuid CONSTRAINT provider_descriptions_description_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT provider_descriptions_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT provider_descriptions_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT provider_descriptions_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT provider_descriptions_active_not_null NOT NULL
);


--

-- Name: provider_endpoints_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_endpoints_junction (
    provider_id uuid NOT NULL,
    endpoint_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: provider_flags_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_flags_junction (
    provider_id uuid CONSTRAINT provider_flags_provider_id_not_null NOT NULL,
    flag_id uuid CONSTRAINT provider_flags_flag_id_not_null NOT NULL,
    value boolean CONSTRAINT provider_flags_value_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT provider_flags_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT provider_flags_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT provider_flags_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT provider_flags_active_not_null NOT NULL
);


--

-- Name: provider_keys_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_keys_junction (
    provider_id uuid NOT NULL,
    key_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: provider_names_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_names_junction (
    provider_id uuid CONSTRAINT provider_names_provider_id_not_null NOT NULL,
    name_id uuid CONSTRAINT provider_names_name_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT provider_names_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT provider_names_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT provider_names_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT provider_names_active_not_null NOT NULL
);


--

-- Name: provider_providers_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_providers_junction (
    provider_id uuid NOT NULL,
    providers_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: provider_values_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_values_junction (
    provider_id uuid CONSTRAINT provider_values_provider_id_not_null NOT NULL,
    values_id uuid CONSTRAINT provider_values_values_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT provider_values_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT provider_values_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT provider_values_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT provider_values_mcp_not_null NOT NULL
);


--

-- Name: provider_departments_junction provider_departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_departments_junction
    ADD CONSTRAINT provider_departments_pkey PRIMARY KEY (provider_id, department_id);


--

-- Name: provider_descriptions_junction provider_descriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_descriptions_junction
    ADD CONSTRAINT provider_descriptions_pkey PRIMARY KEY (provider_id, description_id);


--

-- Name: provider_endpoints_junction provider_endpoints_junction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_endpoints_junction
    ADD CONSTRAINT provider_endpoints_junction_pkey PRIMARY KEY (provider_id, endpoint_id);


--

-- Name: provider_flags_junction provider_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_flags_junction
    ADD CONSTRAINT provider_flags_pkey PRIMARY KEY (provider_id, flag_id);


--

-- Name: provider_keys_junction provider_keys_junction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_keys_junction
    ADD CONSTRAINT provider_keys_junction_pkey PRIMARY KEY (provider_id, key_id);


--

-- Name: provider_names_junction provider_names_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_names_junction
    ADD CONSTRAINT provider_names_pkey PRIMARY KEY (provider_id, name_id);


--

-- Name: provider_providers_junction provider_providers_junction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_providers_junction
    ADD CONSTRAINT provider_providers_junction_pkey PRIMARY KEY (provider_id, providers_id);


--

-- Name: provider_values_junction provider_values_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_values_junction
    ADD CONSTRAINT provider_values_pkey PRIMARY KEY (provider_id, values_id);


--
