-- Enum: message_type
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: message_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.message_type AS ENUM (
    'user',
    'assistant',
    'system',
    'developer'
);


--
