-- Enum: profile_type
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: profile_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.profile_type AS ENUM (
    'superadmin',
    'admin',
    'instructional',
    'member',
    'guest',
    'custom'
);


--
