-- Enum: reasoning_type
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: reasoning_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.reasoning_type AS ENUM (
    'minimal',
    'low',
    'medium',
    'high',
    'none'
);


--
