-- Enum: schema_type
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: schema_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.schema_type AS ENUM (
    'string',
    'number',
    'boolean',
    'array'
);


--
