-- Enum: simulation_message_type
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: simulation_message_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.simulation_message_type AS ENUM (
    'query',
    'response'
);


--
