-- Foreign keys: agent_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: agent_drafts_agents_connection agent_drafts_agents_connection_agents_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_agents_connection
    ADD CONSTRAINT agent_drafts_agents_connection_agents_id_fkey FOREIGN KEY (agents_id) REFERENCES public.agents_resource(id);


--

-- Name: agent_drafts_agents_connection agent_drafts_agents_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_agents_connection
    ADD CONSTRAINT agent_drafts_agents_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_departments_connection agent_drafts_departments_connection_departments_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_departments_connection
    ADD CONSTRAINT agent_drafts_departments_connection_departments_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id);


--

-- Name: agent_drafts_departments_connection agent_drafts_departments_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_departments_connection
    ADD CONSTRAINT agent_drafts_departments_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_descriptions_connection agent_drafts_descriptions_connection_descriptions_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_descriptions_connection
    ADD CONSTRAINT agent_drafts_descriptions_connection_descriptions_id_fkey FOREIGN KEY (descriptions_id) REFERENCES public.descriptions_resource(id);


--

-- Name: agent_drafts_descriptions_connection agent_drafts_descriptions_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_descriptions_connection
    ADD CONSTRAINT agent_drafts_descriptions_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_flags_connection agent_drafts_flags_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_flags_connection
    ADD CONSTRAINT agent_drafts_flags_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_flags_connection agent_drafts_flags_connection_flags_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_flags_connection
    ADD CONSTRAINT agent_drafts_flags_connection_flags_id_fkey FOREIGN KEY (flags_id) REFERENCES public.flags_resource(id);


--

-- Name: agent_drafts_models_connection agent_drafts_models_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_models_connection
    ADD CONSTRAINT agent_drafts_models_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_models_connection agent_drafts_models_connection_models_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_models_connection
    ADD CONSTRAINT agent_drafts_models_connection_models_id_fkey FOREIGN KEY (models_id) REFERENCES public.models_resource(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_names_connection agent_drafts_names_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_names_connection
    ADD CONSTRAINT agent_drafts_names_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_names_connection agent_drafts_names_connection_names_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_names_connection
    ADD CONSTRAINT agent_drafts_names_connection_names_id_fkey FOREIGN KEY (names_id) REFERENCES public.names_resource(id);


--

-- Name: agent_drafts_profiles_connection agent_drafts_profiles_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_profiles_connection
    ADD CONSTRAINT agent_drafts_profiles_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_profiles_connection agent_drafts_profiles_connection_profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_profiles_connection
    ADD CONSTRAINT agent_drafts_profiles_connection_profiles_id_fkey FOREIGN KEY (profiles_id) REFERENCES public.profiles_resource(id);


--

-- Name: agent_drafts_reasoning_levels_connection agent_drafts_reasoning_levels_connecti_reasoning_levels_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_reasoning_levels_connection
    ADD CONSTRAINT agent_drafts_reasoning_levels_connecti_reasoning_levels_id_fkey FOREIGN KEY (reasoning_levels_id) REFERENCES public.reasoning_levels_resource(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_reasoning_levels_connection agent_drafts_reasoning_levels_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_reasoning_levels_connection
    ADD CONSTRAINT agent_drafts_reasoning_levels_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_temperature_levels_connection agent_drafts_temperature_levels_conn_temperature_levels_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_temperature_levels_connection
    ADD CONSTRAINT agent_drafts_temperature_levels_conn_temperature_levels_id_fkey FOREIGN KEY (temperature_levels_id) REFERENCES public.temperature_levels_resource(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_temperature_levels_connection agent_drafts_temperature_levels_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_temperature_levels_connection
    ADD CONSTRAINT agent_drafts_temperature_levels_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_tools_connection agent_drafts_tools_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_tools_connection
    ADD CONSTRAINT agent_drafts_tools_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_tools_connection agent_drafts_tools_connection_tools_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_tools_connection
    ADD CONSTRAINT agent_drafts_tools_connection_tools_id_fkey FOREIGN KEY (tools_id) REFERENCES public.tools_resource(id);


--

-- Name: agent_drafts_voices_connection agent_drafts_voices_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_voices_connection
    ADD CONSTRAINT agent_drafts_voices_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.agent_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: agent_drafts_voices_connection agent_drafts_voices_connection_voices_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_drafts_voices_connection
    ADD CONSTRAINT agent_drafts_voices_connection_voices_id_fkey FOREIGN KEY (voices_id) REFERENCES public.voices_resource(id) ON DELETE CASCADE;


--
