-- Foreign keys: agents_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: agents_calls_connection agents_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agents_calls_connection
    ADD CONSTRAINT agents_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: agents_calls_connection agents_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agents_calls_connection
    ADD CONSTRAINT agents_calls_connection_id_fkey FOREIGN KEY (agents_id) REFERENCES public.agents_resource(id) ON DELETE CASCADE;


--
