-- Foreign keys: colors_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: colors_calls_connection colors_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.colors_calls_connection
    ADD CONSTRAINT colors_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: colors_calls_connection colors_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.colors_calls_connection
    ADD CONSTRAINT colors_calls_connection_id_fkey FOREIGN KEY (colors_id) REFERENCES public.colors_resource(id) ON DELETE CASCADE;


--
