-- Foreign keys: documents_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: documents_calls_connection documents_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents_calls_connection
    ADD CONSTRAINT documents_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: documents_calls_connection documents_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents_calls_connection
    ADD CONSTRAINT documents_calls_connection_id_fkey FOREIGN KEY (documents_id) REFERENCES public.documents_resource(id) ON DELETE CASCADE;


--
