-- Foreign keys: flags_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: flags_calls_connection flags_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flags_calls_connection
    ADD CONSTRAINT flags_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: flags_calls_connection flags_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flags_calls_connection
    ADD CONSTRAINT flags_calls_connection_id_fkey FOREIGN KEY (flags_id) REFERENCES public.flags_resource(id) ON DELETE CASCADE;


--
