-- Foreign keys: groups_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: groups_calls_connection groups_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups_calls_connection
    ADD CONSTRAINT groups_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: groups_calls_connection groups_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups_calls_connection
    ADD CONSTRAINT groups_calls_connection_id_fkey FOREIGN KEY (groups_id) REFERENCES public.groups_resource(id) ON DELETE CASCADE;


--

-- Name: groups_groups_connection groups_groups_connection_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups_groups_connection
    ADD CONSTRAINT groups_groups_connection_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups_entry(id) ON DELETE CASCADE;


--

-- Name: groups_groups_connection groups_groups_connection_groups_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups_groups_connection
    ADD CONSTRAINT groups_groups_connection_groups_id_fkey FOREIGN KEY (groups_id) REFERENCES public.groups_resource(id) ON DELETE CASCADE;


--
