-- Foreign keys: icons_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: icons_calls_connection icons_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.icons_calls_connection
    ADD CONSTRAINT icons_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: icons_calls_connection icons_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.icons_calls_connection
    ADD CONSTRAINT icons_calls_connection_id_fkey FOREIGN KEY (icons_id) REFERENCES public.icons_resource(id) ON DELETE CASCADE;


--
