-- Foreign keys: objectives_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: objectives_calls_connection objectives_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objectives_calls_connection
    ADD CONSTRAINT objectives_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: objectives_calls_connection objectives_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objectives_calls_connection
    ADD CONSTRAINT objectives_calls_connection_id_fkey FOREIGN KEY (objectives_id) REFERENCES public.objectives_resource(id) ON DELETE CASCADE;


--
