-- Foreign keys: points_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: points_calls_connection points_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_calls_connection
    ADD CONSTRAINT points_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: points_calls_connection points_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_calls_connection
    ADD CONSTRAINT points_calls_connection_id_fkey FOREIGN KEY (points_id) REFERENCES public.points_resource(id) ON DELETE CASCADE;


--
