-- Foreign keys: profile_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: profile_drafts_departments_connection profile_drafts_departments_connection_departments_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_departments_connection
    ADD CONSTRAINT profile_drafts_departments_connection_departments_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id);


--

-- Name: profile_drafts_departments_connection profile_drafts_departments_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_departments_connection
    ADD CONSTRAINT profile_drafts_departments_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.profile_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: profile_drafts_emails_connection profile_drafts_emails_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_emails_connection
    ADD CONSTRAINT profile_drafts_emails_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.profile_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: profile_drafts_emails_connection profile_drafts_emails_connection_emails_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_emails_connection
    ADD CONSTRAINT profile_drafts_emails_connection_emails_id_fkey FOREIGN KEY (emails_id) REFERENCES public.emails_resource(id);


--

-- Name: profile_drafts_flags_connection profile_drafts_flags_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_flags_connection
    ADD CONSTRAINT profile_drafts_flags_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.profile_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: profile_drafts_flags_connection profile_drafts_flags_connection_flags_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_flags_connection
    ADD CONSTRAINT profile_drafts_flags_connection_flags_id_fkey FOREIGN KEY (flags_id) REFERENCES public.flags_resource(id);


--

-- Name: profile_drafts_names_connection profile_drafts_names_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_names_connection
    ADD CONSTRAINT profile_drafts_names_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.profile_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: profile_drafts_names_connection profile_drafts_names_connection_names_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_names_connection
    ADD CONSTRAINT profile_drafts_names_connection_names_id_fkey FOREIGN KEY (names_id) REFERENCES public.names_resource(id);


--

-- Name: profile_drafts_request_limits_connection profile_drafts_request_limits_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_request_limits_connection
    ADD CONSTRAINT profile_drafts_request_limits_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.profile_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: profile_drafts_request_limits_connection profile_drafts_request_limits_connection_request_limits_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_request_limits_connection
    ADD CONSTRAINT profile_drafts_request_limits_connection_request_limits_id_fkey FOREIGN KEY (request_limits_id) REFERENCES public.request_limits_resource(id);


--

-- Name: profile_drafts_roles_connection profile_drafts_roles_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_roles_connection
    ADD CONSTRAINT profile_drafts_roles_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.profile_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: profile_drafts_roles_connection profile_drafts_roles_connection_roles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_drafts_roles_connection
    ADD CONSTRAINT profile_drafts_roles_connection_roles_id_fkey FOREIGN KEY (roles_id) REFERENCES public.roles_resource(id);


--

-- Name: profile_personas_calls_connection profile_personas_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_personas_calls_connection
    ADD CONSTRAINT profile_personas_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: profile_personas_calls_connection profile_personas_calls_connection_profile_personas_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_personas_calls_connection
    ADD CONSTRAINT profile_personas_calls_connection_profile_personas_id_fkey FOREIGN KEY (profile_personas_id) REFERENCES public.profile_personas_resource(id) ON DELETE CASCADE;


--
