-- Foreign keys: scenario_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: scenario_drafts_departments_connection scenario_drafts_departments_connection_departments_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_departments_connection
    ADD CONSTRAINT scenario_drafts_departments_connection_departments_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id);


--

-- Name: scenario_drafts_departments_connection scenario_drafts_departments_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_departments_connection
    ADD CONSTRAINT scenario_drafts_departments_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_descriptions_connection scenario_drafts_descriptions_connection_descriptions_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_descriptions_connection
    ADD CONSTRAINT scenario_drafts_descriptions_connection_descriptions_id_fkey FOREIGN KEY (descriptions_id) REFERENCES public.descriptions_resource(id);


--

-- Name: scenario_drafts_descriptions_connection scenario_drafts_descriptions_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_descriptions_connection
    ADD CONSTRAINT scenario_drafts_descriptions_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_documents_connection scenario_drafts_documents_connection_documents_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_documents_connection
    ADD CONSTRAINT scenario_drafts_documents_connection_documents_id_fkey FOREIGN KEY (documents_id) REFERENCES public.documents_resource(id);


--

-- Name: scenario_drafts_documents_connection scenario_drafts_documents_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_documents_connection
    ADD CONSTRAINT scenario_drafts_documents_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_flags_connection scenario_drafts_flags_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_flags_connection
    ADD CONSTRAINT scenario_drafts_flags_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_flags_connection scenario_drafts_flags_connection_flags_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_flags_connection
    ADD CONSTRAINT scenario_drafts_flags_connection_flags_id_fkey FOREIGN KEY (flags_id) REFERENCES public.flags_resource(id);


--

-- Name: scenario_drafts_images_connection scenario_drafts_images_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_images_connection
    ADD CONSTRAINT scenario_drafts_images_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_images_connection scenario_drafts_images_connection_images_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_images_connection
    ADD CONSTRAINT scenario_drafts_images_connection_images_id_fkey FOREIGN KEY (images_id) REFERENCES public.images_resource(id);


--

-- Name: scenario_drafts_names_connection scenario_drafts_names_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_names_connection
    ADD CONSTRAINT scenario_drafts_names_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_names_connection scenario_drafts_names_connection_names_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_names_connection
    ADD CONSTRAINT scenario_drafts_names_connection_names_id_fkey FOREIGN KEY (names_id) REFERENCES public.names_resource(id);


--

-- Name: scenario_drafts_objectives_connection scenario_drafts_objectives_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_objectives_connection
    ADD CONSTRAINT scenario_drafts_objectives_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_objectives_connection scenario_drafts_objectives_connection_objectives_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_objectives_connection
    ADD CONSTRAINT scenario_drafts_objectives_connection_objectives_id_fkey FOREIGN KEY (objectives_id) REFERENCES public.objectives_resource(id);


--

-- Name: scenario_drafts_options_connection scenario_drafts_options_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_options_connection
    ADD CONSTRAINT scenario_drafts_options_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_options_connection scenario_drafts_options_connection_options_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_options_connection
    ADD CONSTRAINT scenario_drafts_options_connection_options_id_fkey FOREIGN KEY (options_id) REFERENCES public.options_resource(id);


--

-- Name: scenario_drafts_parameter_fields_connection scenario_drafts_parameter_fields_conne_parameter_fields_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_parameter_fields_connection
    ADD CONSTRAINT scenario_drafts_parameter_fields_conne_parameter_fields_id_fkey FOREIGN KEY (parameter_fields_id) REFERENCES public.parameter_fields_resource(id);


--

-- Name: scenario_drafts_parameter_fields_connection scenario_drafts_parameter_fields_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_parameter_fields_connection
    ADD CONSTRAINT scenario_drafts_parameter_fields_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_personas_connection scenario_drafts_personas_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_personas_connection
    ADD CONSTRAINT scenario_drafts_personas_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_personas_connection scenario_drafts_personas_connection_personas_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_personas_connection
    ADD CONSTRAINT scenario_drafts_personas_connection_personas_id_fkey FOREIGN KEY (personas_id) REFERENCES public.personas_resource(id);


--

-- Name: scenario_drafts_problem_statements_connection scenario_drafts_problem_statements_c_problem_statements_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_problem_statements_connection
    ADD CONSTRAINT scenario_drafts_problem_statements_c_problem_statements_id_fkey FOREIGN KEY (problem_statements_id) REFERENCES public.problem_statements_resource(id);


--

-- Name: scenario_drafts_problem_statements_connection scenario_drafts_problem_statements_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_problem_statements_connection
    ADD CONSTRAINT scenario_drafts_problem_statements_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_profiles_connection scenario_drafts_profiles_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_profiles_connection
    ADD CONSTRAINT scenario_drafts_profiles_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_profiles_connection scenario_drafts_profiles_connection_profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_profiles_connection
    ADD CONSTRAINT scenario_drafts_profiles_connection_profiles_id_fkey FOREIGN KEY (profiles_id) REFERENCES public.profiles_resource(id);


--

-- Name: scenario_drafts_questions_connection scenario_drafts_questions_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_questions_connection
    ADD CONSTRAINT scenario_drafts_questions_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_questions_connection scenario_drafts_questions_connection_questions_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_questions_connection
    ADD CONSTRAINT scenario_drafts_questions_connection_questions_id_fkey FOREIGN KEY (questions_id) REFERENCES public.questions_resource(id);


--

-- Name: scenario_drafts_scenarios_connection scenario_drafts_scenarios_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_scenarios_connection
    ADD CONSTRAINT scenario_drafts_scenarios_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_scenarios_connection scenario_drafts_scenarios_connection_scenarios_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_scenarios_connection
    ADD CONSTRAINT scenario_drafts_scenarios_connection_scenarios_id_fkey FOREIGN KEY (scenarios_id) REFERENCES public.scenarios_resource(id);


--

-- Name: scenario_drafts_videos_connection scenario_drafts_videos_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_videos_connection
    ADD CONSTRAINT scenario_drafts_videos_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.scenario_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_drafts_videos_connection scenario_drafts_videos_connection_videos_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_drafts_videos_connection
    ADD CONSTRAINT scenario_drafts_videos_connection_videos_id_fkey FOREIGN KEY (videos_id) REFERENCES public.videos_resource(id);


--

-- Name: scenario_flags_calls_connection scenario_flags_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_flags_calls_connection
    ADD CONSTRAINT scenario_flags_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_flags_calls_connection scenario_flags_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_flags_calls_connection
    ADD CONSTRAINT scenario_flags_calls_connection_id_fkey FOREIGN KEY (scenario_flags_id) REFERENCES public.scenario_flags_resource(id) ON DELETE CASCADE;


--

-- Name: scenario_positions_calls_connection scenario_positions_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_positions_calls_connection
    ADD CONSTRAINT scenario_positions_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_positions_calls_connection scenario_positions_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_positions_calls_connection
    ADD CONSTRAINT scenario_positions_calls_connection_id_fkey FOREIGN KEY (scenario_positions_id) REFERENCES public.scenario_positions_resource(id) ON DELETE CASCADE;


--

-- Name: scenario_rubrics_calls_connection scenario_rubrics_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_rubrics_calls_connection
    ADD CONSTRAINT scenario_rubrics_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_rubrics_calls_connection scenario_rubrics_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_rubrics_calls_connection
    ADD CONSTRAINT scenario_rubrics_calls_connection_id_fkey FOREIGN KEY (scenario_rubrics_id) REFERENCES public.scenario_rubrics_resource(id) ON DELETE CASCADE;


--

-- Name: scenario_time_limits_calls_connection scenario_time_limits_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_time_limits_calls_connection
    ADD CONSTRAINT scenario_time_limits_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: scenario_time_limits_calls_connection scenario_time_limits_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario_time_limits_calls_connection
    ADD CONSTRAINT scenario_time_limits_calls_connection_id_fkey FOREIGN KEY (scenario_time_limits_id) REFERENCES public.scenario_time_limits_resource(id) ON DELETE CASCADE;


--
