-- Foreign keys: settings_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: settings_calls_connection settings_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings_calls_connection
    ADD CONSTRAINT settings_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: settings_calls_connection settings_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings_calls_connection
    ADD CONSTRAINT settings_calls_connection_id_fkey FOREIGN KEY (settings_id) REFERENCES public.settings_resource(id) ON DELETE CASCADE;


--
