-- Foreign keys: simulation_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: simulation_availability_calls_connection simulation_availability_calls_c_simulation_availability_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_availability_calls_connection
    ADD CONSTRAINT simulation_availability_calls_c_simulation_availability_id_fkey FOREIGN KEY (simulation_availability_id) REFERENCES public.simulation_availability_resource(id) ON DELETE CASCADE;


--

-- Name: simulation_availability_calls_connection simulation_availability_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_availability_calls_connection
    ADD CONSTRAINT simulation_availability_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_departments_connection simulation_drafts_departments_connection_departments_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_departments_connection
    ADD CONSTRAINT simulation_drafts_departments_connection_departments_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id);


--

-- Name: simulation_drafts_departments_connection simulation_drafts_departments_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_departments_connection
    ADD CONSTRAINT simulation_drafts_departments_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_descriptions_connection simulation_drafts_descriptions_connection_descriptions_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_descriptions_connection
    ADD CONSTRAINT simulation_drafts_descriptions_connection_descriptions_id_fkey FOREIGN KEY (descriptions_id) REFERENCES public.descriptions_resource(id);


--

-- Name: simulation_drafts_descriptions_connection simulation_drafts_descriptions_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_descriptions_connection
    ADD CONSTRAINT simulation_drafts_descriptions_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_flags_connection simulation_drafts_flags_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_flags_connection
    ADD CONSTRAINT simulation_drafts_flags_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_flags_connection simulation_drafts_flags_connection_flags_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_flags_connection
    ADD CONSTRAINT simulation_drafts_flags_connection_flags_id_fkey FOREIGN KEY (flags_id) REFERENCES public.flags_resource(id);


--

-- Name: simulation_drafts_names_connection simulation_drafts_names_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_names_connection
    ADD CONSTRAINT simulation_drafts_names_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_names_connection simulation_drafts_names_connection_names_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_names_connection
    ADD CONSTRAINT simulation_drafts_names_connection_names_id_fkey FOREIGN KEY (names_id) REFERENCES public.names_resource(id);


--

-- Name: simulation_drafts_profiles_connection simulation_drafts_profiles_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_profiles_connection
    ADD CONSTRAINT simulation_drafts_profiles_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_profiles_connection simulation_drafts_profiles_connection_profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_profiles_connection
    ADD CONSTRAINT simulation_drafts_profiles_connection_profiles_id_fkey FOREIGN KEY (profiles_id) REFERENCES public.profiles_resource(id);


--

-- Name: simulation_drafts_scenario_flags_connection simulation_drafts_scenario_flags_connect_scenario_flags_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenario_flags_connection
    ADD CONSTRAINT simulation_drafts_scenario_flags_connect_scenario_flags_id_fkey FOREIGN KEY (scenario_flags_id) REFERENCES public.scenario_flags_resource(id);


--

-- Name: simulation_drafts_scenario_flags_connection simulation_drafts_scenario_flags_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenario_flags_connection
    ADD CONSTRAINT simulation_drafts_scenario_flags_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_scenario_positions_connection simulation_drafts_scenario_positions_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenario_positions_connection
    ADD CONSTRAINT simulation_drafts_scenario_positions_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_scenario_positions_connection simulation_drafts_scenario_positions_scenario_positions_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenario_positions_connection
    ADD CONSTRAINT simulation_drafts_scenario_positions_scenario_positions_id_fkey FOREIGN KEY (scenario_positions_id) REFERENCES public.scenario_positions_resource(id);


--

-- Name: simulation_drafts_scenario_rubrics_connection simulation_drafts_scenario_rubrics_con_scenario_rubrics_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenario_rubrics_connection
    ADD CONSTRAINT simulation_drafts_scenario_rubrics_con_scenario_rubrics_id_fkey FOREIGN KEY (scenario_rubrics_id) REFERENCES public.scenario_rubrics_resource(id);


--

-- Name: simulation_drafts_scenario_rubrics_connection simulation_drafts_scenario_rubrics_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenario_rubrics_connection
    ADD CONSTRAINT simulation_drafts_scenario_rubrics_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_scenario_time_limits_connection simulation_drafts_scenario_time_li_scenario_time_limits_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenario_time_limits_connection
    ADD CONSTRAINT simulation_drafts_scenario_time_li_scenario_time_limits_id_fkey FOREIGN KEY (scenario_time_limits_id) REFERENCES public.scenario_time_limits_resource(id);


--

-- Name: simulation_drafts_scenario_time_limits_connection simulation_drafts_scenario_time_limits_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenario_time_limits_connection
    ADD CONSTRAINT simulation_drafts_scenario_time_limits_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_scenarios_connection simulation_drafts_scenarios_connection_draft_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenarios_connection
    ADD CONSTRAINT simulation_drafts_scenarios_connection_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.simulation_drafts_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_drafts_scenarios_connection simulation_drafts_scenarios_connection_scenarios_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_drafts_scenarios_connection
    ADD CONSTRAINT simulation_drafts_scenarios_connection_scenarios_id_fkey FOREIGN KEY (scenarios_id) REFERENCES public.scenarios_resource(id);


--

-- Name: simulation_positions_calls_connection simulation_positions_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_positions_calls_connection
    ADD CONSTRAINT simulation_positions_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: simulation_positions_calls_connection simulation_positions_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation_positions_calls_connection
    ADD CONSTRAINT simulation_positions_calls_connection_id_fkey FOREIGN KEY (simulation_positions_id) REFERENCES public.simulation_positions_resource(id) ON DELETE CASCADE;


--
