-- Foreign keys: simulations_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: simulations_calls_connection simulations_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulations_calls_connection
    ADD CONSTRAINT simulations_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: simulations_calls_connection simulations_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulations_calls_connection
    ADD CONSTRAINT simulations_calls_connection_id_fkey FOREIGN KEY (simulations_id) REFERENCES public.simulations_resource(id) ON DELETE CASCADE;


--
