-- Foreign keys: test_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: test_departments_connection benchmark_attempts_departments_connection_attempt_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_departments_connection
    ADD CONSTRAINT benchmark_attempts_departments_connection_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES public.test_entry(id) ON DELETE CASCADE;


--

-- Name: test_departments_connection benchmark_attempts_departments_connection_departments_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_departments_connection
    ADD CONSTRAINT benchmark_attempts_departments_connection_departments_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id);


--

-- Name: test_evals_connection benchmark_attempts_evals_connection_attempt_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_evals_connection
    ADD CONSTRAINT benchmark_attempts_evals_connection_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES public.test_entry(id) ON DELETE CASCADE;


--

-- Name: test_evals_connection benchmark_attempts_evals_connection_evals_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_evals_connection
    ADD CONSTRAINT benchmark_attempts_evals_connection_evals_id_fkey FOREIGN KEY (evals_id) REFERENCES public.evals_resource(id);


--

-- Name: test_profiles_connection benchmark_attempts_profiles_connection_attempt_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_profiles_connection
    ADD CONSTRAINT benchmark_attempts_profiles_connection_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES public.test_entry(id) ON DELETE CASCADE;


--

-- Name: test_profiles_connection benchmark_attempts_profiles_connection_profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_profiles_connection
    ADD CONSTRAINT benchmark_attempts_profiles_connection_profiles_id_fkey FOREIGN KEY (profiles_id) REFERENCES public.profiles_resource(id);


--

-- Name: test_roles_connection benchmark_attempts_roles_connection_attempt_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_roles_connection
    ADD CONSTRAINT benchmark_attempts_roles_connection_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES public.test_entry(id) ON DELETE CASCADE;


--

-- Name: test_roles_connection benchmark_attempts_roles_connection_roles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_roles_connection
    ADD CONSTRAINT benchmark_attempts_roles_connection_roles_id_fkey FOREIGN KEY (roles_id) REFERENCES public.roles_resource(id);


--

-- Name: test_invocation_keys_connection invocation_resolved_keys_connection_invocation_resolved_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_keys_connection
    ADD CONSTRAINT invocation_resolved_keys_connection_invocation_resolved_id_fkey FOREIGN KEY (test_invocation_id) REFERENCES public.test_invocation_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_keys_connection invocation_resolved_keys_connection_keys_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_keys_connection
    ADD CONSTRAINT invocation_resolved_keys_connection_keys_id_fkey FOREIGN KEY (keys_id) REFERENCES public.keys_resource(id);


--

-- Name: test_invocation_models_connection invocation_resolved_models_connecti_invocation_resolved_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_models_connection
    ADD CONSTRAINT invocation_resolved_models_connecti_invocation_resolved_id_fkey FOREIGN KEY (test_invocation_id) REFERENCES public.test_invocation_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_reasoning_levels_connection invocation_resolved_reasoning_level_invocation_resolved_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_reasoning_levels_connection
    ADD CONSTRAINT invocation_resolved_reasoning_level_invocation_resolved_id_fkey FOREIGN KEY (test_invocation_id) REFERENCES public.test_invocation_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_reasoning_levels_connection invocation_resolved_reasoning_levels_c_reasoning_levels_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_reasoning_levels_connection
    ADD CONSTRAINT invocation_resolved_reasoning_levels_c_reasoning_levels_id_fkey FOREIGN KEY (reasoning_levels_id) REFERENCES public.reasoning_levels_resource(id);


--

-- Name: test_invocation_temperature_levels_connection invocation_resolved_temperature_lev_invocation_resolved_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_temperature_levels_connection
    ADD CONSTRAINT invocation_resolved_temperature_lev_invocation_resolved_id_fkey FOREIGN KEY (test_invocation_id) REFERENCES public.test_invocation_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_temperature_levels_connection invocation_resolved_temperature_leve_temperature_levels_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_temperature_levels_connection
    ADD CONSTRAINT invocation_resolved_temperature_leve_temperature_levels_id_fkey FOREIGN KEY (temperature_levels_id) REFERENCES public.temperature_levels_resource(id);


--

-- Name: test_invocation_voices_connection invocation_resolved_voices_connecti_invocation_resolved_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_voices_connection
    ADD CONSTRAINT invocation_resolved_voices_connecti_invocation_resolved_id_fkey FOREIGN KEY (test_invocation_id) REFERENCES public.test_invocation_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_voices_connection invocation_resolved_voices_connection_voices_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_voices_connection
    ADD CONSTRAINT invocation_resolved_voices_connection_voices_id_fkey FOREIGN KEY (voices_id) REFERENCES public.voices_resource(id);


--

-- Name: test_invocation_departments_connection test_invocation_departments_connection_departments_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_departments_connection
    ADD CONSTRAINT test_invocation_departments_connection_departments_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id);


--

-- Name: test_invocation_departments_connection test_invocation_departments_connection_test_invocation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_departments_connection
    ADD CONSTRAINT test_invocation_departments_connection_test_invocation_id_fkey FOREIGN KEY (test_invocation_id) REFERENCES public.test_invocation_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_groups_agents_connection test_invocation_groups_agents_co_test_invocation_groups_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_groups_agents_connection
    ADD CONSTRAINT test_invocation_groups_agents_co_test_invocation_groups_id_fkey FOREIGN KEY (test_invocation_groups_id) REFERENCES public.test_invocation_groups_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_groups_agents_connection test_invocation_groups_agents_connection_agents_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_groups_agents_connection
    ADD CONSTRAINT test_invocation_groups_agents_connection_agents_id_fkey FOREIGN KEY (agents_id) REFERENCES public.agents_resource(id);


--

-- Name: test_invocation_groups_groups_connection test_invocation_groups_groups_co_test_invocation_groups_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_groups_groups_connection
    ADD CONSTRAINT test_invocation_groups_groups_co_test_invocation_groups_id_fkey FOREIGN KEY (test_invocation_groups_id) REFERENCES public.test_invocation_groups_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_groups_groups_connection test_invocation_groups_groups_connection_groups_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_groups_groups_connection
    ADD CONSTRAINT test_invocation_groups_groups_connection_groups_id_fkey FOREIGN KEY (groups_id) REFERENCES public.groups_resource(id);


--

-- Name: test_invocation_models_connection test_invocation_models_connection_models_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_models_connection
    ADD CONSTRAINT test_invocation_models_connection_models_id_fkey FOREIGN KEY (models_id) REFERENCES public.models_resource(id);


--

-- Name: test_invocation_runs_agents_connection test_invocation_runs_agents_connec_test_invocation_runs_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_runs_agents_connection
    ADD CONSTRAINT test_invocation_runs_agents_connec_test_invocation_runs_id_fkey FOREIGN KEY (test_invocation_runs_id) REFERENCES public.test_invocation_runs_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_runs_agents_connection test_invocation_runs_agents_connection_agents_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_runs_agents_connection
    ADD CONSTRAINT test_invocation_runs_agents_connection_agents_id_fkey FOREIGN KEY (agents_id) REFERENCES public.agents_resource(id);


--

-- Name: test_invocation_runs_runs_connection test_invocation_runs_runs_connecti_test_invocation_runs_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_runs_runs_connection
    ADD CONSTRAINT test_invocation_runs_runs_connecti_test_invocation_runs_id_fkey FOREIGN KEY (test_invocation_runs_id) REFERENCES public.test_invocation_runs_entry(id) ON DELETE CASCADE;


--

-- Name: test_invocation_runs_runs_connection test_invocation_runs_runs_connection_runs_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_invocation_runs_runs_connection
    ADD CONSTRAINT test_invocation_runs_runs_connection_runs_id_fkey FOREIGN KEY (runs_id) REFERENCES public.runs_resource(id);


--
