-- Foreign keys: videos_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: videos_calls_connection videos_calls_connection_call_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos_calls_connection
    ADD CONSTRAINT videos_calls_connection_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--

-- Name: videos_calls_connection videos_calls_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos_calls_connection
    ADD CONSTRAINT videos_calls_connection_id_fkey FOREIGN KEY (videos_id) REFERENCES public.videos_resource(id) ON DELETE CASCADE;


--

-- Name: videos_videos_connection videos_videos_connection_video_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos_videos_connection
    ADD CONSTRAINT videos_videos_connection_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos_entry(id) ON DELETE CASCADE;


--

-- Name: videos_videos_connection videos_videos_connection_videos_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos_videos_connection
    ADD CONSTRAINT videos_videos_connection_videos_id_fkey FOREIGN KEY (videos_id) REFERENCES public.videos_resource(id) ON DELETE CASCADE;


--
