-- Foreign keys: document_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: document_departments_junction document_departments_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_departments_junction
    ADD CONSTRAINT document_departments_department_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id);


--

-- Name: document_departments_junction document_departments_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_departments_junction
    ADD CONSTRAINT document_departments_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_artifact(id) ON DELETE CASCADE;


--

-- Name: document_descriptions_junction document_descriptions_description_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_descriptions_junction
    ADD CONSTRAINT document_descriptions_description_id_fkey FOREIGN KEY (descriptions_id) REFERENCES public.descriptions_resource(id) ON DELETE CASCADE;


--

-- Name: document_descriptions_junction document_descriptions_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_descriptions_junction
    ADD CONSTRAINT document_descriptions_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_artifact(id) ON DELETE CASCADE;


--

-- Name: document_documents_junction document_documents_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_documents_junction
    ADD CONSTRAINT document_documents_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_artifact(id) ON DELETE CASCADE;


--

-- Name: document_documents_junction document_documents_documents_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_documents_junction
    ADD CONSTRAINT document_documents_documents_id_fkey FOREIGN KEY (documents_id) REFERENCES public.documents_resource(id) ON DELETE CASCADE;


--

-- Name: document_files_junction document_files_junction_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_files_junction
    ADD CONSTRAINT document_files_junction_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_artifact(id) ON DELETE CASCADE;


--

-- Name: document_files_junction document_files_junction_files_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_files_junction
    ADD CONSTRAINT document_files_junction_files_id_fkey FOREIGN KEY (files_id) REFERENCES public.files_resource(id) ON DELETE CASCADE;


--

-- Name: document_flags_junction document_flags_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_flags_junction
    ADD CONSTRAINT document_flags_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_artifact(id) ON DELETE CASCADE;


--

-- Name: document_flags_junction document_flags_flag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_flags_junction
    ADD CONSTRAINT document_flags_flag_id_fkey FOREIGN KEY (flags_id) REFERENCES public.flags_resource(id) ON DELETE CASCADE;


--

-- Name: document_images_junction document_images_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_images_junction
    ADD CONSTRAINT document_images_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_artifact(id) ON DELETE CASCADE;


--

-- Name: document_images_junction document_images_images_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_images_junction
    ADD CONSTRAINT document_images_images_id_fkey FOREIGN KEY (images_id) REFERENCES public.images_resource(id) ON DELETE CASCADE;


--

-- Name: document_names_junction document_names_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_names_junction
    ADD CONSTRAINT document_names_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_artifact(id) ON DELETE CASCADE;


--

-- Name: document_names_junction document_names_name_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_names_junction
    ADD CONSTRAINT document_names_name_id_fkey FOREIGN KEY (names_id) REFERENCES public.names_resource(id) ON DELETE CASCADE;


--

-- Name: document_parameter_fields_junction document_parameter_fields_junction_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_parameter_fields_junction
    ADD CONSTRAINT document_parameter_fields_junction_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_artifact(id) ON DELETE CASCADE;


--

-- Name: document_parameter_fields_junction document_parameter_fields_junction_parameter_field_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_parameter_fields_junction
    ADD CONSTRAINT document_parameter_fields_junction_parameter_field_id_fkey FOREIGN KEY (parameter_fields_id) REFERENCES public.parameter_fields_resource(id) ON DELETE CASCADE;


--

-- Name: document_texts_junction document_texts_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_texts_junction
    ADD CONSTRAINT document_texts_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_artifact(id) ON DELETE CASCADE;


--

-- Name: document_texts_junction document_texts_texts_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_texts_junction
    ADD CONSTRAINT document_texts_texts_id_fkey FOREIGN KEY (texts_id) REFERENCES public.texts_resource(id) ON DELETE CASCADE;


--
