-- Foreign keys: model_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: model_departments_junction model_departments_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_departments_junction
    ADD CONSTRAINT model_departments_department_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id);


--

-- Name: model_departments_junction model_departments_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_departments_junction
    ADD CONSTRAINT model_departments_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_descriptions_junction model_descriptions_description_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_descriptions_junction
    ADD CONSTRAINT model_descriptions_description_id_fkey FOREIGN KEY (descriptions_id) REFERENCES public.descriptions_resource(id) ON DELETE CASCADE;


--

-- Name: model_descriptions_junction model_descriptions_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_descriptions_junction
    ADD CONSTRAINT model_descriptions_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_flags_junction model_flags_flag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_flags_junction
    ADD CONSTRAINT model_flags_flag_id_fkey FOREIGN KEY (flags_id) REFERENCES public.flags_resource(id) ON DELETE CASCADE;


--

-- Name: model_flags_junction model_flags_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_flags_junction
    ADD CONSTRAINT model_flags_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_modalities_junction model_modalities_modality_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_modalities_junction
    ADD CONSTRAINT model_modalities_modality_id_fkey FOREIGN KEY (modalities_id) REFERENCES public.modalities_resource(id) ON DELETE CASCADE;


--

-- Name: model_modalities_junction model_modalities_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_modalities_junction
    ADD CONSTRAINT model_modalities_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_models_junction model_models_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_models_junction
    ADD CONSTRAINT model_models_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_models_junction model_models_models_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_models_junction
    ADD CONSTRAINT model_models_models_id_fkey FOREIGN KEY (models_id) REFERENCES public.models_resource(id) ON DELETE CASCADE;


--

-- Name: model_names_junction model_names_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_names_junction
    ADD CONSTRAINT model_names_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_names_junction model_names_name_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_names_junction
    ADD CONSTRAINT model_names_name_id_fkey FOREIGN KEY (names_id) REFERENCES public.names_resource(id) ON DELETE CASCADE;


--

-- Name: model_pricing_junction model_pricing_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_pricing_junction
    ADD CONSTRAINT model_pricing_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_pricing_junction model_pricing_pricing_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_pricing_junction
    ADD CONSTRAINT model_pricing_pricing_id_fkey FOREIGN KEY (pricing_id) REFERENCES public.pricing_resource(id) ON DELETE CASCADE;


--

-- Name: model_providers_junction model_providers_junction_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_providers_junction
    ADD CONSTRAINT model_providers_junction_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_providers_junction model_providers_junction_providers_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_providers_junction
    ADD CONSTRAINT model_providers_junction_providers_id_fkey FOREIGN KEY (providers_id) REFERENCES public.providers_resource(id) ON DELETE CASCADE;


--

-- Name: model_qualities_junction model_qualities_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_qualities_junction
    ADD CONSTRAINT model_qualities_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_qualities_junction model_qualities_quality_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_qualities_junction
    ADD CONSTRAINT model_qualities_quality_id_fkey FOREIGN KEY (qualities_id) REFERENCES public.qualities_resource(id) ON DELETE CASCADE;


--

-- Name: model_reasoning_levels_junction model_reasoning_levels_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_reasoning_levels_junction
    ADD CONSTRAINT model_reasoning_levels_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_reasoning_levels_junction model_reasoning_levels_reasoning_level_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_reasoning_levels_junction
    ADD CONSTRAINT model_reasoning_levels_reasoning_level_id_fkey FOREIGN KEY (reasoning_levels_id) REFERENCES public.reasoning_levels_resource(id) ON DELETE CASCADE;


--

-- Name: model_temperature_levels_junction model_temperature_levels_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_temperature_levels_junction
    ADD CONSTRAINT model_temperature_levels_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_temperature_levels_junction model_temperature_levels_temperature_level_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_temperature_levels_junction
    ADD CONSTRAINT model_temperature_levels_temperature_level_id_fkey FOREIGN KEY (temperature_levels_id) REFERENCES public.temperature_levels_resource(id) ON DELETE CASCADE;


--

-- Name: model_values_junction model_values_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_values_junction
    ADD CONSTRAINT model_values_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_values_junction model_values_value_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_values_junction
    ADD CONSTRAINT model_values_value_id_fkey FOREIGN KEY (values_id) REFERENCES public.values_resource(id) ON DELETE CASCADE;


--

-- Name: model_voices_junction model_voices_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_voices_junction
    ADD CONSTRAINT model_voices_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model_artifact(id) ON DELETE CASCADE;


--

-- Name: model_voices_junction model_voices_voice_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_voices_junction
    ADD CONSTRAINT model_voices_voice_id_fkey FOREIGN KEY (voices_id) REFERENCES public.voices_resource(id) ON DELETE CASCADE;


--
