-- Foreign keys: parameter_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: parameter_departments_junction parameter_departments_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_departments_junction
    ADD CONSTRAINT parameter_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments_resource(id);


--

-- Name: parameter_departments_junction parameter_departments_parameter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_departments_junction
    ADD CONSTRAINT parameter_departments_parameter_id_fkey FOREIGN KEY (parameter_id) REFERENCES public.parameter_artifact(id) ON DELETE CASCADE;


--

-- Name: parameter_descriptions_junction parameter_descriptions_description_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_descriptions_junction
    ADD CONSTRAINT parameter_descriptions_description_id_fkey FOREIGN KEY (description_id) REFERENCES public.descriptions_resource(id) ON DELETE CASCADE;


--

-- Name: parameter_descriptions_junction parameter_descriptions_parameter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_descriptions_junction
    ADD CONSTRAINT parameter_descriptions_parameter_id_fkey FOREIGN KEY (parameter_id) REFERENCES public.parameter_artifact(id) ON DELETE CASCADE;


--

-- Name: parameter_fields_junction parameter_fields_field_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_fields_junction
    ADD CONSTRAINT parameter_fields_field_id_fkey FOREIGN KEY (field_id) REFERENCES public.field_artifact(id) ON DELETE CASCADE;


--

-- Name: parameter_fields_junction parameter_fields_field_resource_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_fields_junction
    ADD CONSTRAINT parameter_fields_field_resource_id_fkey FOREIGN KEY (field_resource_id) REFERENCES public.fields_resource(id) ON DELETE CASCADE;


--

-- Name: parameter_fields_junction parameter_fields_parameter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_fields_junction
    ADD CONSTRAINT parameter_fields_parameter_id_fkey FOREIGN KEY (parameter_id) REFERENCES public.parameter_artifact(id) ON DELETE CASCADE;


--

-- Name: parameter_flags_junction parameter_flags_flag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_flags_junction
    ADD CONSTRAINT parameter_flags_flag_id_fkey FOREIGN KEY (flag_id) REFERENCES public.flags_resource(id) ON DELETE CASCADE;


--

-- Name: parameter_flags_junction parameter_flags_parameter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_flags_junction
    ADD CONSTRAINT parameter_flags_parameter_id_fkey FOREIGN KEY (parameter_id) REFERENCES public.parameter_artifact(id) ON DELETE CASCADE;


--

-- Name: parameter_names_junction parameter_names_name_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_names_junction
    ADD CONSTRAINT parameter_names_name_id_fkey FOREIGN KEY (name_id) REFERENCES public.names_resource(id) ON DELETE CASCADE;


--

-- Name: parameter_names_junction parameter_names_parameter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_names_junction
    ADD CONSTRAINT parameter_names_parameter_id_fkey FOREIGN KEY (parameter_id) REFERENCES public.parameter_artifact(id) ON DELETE CASCADE;


--

-- Name: parameter_parameters_junction parameter_parameters_parameter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_parameters_junction
    ADD CONSTRAINT parameter_parameters_parameter_id_fkey FOREIGN KEY (parameter_id) REFERENCES public.parameter_artifact(id) ON DELETE CASCADE;


--

-- Name: parameter_parameters_junction parameter_parameters_parameters_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parameter_parameters_junction
    ADD CONSTRAINT parameter_parameters_parameters_id_fkey FOREIGN KEY (parameters_id) REFERENCES public.parameters_resource(id) ON DELETE CASCADE;


--
