-- Foreign keys: persona_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: persona_colors_junction persona_colors_color_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_colors_junction
    ADD CONSTRAINT persona_colors_color_id_fkey FOREIGN KEY (color_id) REFERENCES public.colors_resource(id) ON DELETE CASCADE;


--

-- Name: persona_colors_junction persona_colors_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_colors_junction
    ADD CONSTRAINT persona_colors_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_departments_junction persona_departments_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_departments_junction
    ADD CONSTRAINT persona_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments_resource(id);


--

-- Name: persona_departments_junction persona_departments_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_departments_junction
    ADD CONSTRAINT persona_departments_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_descriptions_junction persona_descriptions_description_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_descriptions_junction
    ADD CONSTRAINT persona_descriptions_description_id_fkey FOREIGN KEY (description_id) REFERENCES public.descriptions_resource(id) ON DELETE CASCADE;


--

-- Name: persona_descriptions_junction persona_descriptions_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_descriptions_junction
    ADD CONSTRAINT persona_descriptions_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_examples_junction persona_examples_example_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_examples_junction
    ADD CONSTRAINT persona_examples_example_id_fkey FOREIGN KEY (example_id) REFERENCES public.examples_resource(id);


--

-- Name: persona_examples_junction persona_examples_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_examples_junction
    ADD CONSTRAINT persona_examples_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_flags_junction persona_flags_flag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_flags_junction
    ADD CONSTRAINT persona_flags_flag_id_fkey FOREIGN KEY (flag_id) REFERENCES public.flags_resource(id) ON DELETE CASCADE;


--

-- Name: persona_flags_junction persona_flags_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_flags_junction
    ADD CONSTRAINT persona_flags_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_icons_junction persona_icons_icon_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_icons_junction
    ADD CONSTRAINT persona_icons_icon_id_fkey FOREIGN KEY (icon_id) REFERENCES public.icons_resource(id) ON DELETE CASCADE;


--

-- Name: persona_icons_junction persona_icons_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_icons_junction
    ADD CONSTRAINT persona_icons_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_instructions_junction persona_instructions_instruction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_instructions_junction
    ADD CONSTRAINT persona_instructions_instruction_id_fkey FOREIGN KEY (instruction_id) REFERENCES public.instructions_resource(id) ON DELETE CASCADE;


--

-- Name: persona_instructions_junction persona_instructions_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_instructions_junction
    ADD CONSTRAINT persona_instructions_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_names_junction persona_names_name_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_names_junction
    ADD CONSTRAINT persona_names_name_id_fkey FOREIGN KEY (name_id) REFERENCES public.names_resource(id) ON DELETE CASCADE;


--

-- Name: persona_names_junction persona_names_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_names_junction
    ADD CONSTRAINT persona_names_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_parameter_fields_junction persona_parameter_fields_junction_parameter_field_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_parameter_fields_junction
    ADD CONSTRAINT persona_parameter_fields_junction_parameter_field_id_fkey FOREIGN KEY (parameter_field_id) REFERENCES public.parameter_fields_resource(id) ON DELETE CASCADE;


--

-- Name: persona_parameter_fields_junction persona_parameter_fields_junction_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_parameter_fields_junction
    ADD CONSTRAINT persona_parameter_fields_junction_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_personas_junction persona_personas_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_personas_junction
    ADD CONSTRAINT persona_personas_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_personas_junction persona_personas_personas_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_personas_junction
    ADD CONSTRAINT persona_personas_personas_id_fkey FOREIGN KEY (personas_id) REFERENCES public.personas_resource(id) ON DELETE CASCADE;


--

-- Name: persona_voices_junction persona_voices_junction_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_voices_junction
    ADD CONSTRAINT persona_voices_junction_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona_artifact(id) ON DELETE CASCADE;


--

-- Name: persona_voices_junction persona_voices_junction_voice_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_voices_junction
    ADD CONSTRAINT persona_voices_junction_voice_id_fkey FOREIGN KEY (voice_id) REFERENCES public.voices_resource(id) ON DELETE CASCADE;


--
