-- Foreign keys: setting_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: setting_auth_item_keys_junction setting_auth_item_keys_junction_auth_item_keys_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_auth_item_keys_junction
    ADD CONSTRAINT setting_auth_item_keys_junction_auth_item_keys_id_fkey FOREIGN KEY (auth_item_keys_id) REFERENCES public.auth_item_keys_resource(id);


--

-- Name: setting_auth_item_values_junction setting_auth_item_values_junction_auth_item_values_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_auth_item_values_junction
    ADD CONSTRAINT setting_auth_item_values_junction_auth_item_values_id_fkey FOREIGN KEY (auth_item_values_id) REFERENCES public.auth_item_values_resource(id);


--

-- Name: setting_auth_item_values_junction setting_auth_item_values_junction_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_auth_item_values_junction
    ADD CONSTRAINT setting_auth_item_values_junction_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_auth_item_keys_junction setting_auth_keys_junction_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_auth_item_keys_junction
    ADD CONSTRAINT setting_auth_keys_junction_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_auths_junction setting_auths_auth_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_auths_junction
    ADD CONSTRAINT setting_auths_auth_id_fkey FOREIGN KEY (auths_id) REFERENCES public.auths_resource(id) ON DELETE CASCADE;


--

-- Name: setting_auths_junction setting_auths_settings_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_auths_junction
    ADD CONSTRAINT setting_auths_settings_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_colors_junction setting_colors_color_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_colors_junction
    ADD CONSTRAINT setting_colors_color_id_fkey FOREIGN KEY (colors_id) REFERENCES public.colors_resource(id) ON DELETE CASCADE;


--

-- Name: setting_colors_junction setting_colors_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_colors_junction
    ADD CONSTRAINT setting_colors_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_departments_junction setting_departments_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_departments_junction
    ADD CONSTRAINT setting_departments_department_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id) ON DELETE CASCADE;


--

-- Name: setting_departments_junction setting_departments_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_departments_junction
    ADD CONSTRAINT setting_departments_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_descriptions_junction setting_descriptions_description_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_descriptions_junction
    ADD CONSTRAINT setting_descriptions_description_id_fkey FOREIGN KEY (descriptions_id) REFERENCES public.descriptions_resource(id) ON DELETE CASCADE;


--

-- Name: setting_descriptions_junction setting_descriptions_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_descriptions_junction
    ADD CONSTRAINT setting_descriptions_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_flags_junction setting_flags_flag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_flags_junction
    ADD CONSTRAINT setting_flags_flag_id_fkey FOREIGN KEY (flags_id) REFERENCES public.flags_resource(id) ON DELETE CASCADE;


--

-- Name: setting_flags_junction setting_flags_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_flags_junction
    ADD CONSTRAINT setting_flags_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_names_junction setting_names_name_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_names_junction
    ADD CONSTRAINT setting_names_name_id_fkey FOREIGN KEY (names_id) REFERENCES public.names_resource(id) ON DELETE CASCADE;


--

-- Name: setting_names_junction setting_names_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_names_junction
    ADD CONSTRAINT setting_names_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_profiles_junction setting_profiles_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_profiles_junction
    ADD CONSTRAINT setting_profiles_profile_id_fkey FOREIGN KEY (profiles_id) REFERENCES public.profiles_resource(id) ON DELETE CASCADE;


--

-- Name: setting_profiles_junction setting_profiles_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_profiles_junction
    ADD CONSTRAINT setting_profiles_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_provider_keys_junction setting_provider_keys_junction_provider_key_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_provider_keys_junction
    ADD CONSTRAINT setting_provider_keys_junction_provider_key_id_fkey FOREIGN KEY (provider_keys_id) REFERENCES public.provider_keys_resource(id) ON DELETE CASCADE;


--

-- Name: setting_provider_keys_junction setting_provider_keys_junction_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_provider_keys_junction
    ADD CONSTRAINT setting_provider_keys_junction_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_settings_junction setting_settings_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_settings_junction
    ADD CONSTRAINT setting_settings_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_settings_junction setting_settings_settings_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_settings_junction
    ADD CONSTRAINT setting_settings_settings_id_fkey FOREIGN KEY (settings_id) REFERENCES public.settings_resource(id) ON DELETE CASCADE;


--

-- Name: setting_systems_junction setting_systems_junction_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_systems_junction
    ADD CONSTRAINT setting_systems_junction_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id);


--

-- Name: setting_systems_junction setting_systems_junction_systems_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_systems_junction
    ADD CONSTRAINT setting_systems_junction_systems_id_fkey FOREIGN KEY (systems_id) REFERENCES public.systems_resource(id);


--

-- Name: setting_thresholds_junction setting_thresholds_setting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_thresholds_junction
    ADD CONSTRAINT setting_thresholds_setting_id_fkey FOREIGN KEY (setting_id) REFERENCES public.setting_artifact(id) ON DELETE CASCADE;


--

-- Name: setting_thresholds_junction setting_thresholds_threshold_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_thresholds_junction
    ADD CONSTRAINT setting_thresholds_threshold_id_fkey FOREIGN KEY (thresholds_id) REFERENCES public.thresholds_resource(id) ON DELETE CASCADE;


--
