-- Foreign keys: tool_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: tool_arg_positions_junction tool_arg_positions_junction_arg_positions_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_arg_positions_junction
    ADD CONSTRAINT tool_arg_positions_junction_arg_positions_id_fkey FOREIGN KEY (arg_positions_id) REFERENCES public.arg_positions_resource(id) ON DELETE CASCADE;


--

-- Name: tool_arg_positions_junction tool_arg_positions_junction_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_arg_positions_junction
    ADD CONSTRAINT tool_arg_positions_junction_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_args_junction tool_args_args_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_args_junction
    ADD CONSTRAINT tool_args_args_id_fkey FOREIGN KEY (args_id) REFERENCES public.args_resource(id) ON DELETE CASCADE;


--

-- Name: tool_args_outputs_junction tool_args_outputs_args_outputs_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_args_outputs_junction
    ADD CONSTRAINT tool_args_outputs_args_outputs_id_fkey FOREIGN KEY (args_outputs_id) REFERENCES public.args_outputs_resource(id) ON DELETE CASCADE;


--

-- Name: tool_args_outputs_junction tool_args_outputs_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_args_outputs_junction
    ADD CONSTRAINT tool_args_outputs_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_args_junction tool_args_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_args_junction
    ADD CONSTRAINT tool_args_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_artifacts_junction tool_artifacts_junction_artifact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_artifacts_junction
    ADD CONSTRAINT tool_artifacts_junction_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts_resource(id) ON DELETE CASCADE;


--

-- Name: tool_artifacts_junction tool_artifacts_junction_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_artifacts_junction
    ADD CONSTRAINT tool_artifacts_junction_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_departments_junction tool_departments_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_departments_junction
    ADD CONSTRAINT tool_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments_resource(id);


--

-- Name: tool_departments_junction tool_departments_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_departments_junction
    ADD CONSTRAINT tool_departments_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_descriptions_junction tool_descriptions_description_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_descriptions_junction
    ADD CONSTRAINT tool_descriptions_description_id_fkey FOREIGN KEY (description_id) REFERENCES public.descriptions_resource(id) ON DELETE CASCADE;


--

-- Name: tool_descriptions_junction tool_descriptions_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_descriptions_junction
    ADD CONSTRAINT tool_descriptions_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_entries_junction tool_entries_junction_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_entries_junction
    ADD CONSTRAINT tool_entries_junction_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES public.entries_resource(id) ON DELETE CASCADE;


--

-- Name: tool_entries_junction tool_entries_junction_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_entries_junction
    ADD CONSTRAINT tool_entries_junction_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_flags_junction tool_flags_flag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_flags_junction
    ADD CONSTRAINT tool_flags_flag_id_fkey FOREIGN KEY (flag_id) REFERENCES public.flags_resource(id) ON DELETE CASCADE;


--

-- Name: tool_flags_junction tool_flags_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_flags_junction
    ADD CONSTRAINT tool_flags_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_names_junction tool_names_name_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_names_junction
    ADD CONSTRAINT tool_names_name_id_fkey FOREIGN KEY (name_id) REFERENCES public.names_resource(id) ON DELETE CASCADE;


--

-- Name: tool_names_junction tool_names_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_names_junction
    ADD CONSTRAINT tool_names_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_operations_junction tool_operations_operation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_operations_junction
    ADD CONSTRAINT tool_operations_operation_id_fkey FOREIGN KEY (operation_id) REFERENCES public.operations_resource(id);


--

-- Name: tool_operations_junction tool_operations_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_operations_junction
    ADD CONSTRAINT tool_operations_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id);


--

-- Name: tool_resources_junction tool_resources_resource_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_resources_junction
    ADD CONSTRAINT tool_resources_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.resources_resource(id) ON DELETE CASCADE;


--

-- Name: tool_resources_junction tool_resources_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_resources_junction
    ADD CONSTRAINT tool_resources_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_tools_junction tool_tools_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_tools_junction
    ADD CONSTRAINT tool_tools_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_tools_junction tool_tools_tools_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_tools_junction
    ADD CONSTRAINT tool_tools_tools_id_fkey FOREIGN KEY (tools_id) REFERENCES public.tools_resource(id) ON DELETE CASCADE;


--
